
/ Structure and General Properties of the Nonmetals
story 18_4
  >
    The nonmetals are elements located in the upper right portion of the periodic table. Their properties and behavior are quite different from those of metals on the left side. Under normal conditions, more than half of the nonmetals are gases, one is a liquid, and the rest include some of the softest and hardest of solids. The nonmetals exhibit a rich variety of chemical behaviors. They include the most reactive and least reactive of elements, and they form many different ionic and covalent compounds. This section presents an overview of the properties and chemical behaviors of the nonmetals, as well as the chemistry of specific elements. Many of these nonmetals are important in biological systems.
    
    In many cases, trends in electronegativity enable us to predict the type of bonding and the physical states in compounds involving the nonmetals. We know that electronegativity decreases as we move down a given group and increases as we move from left to right across a period. The nonmetals have higher electronegativities than do metals, and compounds formed between metals and nonmetals are generally ionic in nature because of the large differences in electronegativity between them. The metals form cations, the nonmetals form anions, and the resulting compounds are solids under normal conditions. On the other hand, compounds formed between two or more nonmetals have small differences in electronegativity between the atoms, and covalent bonding—sharing of electrons—results. These substances tend to be molecular in nature and are gases, liquids, or volatile solids at room temperature and pressure.
    
    In normal chemical processes, nonmetals do not form monatomic positive ions (cations) because their ionization energies are too high. All monatomic nonmetal ions are anions; examples include the chloride ion, Cl<sup>−</sup>, the nitride ion, N<sup>3−</sup>, and the selenide ion, Se<sup>2−</sup>.
    
    The common oxidation states that the nonmetals exhibit in their ionic and covalent compounds are shown in {'Figure_18_4_OxStNonmts Figure 18.4.OxStNonmts}. Remember that an element exhibits a positive oxidation state when combined with a more electronegative element and that it exhibits a negative oxidation state when combined with a less electronegative element.
    
    
            
    
    The first member of each nonmetal group exhibits different behaviors, in many respects, from the other group members. The reasons for this include smaller size, greater ionization energy, and (most important) the fact that the first member of each group has only four valence orbitals (one 2 *s* and three 2 *p*) available for bonding, whereas other group members have empty  *d* orbitals in their valence shells, making possible five, six, or even more bonds around the central atom. For example, nitrogen forms only NF<sub>3,</sub> whereas phosphorus forms both PF<sub>3</sub> and PF<sub>5</sub>.
    
    Another difference between the first group member and subsequent members is the greater ability of the first member to form  *π* bonds. This is primarily a function of the smaller size of the first member of each group, which allows better overlap of atomic orbitals. Nonmetals, other than the first member of each group, rarely form π bonds to nonmetals that are the first member of a group. For example, sulfur-oxygen π bonds are well known, whereas sulfur does not normally form stable π bonds to itself.
    
    The variety of oxidation states displayed by most of the nonmetals means that many of their chemical reactions involve changes in oxidation state through oxidation-reduction reactions. There are five general aspects of the oxidation-reduction chemistry:
    
      1. Nonmetals oxidize most metals. The oxidation state of the metal becomes positive as it undergoes oxidation and that of the nonmetal becomes negative as it undergoes reduction. For example:<br /> <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtable><mtr><mtd columnalign="left"><mrow><mtext>4Fe</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>+</mo></mrow></mtd><mtd columnalign="left"><mrow><msub><mrow><mtext>3O</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo></mrow></mtd><mtd columnalign="left"><mo stretchy="false">⟶</mo></mtd><mtd columnalign="left"><mrow><msub><mrow><mtext>2Fe</mtext></mrow><mn>2</mn></msub><msub><mtext>O</mtext><mn>3</mn></msub><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mrow></mtd></mtr><mtr><mtd columnalign="left"><mspace width="0.8em"/><mn>0</mn></mtd><mtd columnalign="left"><mspace width="0.6em"/><mn>0</mn></mtd><mtd/><mtd columnalign="left"><mrow><mn>+3</mn><mspace width="0.5em"/><mn>−2</mn></mrow></mtd></mtr></mtable></mrow></math>
      2. With the exception of nitrogen and carbon, which are poor oxidizing agents, a more electronegative nonmetal oxidizes a less electronegative nonmetal or the anion of the nonmetal:<br /> <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtable><mtr><mtd columnalign="left"><mrow><mtext>S</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>+</mo></mrow></mtd><mtd columnalign="left"><mrow><msub><mrow><mtext>O</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo></mrow></mtd><mtd columnalign="left"><mo stretchy="false">⟶</mo></mtd><mtd columnalign="left"><mrow><msub><mrow><mtext>2SO</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mrow></mtd></mtr><mtr><mtd columnalign="left"><mn>0</mn></mtd><mtd columnalign="left"><mspace width="0.2em"/><mn>0</mn></mtd><mtd/><mtd columnalign="left"><mrow><mn>+4</mn><mspace width="1em"/><mn>−2</mn></mrow></mtd></mtr></mtable></mrow></math> <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtable><mtr><mtd columnalign="left"><mrow><msub><mrow><mtext>Cl</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mo>+</mo></mrow></mtd><mtd columnalign="left"><mrow><msup><mrow><mtext>2I</mtext></mrow><mn>−</mn></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></mtd><mtd columnalign="left"><mo stretchy="false">⟶</mo></mtd><mtd columnalign="left"><mrow><msub><mrow><mtext>I</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mrow><mtext>2Cl</mtext></mrow><mn>−</mn></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></mtd></mtr><mtr><mtd columnalign="left"><mspace width="0.2em"/><mn>0</mn></mtd><mtd/><mtd/><mtd columnalign="left"><mn>0</mn></mtd></mtr></mtable></mrow></math>
      3. Fluorine and oxygen are the strongest oxidizing agents within their respective groups; each oxidizes all the elements that lie below it in the group. Within any period, the strongest oxidizing agent is in group 17. A nonmetal often oxidizes an element that lies to its left in the same period. For example:<br /> <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtable><mtr><mtd columnalign="left"><mrow><mtext>2As</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>+</mo></mrow></mtd><mtd columnalign="left"><mrow><msub><mrow><mtext>3Br</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo></mrow></mtd><mtd columnalign="left"><mo stretchy="false">⟶</mo></mtd><mtd columnalign="left"><mrow><msub><mrow><mtext>2AsBr</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mrow></mtd></mtr><mtr><mtd columnalign="left"><mn>0</mn></mtd><mtd columnalign="left"><mn>0</mn></mtd><mtd/><mtd columnalign="left"><mrow><mn>+3</mn><mspace width="0.2em"/><mn>−1</mn></mrow></mtd></mtr></mtable></mrow></math>
      4. The stronger a nonmetal is as an oxidizing agent, the more difficult it is to oxidize the anion formed by the nonmetal. This means that the most stable negative ions are formed by elements at the top of the group or in group 17 of the period.
      5. Fluorine and oxygen are the strongest oxidizing elements known. Fluorine does not form compounds in which it exhibits positive oxidation states; oxygen exhibits a positive oxidation state only when combined with fluorine. For example:<br /> <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtable><mtr><mtd columnalign="left"><mrow><msub><mrow><mtext>2F</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mo>+</mo></mrow></mtd><mtd columnalign="left"><mrow><msup><mrow><mtext>2OH</mtext></mrow><mn>−</mn></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></mtd><mtd columnalign="left"><mo stretchy="false">⟶</mo></mtd><mtd columnalign="left"><mrow><msub><mrow><mtext>OF</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mrow><mtext>2F</mtext></mrow><mn>−</mn></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mrow><mtext>H</mtext></mrow><mn>2</mn></msub><mrow><mtext>O</mtext></mrow><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo></mrow></mtd></mtr><mtr><mtd columnalign="left"><mn>0</mn></mtd><mtd/><mtd/><mtd columnalign="left"><mrow><mn>+2</mn><mspace width="2.5em"/><mn>−1</mn></mrow></mtd></mtr></mtable></mrow></math>
    
    With the exception of most of the noble gases, all nonmetals form compounds with oxygen, yielding covalent oxides. Most of these oxides are acidic, that is, they react with water to form oxyacids. Recall from the acid-base chapter that an oxyacid is an acid consisting of hydrogen, oxygen, and some other element. Notable exceptions are carbon monoxide, CO, nitrous oxide, N<sub>2</sub>O, and nitric oxide, NO. There are three characteristics of these acidic oxides:
    
      1. Oxides such as SO<sub>2</sub> and N<sub>2</sub>O<sub>5</sub>, in which the nonmetal exhibits one of its common oxidation states, are  **acid anhydrides** and react with water to form acids with no change in oxidation state. The product is an oxyacid. For example:<br /> <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>SO</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>SO</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math> <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>N</mtext><mn>2</mn></msub><msub><mtext>O</mtext><mn>5</mn></msub><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mrow><mtext>2HNO</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
      2. Those oxides such as NO<sub>2</sub> and ClO<sub>2</sub>, in which the nonmetal does not exhibit one of its common oxidation states, also react with water. In these reactions, the nonmetal is both oxidized and reduced. For example:<br /> <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtable><mtr><mtd columnalign="left"><mrow><msub><mrow><mtext>3NO</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mo>+</mo></mrow></mtd><mtd columnalign="left"><mrow><msub><mrow><mtext>H</mtext></mrow><mn>2</mn></msub><mrow><mtext>O</mtext></mrow><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo></mrow></mtd><mtd columnalign="left"><mo stretchy="false">⟶</mo></mtd><mtd columnalign="left"><mrow><msub><mrow><mtext>2HNO</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo></mrow></mtd><mtd columnalign="left"><mrow><mtext>NO</mtext></mrow><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo></mtd></mtr><mtr><mtd columnalign="left"><mn>+4</mn></mtd><mtd/><mtd/><mtd columnalign="left"><mrow><mn>+5</mn></mrow></mtd><mtd columnalign="left"><mrow><mn>+2</mn></mrow></mtd></mtr></mtable></mrow></math><br />Reactions in which the same element is both oxidized and reduced are called  **disproportionation reactions**.
      3. The acid strength increases as the electronegativity of the central atom increases. To learn more, see the discussion in the chapter on acid-base chemistry.
    
    The binary hydrogen compounds of the nonmetals also exhibit an acidic behavior in water, although only HCl, HBr, and HI are strong acids. The acid strength of the nonmetal hydrogen compounds increases from left to right across a period and down a group. For example, ammonia, NH<sub>3</sub>, is a weaker acid than is water, H<sub>2</sub>O, which is weaker than is hydrogen fluoride, HF. Water, H<sub>2</sub>O, is also a weaker acid than is hydrogen sulfide, H<sub>2</sub>S<sub>,</sub> which is weaker than is hydrogen selenide, H<sub>2</sub>Se. Weaker acidic character implies greater basic character.

  apply FullText

  ---
    18_4_0
    18_4_1
    18_4_2
    18_4_3
    18_4_4
    18_4_5

  path FullText
    step
      --
        18_4_0
    step
      --
        18_4_1
    step
      --
        18_4_2
    step
      --
        18_4_3
    step
      --
        18_4_4
    step
      --
        18_4_5

    