#!/bin/bash

root=$(pwd)

curl -o $root/app/java.tar.gz https://download.java.net/java/GA/jdk15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_osx-x64_bin.tar.gz
cd $root/app

rm -rf ./java
tar -xvf java.tar.gz
mv jdk-15.0.2.jdk/Contents/Home/ ./java
rm -rf java.tar.gz
rm -rf jdk-15.0.2.jdk/

cd $root

echo
echo "INSTALLED JAVA"
