
/ Friction
story 5_1
  >
     **Friction** is a force that is around us all the time that opposes relative motion between systems in contact but also allows us to move (which you have discovered if you have ever tried to walk on ice). While a common force, the behavior of friction is actually very complicated and is still not completely understood. We have to rely heavily on observations for whatever understandings we can gain. However, we can still deal with its more elementary general characteristics and understand the circumstances in which it behaves.
    
    One of the simpler characteristics of friction is that it is parallel to the contact surface between systems and always in a direction that opposes motion or attempted motion of the systems relative to each other. If two systems are in contact and moving relative to one another, then the friction between them is called  **kinetic friction**. For example, friction slows a hockey puck sliding on ice. But when objects are stationary,  **static friction** **** can act between them; the static friction is usually greater than the kinetic friction between the objects.
    
    Imagine, for example, trying to slide a heavy crate across a concrete floor—you may push harder and harder on the crate and not move it at all. This means that the static friction responds to what you do—it increases to be equal to and in the opposite direction of your push. But if you finally push hard enough, the crate seems to slip suddenly and starts to move. Once in motion it is easier to keep it in motion than it was to get it started, indicating that the kinetic friction force is less than the static friction force. If you add mass to the crate, say by placing a box on top of it, you need to push even harder to get it started and also to keep it moving. Furthermore, if you oiled the concrete you would find it to be easier to get the crate started and keep it going (as you might expect).
    
    {'Figure_6_1_1a Figure 6.1.1a} ****is a crude pictorial representation of how friction occurs at the interface between two objects. Close-up inspection of these surfaces shows them to be rough. So when you push to get an object moving (in this case, a crate), you must raise the object until it can skip along with just the tips of the surface hitting, break off the points, or do both. A considerable force can be resisted by friction with no apparent motion. The harder the surfaces are pushed together (such as if another box is placed on the crate), the more force is needed to move them. Part of the friction is due to adhesive forces between the surface molecules of the two objects, which explain the dependence of friction on the nature of the substances. Adhesion varies with substances in contact and is a complicated aspect of surface physics. Once an object is moving, there are fewer points of contact (fewer molecules adhering), so less force is required to keep the object moving. At small but nonzero speeds, friction is nearly independent of speed.
    
    
            
    
    The magnitude of the frictional force has two forms: one for static situations (static friction), the other for when there is motion (kinetic friction).
    
    When there is no motion between the objects, the  **magnitude of static friction                                                                                     f                                                               s                                                                                                                         size 12&#123;f rSub &#123; size 8&#123;s&#125; &#125; &#125; &#123;&#125;** is
    
    <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>f</mi><mrow><mn>s</mn></mrow></msub><mo stretchy="false">≤</mo><msub><mi>μ</mi><mrow><mn>s</mn></mrow></msub></mrow><mi>N</mi></mrow><mo>,</mo></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f rSub &#123; size 8&#123;s&#125; &#125;  &lt;= μ rSub &#123; size 8&#123;s&#125; &#125; N&#125; &#123;&#125;</annotation></semantics></math>
    
    where <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>μ</mi><mrow><mtext>s</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;μ rSub &#123; size 8&#123;s&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>  is the coefficient of static friction and <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"> <semantics>  <mi>N</mi> </semantics></math> is the magnitude of the normal force  ****(the force perpendicular to the surface).
    
    The symbol <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow/>                    <mo stretchy="false">≤</mo>                  <mrow/>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123; &lt;= &#123;&#125;&#125; &#123;&#125;</annotation>        </semantics>      </math> means  *less than or equal to*, implying that static friction can have a minimum and a maximum value of <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mi>μ</mi><mrow><mtext>s</mtext></mrow></msub><mi>N</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;μ rSub &#123; size 8&#123;s&#125; &#125; N&#125; &#123;&#125;</annotation></semantics></math>. Static friction is a responsive force that increases to be equal and opposite to whatever force is exerted, up to its maximum limit. Once the applied force exceeds <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>f</mi><mrow><mrow><mtext>s</mtext><mo stretchy="false">(</mo><mtext>max</mtext><mo stretchy="false">)</mo></mrow></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f rSub &#123; size 8&#123;s \( &quot;max&quot; \) &#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>, the object will move. Thus
    
    <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>f</mi><mrow><mrow><mtext>s</mtext><mo stretchy="false">(</mo><mtext>max</mtext><mo stretchy="false">)</mo></mrow></mrow></msub><mo stretchy="false">=</mo><msub><mi>μ</mi><mrow><mtext>s</mtext></mrow></msub></mrow><mi>N</mi></mrow><mo>.</mo></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f rSub &#123; size 8&#123;s \( &quot;max&quot; \) &#125; &#125; =μ rSub &#123; size 8&#123;s&#125; &#125; N&#125; &#123;&#125;</annotation></semantics></math>
    
    Once an object is moving, the  **magnitude of kinetic friction                                                                                     f                                                               k                                                                                                                         size 12&#123;f rSub &#123; size 8&#123;k&#125; &#125; &#125; &#123;&#125;** is given by
    
    <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>f</mi><mrow><mtext>k</mtext></mrow></msub><mo stretchy="false">=</mo><msub><mi>μ</mi><mrow><mtext>k</mtext></mrow></msub></mrow><mi>N</mi></mrow><mo>,</mo></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f rSub &#123; size 8&#123;k&#125; &#125; =μ rSub &#123; size 8&#123;k&#125; &#125; N&#125; &#123;&#125;</annotation></semantics></math>
    
    where <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>μ</mi><mrow><mtext>k</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;μ rSub &#123; size 8&#123;K&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the coefficient of kinetic friction. A system in which <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>f</mi><mrow><mtext>k</mtext></mrow></msub><mo stretchy="false">=</mo><msub><mi>μ</mi><mrow><mtext>k</mtext></mrow></msub></mrow><mi>N</mi></mrow><mspace width="0.25em"/></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f rSub &#123; size 8&#123;k&#125; &#125; =μ rSub &#123; size 8&#123;k&#125; &#125; N&#125; &#123;&#125;</annotation></semantics></math>is described as a system in which  *friction behaves simply*.
    
    As seen in , the coefficients of kinetic friction are less than their static counterparts. That values of <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>μ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;μ&#125; &#123;&#125;</annotation></semantics></math> ** in  are stated to only one or, at most, two digits is an indication of the approximate description of friction given by the above two equations.
    
    
        
    
    The equations given earlier  ****include the dependence of friction on materials and the normal force. The direction of friction is always opposite that of motion, parallel to the surface between objects, and perpendicular to the normal force. For example, if the crate you try to push (with a force parallel to the floor) has a mass of 100 kg, then the normal force would be equal to its weight, <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mrow><mi>W</mi><mo stretchy="false">=</mo><mi fontstyle="italic">mg</mi></mrow><mo stretchy="false">=</mo><mo stretchy="false">(</mo></mrow><mtext>100 kg</mtext><mo stretchy="false">)</mo><mo stretchy="false">(</mo><mn>9</mn><mtext>.</mtext><mtext>80</mtext><mspace width="0.25em"/><msup><mtext>m/s</mtext><mrow><mn>2</mn></mrow></msup><mo stretchy="false">)</mo><mo stretchy="false">=</mo><mtext>980 N</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;W=&quot;mg&quot;= \( &quot;100&quot;&quot;kg&quot; \)  \( 9 &quot;.&quot; &quot;80&quot;`&quot;m/s&quot; rSup &#123; size 8&#123;2&#125; &#125;  \) =&quot;980&quot;N&#125; &#123;&#125;</annotation></semantics></math>, perpendicular to the floor. If the coefficient of static friction is 0.45, you would have to exert a force parallel to the floor greater than 
    <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>f</mi><mrow><mrow><mtext>s</mtext><mo stretchy="false">(</mo><mtext>max</mtext><mo stretchy="false">)</mo></mrow></mrow></msub><mo stretchy="false">=</mo><msub><mi>μ</mi><mrow><mtext>s</mtext></mrow></msub></mrow><mrow><mi>N</mi><mo stretchy="false">=</mo></mrow><mfenced close=")" open="("><mn>0.45</mn></mfenced><mrow><mo stretchy="false">(</mo><mtext>980</mtext></mrow><mrow><mspace width="0.25em"/><mtext>N</mtext><mo stretchy="false">)</mo><mo stretchy="false">=</mo><mtext>440</mtext></mrow><mspace width="0.25em"/><mtext>N</mtext></mrow></mrow><mspace width="0.25em"/><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f rSub &#123; size 8&#123;S \( &quot;max&quot; \) &#125; &#125; =μ rSub &#123; size 8&#123;S&#125; &#125; N=0 &quot;.&quot; &quot;45&quot; times &quot;980&quot;N=&quot;440&quot;N&#125; &#123;&#125;</annotation></semantics></math>to move the crate. Once there is motion, friction is less and the coefficient of kinetic friction might be 0.30, so that a force of only 290 N 
    (<math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>f</mi><mrow><mtext>k</mtext></mrow></msub><mo stretchy="false">=</mo><msub><mi>μ</mi><mrow><mtext>k</mtext></mrow></msub></mrow><mrow><mi>N</mi><mo stretchy="false">=</mo><mfenced close=")" open="("><mrow><mn>0</mn><mtext>.</mtext><mtext>30</mtext></mrow></mfenced></mrow><mrow><mfenced close=")" open="("><mrow><mtext>980</mtext><mspace width="0.25em"/><mtext>N</mtext></mrow></mfenced><mo stretchy="false">=</mo><mtext>290</mtext></mrow><mspace width="0.25em"/><mtext>N</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f rSub &#123; size 8&#123;k&#125; &#125; =μ rSub &#123; size 8&#123;k&#125; &#125; N= left (0 &quot;.&quot; &quot;30&quot; right ) left (&quot;980&quot;&quot; N&quot; right )=&quot;290&quot;&quot; N&quot;&#125; &#123;&#125;</annotation></semantics></math>)
     would keep it moving at a constant speed. If the floor is lubricated, both coefficients are considerably less than they would be without lubrication. Coefficient of friction is a unit less quantity with a magnitude usually between 0 and 1.0. The coefficient of the friction depends on the two surfaces that are in contact.
    
    Many people have experienced the slipperiness of walking on ice. However, many parts of the body, especially the joints, have much smaller coefficients of friction—often three or four times less than ice. A joint is formed by the ends of two bones, which are connected by thick tissues. The knee joint is formed by the lower leg bone (the tibia) and the thighbone (the femur). The hip is a ball (at the end of the femur) and socket (part of the pelvis) joint. The ends of the bones in the joint are covered by cartilage, which provides a smooth, almost glassy surface. The joints also produce a fluid (synovial fluid) that reduces friction and wear. A damaged or arthritic joint can be replaced by an artificial joint ({'Figure_6_1_2a Figure 6.1.2a}). These replacements can be made of metals (stainless steel or titanium) or plastic (polyethylene), also with very small coefficients of friction.
    
    
            
    
    Other natural lubricants include saliva produced in our mouths to aid in the swallowing process, and the slippery mucus found between organs in the body, allowing them to move freely past each other during heartbeats, during breathing, and when a person moves. Artificial lubricants are also common in hospitals and doctor’s clinics. For example, when ultrasonic imaging is carried out, the gel that couples the transducer to the skin also serves to to lubricate the surface between the transducer and the skin—thereby reducing the coefficient of friction between the two surfaces. This allows the transducer to move freely over the skin.
    
    We have discussed that when an object rests on a horizontal surface, there is a normal force supporting it equal in magnitude to its weight. Furthermore, simple friction is always proportional to the normal force.
    
    {'Figure_6_1_4a Figure 6.1.4a} illustrates one macroscopic characteristic of friction that is explained by microscopic (small-scale) research. We have noted that friction is proportional to the normal force, but not to the area in contact, a somewhat counterintuitive notion. When two rough surfaces are in contact, the actual contact area is a tiny fraction of the total area since only high spots touch. When a greater normal force is exerted, the actual contact area increases, and it is found that the friction is proportional to this area.
    
    
            
    
    But the atomic-scale view promises to explain far more than the simpler features of friction. The mechanism for how heat is generated is now being determined. In other words, why do surfaces get warmer when rubbed? Essentially, atoms are linked with one another to form lattices. When surfaces rub, the surface atoms adhere and cause atomic lattices to vibrate—essentially creating sound waves that penetrate the material. The sound waves diminish with distance and their energy is converted into heat. Chemical reactions that are related to frictional wear can also occur between atoms and molecules on the surfaces. {'Figure_6_1_5a Figure 6.1.5a} shows how the tip of a probe drawn across another material is deformed by atomic-scale friction. The force needed to drag the tip can be measured and is found to be related to shear stress, which will be discussed later in this chapter. The variation in shear stress is remarkable (more than a factor of <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>            <mrow>              <msup>                <mtext>10</mtext>                <mrow>                  <mtext>12</mtext>                </mrow>              </msup>            </mrow>            <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;&quot;10&quot; rSup &#123; size 8&#123;&quot;12&quot;&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>
        ) and difficult to predict theoretically, but shear stress is yielding a fundamental understanding of a large-scale phenomenon known since ancient times—friction.
    
    
            

  apply FullText

  ---
    5_1_0
    5_1_1

  / Friction - Full Text
  path FullText
    step
      --
        5_1_0
    step
      --
        5_1_1

    