/ Longevity & Ageing
subject Longevity
  head =

  / Aging & Theories of Aging
  model module AgingTheory
    head =

    -
      Concepts.LongevityConcepts.LifeSpan
    -
      Concepts.LongevityConcepts.Ageing
      Concepts.LongevityConcepts.Phenotypes
    >
      There are several molecular models of aging which includes damage by reactive oxygen species (ROS) generated by metabolism, genome instability, genetically programmed extension mechanisms, cell death, and systemic aging.

    > Oxidative Stress
      [One theory of aging proposes](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC349208/) that ROS which are generated by metabolism cause cumulative damage over a lifetime. ROS have been shown to cause molecular damage relatively indiscriminately to proteins, lipids, and nucleic acids.
    -
      Concepts.LongevityConcepts.ROC
      Concepts.LongevityConcepts.OxidativeStress
    > Telomere theory
      Biologic aging is also heavily attributed to the telomere theory. The telomere theory states that telomere shortening, which is accelerated by oxidative stress, is responsible for much of the age-related deterioration.
    # high level Claims on telemore from here - https://sci-hub.st/10.1533/9781908818652.75
    -
      Concepts.LongevityConcepts.Telomere

    > Damage accumulation theory of Aging
      [This theory](https://www.sciencedirect.com/science/article/pii/B9781907568428500058) of aging has multiple derivative versions, but essentially a common feature among them is that aging can be viewed as an accumulation of biological and biochemical waste.
    -
      Concepts.LongevityConcepts.DNADamage

  / Genomic Factors
  subject GenomicFactors
    head =
    >
      The importance of specific kinds of genome instability in aging is becoming increasingly apparent. The accumulation of genomic changes have long been proposed as causes of aging. While Ageing, Specific damage has been observed in the mitochondrial DNA.
    -
      Concepts.LongevityConcepts.GenomeInstability
    >
      Genetic links between aging and oxidative damage are found in animals in which most adult cells are postmitotic. Postmitotic cells may be more susceptible to the cumulative damage of ROS given their inability to replace themselves. In mammals, organs most vulnerable to this mechanism are the brain, heart, and skeletal muscle. However, the link between ROS and aging in organs consisting of dividing cells is less clear.
    -
      Concepts.LongevityConcepts.Postmitotic
      Concepts.LongevityConcepts.Mitosis
    >
      Genome analysis may also identify human polymorphisms that are associated with longevity.
    -
      Concepts.LongevityConcepts.GenePolymorphism

    >
      The term gerontogenes is used to describe genes that are involved in aging and usually involves genes whose normal function shortens rather than lengthens life.
    -
      Concepts.LongevityConcepts.Gerontogens

    >
      The influence of genes on the life span of organisms can be explained at several biological levels including:
      1. A phylogenetic level where genes generate growth and form and thus determine the basic body plan, metabolic framework, and the broad details of a species’ life history.
      2. A mechanistic level where genes regulate the basic mechanisms affecting the rate of aging and life span.
      3. A disease vulnerability where genes determine the susceptibility of individuals to specific diseases.
    # claim - Phylogenetic Approach (mice flies &.)
    - Phylogenetic Approach (Mice)
      'Carey_et_al_11_02_2002
      'Carey_et_al_11_02_2002.!b
    - Drosophila (Fruit flies)
      'Carey_et_al_11_02_2002
      'Carey_et_al_11_02_2002.!c
    - Nematodes (Roundworms)
      'Carey_et_al_11_02_2002
      'Carey_et_al_11_02_2002.!d
    # claim - Mutants (Yeast ..)
    - Mutants (Yeast)
      'Carey_et_al_11_02_2002
      'Carey_et_al_11_02_2002.!e
    - Nematodes
      'Carey_et_al_11_02_2002
      'Carey_et_al_11_02_2002.!f
    - Drosophila
      'Carey_et_al_11_02_2002
      'Carey_et_al_11_02_2002.!g
    # claim - GeneExpression = Experimental manipulations of life span in both flies and rodents have been shown to cause changes in gene activity
    - Gene Expression
      'Carey_et_al_11_02_2002
      'Carey_et_al_11_02_2002.!h

    # {Context.LongevityConcepts.Gerontogens}
    > Gerontogenes
      The term  Gerontogenes is used to describe genes that are involved in aging and usually involves genes whose normal function shortens rather than lengthens life. One of the approaches that researchers use in an attempt to identify genes that influence aging in humans is to study the prevalence of different genes in centenarians relative to younger people (e.g., 20–60 years).
      One of the most studied genetic polymorphisms involved in human longevity is the apolopoprotein E (APO-E) gene which encodes a protein that is synthe- sized in the liver, brain, spleen, kidneys, and macro- phages and in human populations exists as three common alleles—E2, E3, and E4.
    # claim = Frequencies of these three alleles in centenarians and in noncentenarians revealed that
    - APO-E gene
      'Carey_et_al_11_02_2002
      'Carey_et_al_11_02_2002.!i
    - Results from genetic testing in a hypothetical patient in 2010
      'Carey_et_al_11_02_2002
      'Carey_et_al_11_02_2002.!j

    - Telomere shortening
      'Montano_et_al_01_09_2015
      'Montano_et_al_01_09_2015.!e

    # DAVID SINCLAIR - People born in winter tend to be evening people, especially if they carry a certain version of the SIRT1 longevity-clock gene.
    # Claim = A potential candidate gene for postnatal seasonal programming was SIRT1, which has previously been implicated in postnatal programming, ageing and longevity. Genetic diversity may explain the heterogeneity in ageing-related change of sleep timing and postnatal environmental programming of later-life chronotype. - https://twitter.com/davidasinclair/status/1442920790941261827 (REDO THIS CLAIM)
    - Season of birth, chronological age and genetic polymorphisms in determining later-life chronotype
      'Didikoglu_et_al_05_01_2020
      'Didikoglu_et_al_05_01_2020.!a
      'Didikoglu_et_al_05_01_2020.!b
      'Didikoglu_et_al_05_01_2020.!c
      'Didikoglu_et_al_05_01_2020.!d


  / Cell Death & Functional Decline of organs
  subject CellDeath
    head =
    >
      Cells die via mechanisms that range from necrosis, which is a relatively passive outcome of cell injury, to apoptosis, or programmed cell death, which is an active and ordered process. Apoptosis is triggered by a myriad of stimuli, such as steroid hormones, DNA damage, withdrawal of growth factors, or receptor-mediated apoptosis as in clonal deletion of immune cells. It has been proposed that an inability of certain cells to undergo apoptosis might contribute to aging and diseases of aging.
    -
      Concepts.LongevityConcepts.Necrosis
      Concepts.LongevityConcepts.Apoptosis
    >
      Both apoptotic and necrotic forms of cell death can be mediated by mitochondria.
    -
      Concepts.LongevityConcepts.Mitochondria
    >
      Many of the above mechanisms of aging are cell autonomous.  Systemic control of aging may also occur. Humoral factors (i.e., endocrine hormones) would coordinate the pace of aging in many different tissues and organs. Local mechanisms like cell–cell contact or paracrine hormones could coordinate aging in a proximate compartment of cells. Systemic and cell-autonomous processes are clearly not mutually exclusive; cell-autonomous and systemic aging may coexist or trigger each other.
    -
      Concepts.LongevityConcepts.ParacrineSignaling

    >
      A familiar feature of aging is the functional decline in organ and tissue systems. Functional decline is evident in any of an array of organs (gut, kidney, liver, brain) and tissues (skin, immune system, skeletal muscle). The cellular basis for functional decline with aging is unclear, but may in part be related to age- associated changes in the role of adult stem cells in mediating cellular turnover, particularly in relation to tissue homeostasis and/or tissue repair
    -
      Concepts.LongevityConcepts.StemCell

    # claim - Stem cells
    - Cellular shift from proliferation to hypertrophy
      'Montano_et_al_01_09_2015
      'Montano_et_al_01_09_2015.!f
    - Increased latency period
      'Montano_et_al_01_09_2015
      'Montano_et_al_01_09_2015.!g
    -  Reduced rate of stem cell proliferation
      'Montano_et_al_01_09_2015
      'Montano_et_al_01_09_2015.!h
    - Greater proportion of connective tissue, matrix, fibrosis
      'Montano_et_al_01_09_2015
      'Montano_et_al_01_09_2015.!i
      'Montano_et_al_01_09_2015.!j
      'Montano_et_al_01_09_2015.!k
    ## stem cells ends##

    # Concept satellite cells
    - Aging and muscle tissue regeneration
      'Montano_et_al_01_09_2015
      'Montano_et_al_01_09_2015.!l
    ###  Immunosenescence - claims for all these points in future - 5.7.1 till 4
    -  Immune aging and immunosenescence
      'Montano_et_al_01_09_2015
      'Montano_et_al_01_09_2015.!m
    ## Insulin
    - The insulin/IGF1 signaling axis in aging
      'Montano_et_al_01_09_2015
      'Montano_et_al_01_09_2015.!n
    - IGF1 and lifespan (Rodents)
      'Montano_et_al_01_09_2015
      'Montano_et_al_01_09_2015.!o

  / Aging Control
  subject AgingControl
    # https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5824489/
    # https://www.sciencedirect.com/topics/neuroscience/sirtuin
    >
      Sirtuins (proteins molecule found in Red Wine) contribute to redox homeostasis maintenance by balancing antioxidant enzymes and pro-oxidant radicals. Sirtuins' activity is linked to metabolic control, apoptosis, cell survival, development, inflammation, and healthy aging.
    -
      Concepts.LongevityConcepts.FreeRadical
      Concepts.LongevityConcepts.Sirtuin
    >
      Resveratrol—a natural compound found in the skin of grapes used to make red wine.
    -
      Concepts.LongevityConcepts.Resveratrol

    ### Branched- chain amino acids (BCAA) and aging
    -  BCAA (Branched- chain amino acids)
      'Montano_et_al_01_09_2015
      'Montano_et_al_01_09_2015.!q
    - Rapamycin
      'Montano_et_al_01_09_2015
      # 'Montano_et_al_01_09_2015.!r (Add quote)
    ### BCAA ends
    # Resveratrol
    - Cardiovascular Disease, Obesity, Diabetes, Alzheimer Disease, and Cancer
      'Kulashekar_et_al_09_01_2018
      'Kulashekar_et_al_09_01_2018.!a
      'Resveratrol
    - Liver
      'Theodotou_et_al_10_28_2018
      'Theodotou_et_al_10_28_2018.!a
      'Theodotou_et_al_10_28_2018.!b
    - Kidney
      'Hartogh_et_al_07_17_2019
      'Hartogh_et_al_07_17_2019.!a
      'Hartogh_et_al_07_17_2019.!b
      'Hartogh_et_al_07_17_2019.!c
      'Hartogh_et_al_07_17_2019.!d
      'Hartogh_et_al_07_17_2019.!e
    # claim = In one meta analysis. Resveratrol supplementation significantly increased FMD (flow-mediated dilatation) among patients with MetS and related disorders, but did not affect SBP (systolic blood pressure) and DBP (diastolic blood pressure).
    - Blood pressure and vessel dilation
      'Akbari_et_al_07_01_2019
      'Akbari_et_al_07_01_2019.!a
    # claim = Meta analysis of 16 controlled studies revealed that administration of resveratrol can meaningfully reduce the Body Weight, Waist Circumference, triglycerides, and glucose level, also it can increase HDL, but not total cholesterol.
    - Blood glucose, HDL and triglycerides
      'Asgary_et_al_06_2019
      'Asgary_et_al_06_2019.!a
      'Asgary_et_al_06_2019.!b
      'Asgary_et_al_06_2019.!c
    # Make 2 claims (Mice and Humans)
    - Mice
      'Baur_et_al_11_01_2006
      'Baur_et_al_11_01_2006.!a
      'Baur_et_al_11_01_2006.!b
    # Caution and Anti -Thydroid effects - claim - One study concluded that resveratrol acts as a thyroid disruptor and a goitrogen, which indicates the need for caution as a supplement and for therapeutic uses.
    - Thyroid
      'Giuliani_et_al_06_28_2017
      'Giuliani_et_al_06_28_2017.!a
      'Giuliani_et_al_06_28_2017.!b

  / External Factors effecting Longevity & Ageing
  subject ExternalFactors
    >
      Factos effecting longevity
    - Environment
      'Samaras_et_al_08_26_2008
      'Samaras_et_al_08_26_2008.!a
    - BMI
      'Samaras_et_al_08_26_2008
      'Samaras_et_al_08_26_2008.!b
    - Other Factors
      'Samaras_et_al_08_26_2008
      'Samaras_et_al_08_26_2008.!c
    - Climate
      'Samaras_et_al_08_26_2008
      'Samaras_et_al_08_26_2008.!d
    - Countries with low/high living population
      'Samaras_et_al_08_26_2008
      'Samaras_et_al_08_26_2008.!e
    - Gender
      'Samaras_et_al_08_26_2008
      'Samaras_et_al_08_26_2008.!f
    - Centenarians (those who live 100 years or longer)
      'Samaras_et_al_08_26_2008
      'Samaras_et_al_08_26_2008.!g
    - Okinawa Centenarians (Factors)
      'Samaras_et_al_08_26_2008
      'Samaras_et_al_08_26_2008.!h
    - Height and Weight
      'Samaras_et_al_08_26_2008
      'Samaras_et_al_08_26_2008.!i

    ## Calorie Restriction
    - Calorie Restriction
      'Montano_et_al_01_09_2015
      'Montano_et_al_01_09_2015.!p

  / Disease Prevention
  subject Diseases
    head =
    -
      CardiovascularDisease
    -
      AlzheimerDisease
    -
      !Covid
    -
      !CancerDNAMutation

    # we make the case for the use of TRE as a novel, safe, and feasible intervention for primary and secondary BC prevention, as well as tertiary prevention as it relates to CVD in BC survivors.
    - Breast Cancer and Cardiovascular Disease
      'Christensen_et_al_09_30_2021
      'Christensen_et_al_09_30_2021.!a

    / Cancer
    claim !CancerDNAMutation =  DNA mutations cause cancer but do not appear to cause aging in humans
      -
        'Robinson_et_al_09_30_2021
        'Robinson_et_al_09_30_2021.!a
        'Robinson_et_al_09_30_2021.!b


    / Covid-19
    claim !Covid = One study of 3947 patients shows those who are physically active & eat more fruit, vegetables & fish are relatively protected. Authors concluded that Healthy eating behavior and physical activity showed single and combinative impacts on protecting people from COVID-19-like Symptoms.
      - Covid
        'Nguyen_et_al_09_18_2021
        'Nguyen_et_al_09_18_2021.!a



    / Cardiovascular disease in aging
    subject CardiovascularDisease
      head =

      - Oxidative stress
        'Orliaguet_et_al_05_29_2020
        'Orliaguet_et_al_05_29_2020.!d
      - Telomere theory
        'Orliaguet_et_al_05_29_2020
        'Orliaguet_et_al_05_29_2020.!e
      - Mitochondria
        'Orliaguet_et_al_05_29_2020
        'Orliaguet_et_al_05_29_2020.!f
        'Orliaguet_et_al_05_29_2020.!g
      - Key Genes
        'Orliaguet_et_al_05_29_2020
        'Orliaguet_et_al_05_29_2020.!h
      - Oxidative Balance
        'Orliaguet_et_al_05_29_2020
        'Orliaguet_et_al_05_29_2020.!i
      - Calorie & Fasting
        'Orliaguet_et_al_05_29_2020
        'Orliaguet_et_al_05_29_2020.!j

      / Cardiovascular Complications
      claim !CardiovascularSauna = In one study during a median follow-up of 20.7 years, 190 SCDs (sudden cardiac deaths), 281 fatal CHDs(coronary heart diseases), 407 fatal CVDs(cardiovascular diseases), and 929 all-cause mortality events occurred. Authors concluded that Increased frequency of sauna bathing is associated with a reduced risk of SCD, CHD, CVD, and all-cause mortality.
        -
          'Laukkaneen_et_al_02_23_2015
          'Laukkaneen_et_al_02_23_2015.!a
          'Laukkaneen_et_al_02_23_2015.!b

      claim !PlantBasedDiet = Analysis of 84 studies suggests Plant-predominant diets can play a major role in reversing the obesity and chronic disease epidemics. In the setting of sustained lifestyle intervention programs, they may arrest or even reverse type 2 diabetes and cardiovascular disease.
        -
          'Remde_et_al_09_09_2021
          'Remde_et_al_09_09_2021.!a

    / Alzheimer Disease and Dementia
    subject AlzheimerDisease
      head =

      / Alzheimer
      claim !AlzheimerSauna = In one study, during a median follow-up of 20.7 years, a total of 204 and 123 diagnosed cases of dementia and Alzheimer's disease were respectively recorded. Authors concluded that In this male population, moderate to high frequency of sauna bathing was associated with lowered risks of dementia and Alzheimer's disease.
        -
          'Laukkanen_et_al_12_08_2016
          'Laukkanen_et_al_12_08_2016.!a

      / Meat Consumption & Dementia
      claim !MeatConsumption = In one study, among 493,888 participants included, 2896 incident cases of all-cause dementia, 1006 cases of AD(Alzheimer disease), and 490 cases of VD(vascular dementia) were identified. Intake of processed meat was associated with increased risks of incident all-cause dementia and AD while increment in unprocessed red meat intake was associated with reduced risks, independent of the APOE ε4 allele. Regarding VD no significant trends were identified, however for processed meat, higher consumption categories were associated with increased risks.
        -
          'Zhang_et_al_03_22_2021
          'Zhang_et_al_03_22_2021.!a
          'Zhang_et_al_03_22_2021.!b
          'Zhang_et_al_03_22_2021.!c
          'Zhang_et_al_03_22_2021.!d

  / Lifestyle & Diet
  subject LifestyleDiet
    head =
    -
      !BloodDonation
    -
      !PlantBasedDiet
    -
      Omega3Fatty
      Sauna
    -
      !MeatConsumption
    -
      !TREBCCVD  




    # Donating blood seems to slow aspects of aging.
    claim !BloodDonation = In, one study 2,862 men aged 42–60 years were followed for an average of almost 9 years to study the hypothesis that voluntary blood donation is associated with reduced risk of acute myocardial infarction. Findings suggest that frequent blood loss through voluntary blood donations may be associated with a reduced risk of acute myocardial infarction in middle-aged men.
      -
        'Salonen_et_al_11_01_1998
        'Salonen_et_al_11_01_1998.!a
        'Salonen_et_al_11_01_1998.!b

    claim !PlantBasedDiet = Analysis of 84 studies suggests Plant-predominant diets can play a major role in reversing the obesity and chronic disease epidemics. In the setting of sustained lifestyle intervention programs, they may arrest or even reverse type 2 diabetes and cardiovascular disease.
      -
        'Remde_et_al_09_09_2021
        'Remde_et_al_09_09_2021.!a

    subject Sauna
      # Sauna 5 claims (Subject, Make more claims from Rhonda Patrick)
      - Sauna
        'Patrick_et_al_08_05_2021
        'Patrick_et_al_08_05_2021.!a
      -
        'Patrick_et_al_08_05_2021
        'Patrick_et_al_08_05_2021.!b
      -
        'Patrick_et_al_08_05_2021
        'Patrick_et_al_08_05_2021.!c
      -
        'Patrick_et_al_08_05_2021
        'Patrick_et_al_08_05_2021.!d
      -
        'Patrick_et_al_08_05_2021
        'Patrick_et_al_08_05_2021.!e
      -
        !AlzheimerSauna
      -
        !CardiovascularSauna


      / Alzheimer
      claim !AlzheimerSauna = In one study, during a median follow-up of 20.7 years, a total of 204 and 123 diagnosed cases of dementia and Alzheimer's disease were respectively recorded. Authors concluded that In this male population, moderate to high frequency of sauna bathing was associated with lowered risks of dementia and Alzheimer's disease.
        -
          'Laukkanen_et_al_12_08_2016
          'Laukkanen_et_al_12_08_2016.!a

      / Cardiovascular Complications
      claim !CardiovascularSauna = In one study during a median follow-up of 20.7 years, 190 SCDs (sudden cardiac deaths), 281 fatal CHDs(coronary heart diseases), 407 fatal CVDs(cardiovascular diseases), and 929 all-cause mortality events occurred. Authors concluded that Increased frequency of sauna bathing is associated with a reduced risk of SCD, CHD, CVD, and all-cause mortality.
        -
          'Laukkaneen_et_al_02_23_2015
          'Laukkaneen_et_al_02_23_2015.!a
          'Laukkaneen_et_al_02_23_2015.!b

    / Meat Consumption & Dementia
    claim !MeatConsumption = In one study, among 493,888 participants included, 2896 incident cases of all-cause dementia, 1006 cases of AD(Alzheimer disease), and 490 cases of VD(vascular dementia) were identified. Intake of processed meat was associated with increased risks of incident all-cause dementia and AD while increment in unprocessed red meat intake was associated with reduced risks, independent of the APOE ε4 allele. Regarding VD no significant trends were identified, however for processed meat, higher consumption categories were associated with increased risks.
      -
        'Zhang_et_al_03_22_2021
        'Zhang_et_al_03_22_2021.!a
        'Zhang_et_al_03_22_2021.!b
        'Zhang_et_al_03_22_2021.!c
        'Zhang_et_al_03_22_2021.!d

    / Omega 3 Fatty Acids
    subject Omega3Fatty
      head =
      / Polyunsaturated fatty acid
      claim !PUFA = One study enrolled 200 apparently healthy Japanese living in an urban area. Levels of polyunsaturated fatty acid (PUFA) in serum and red blood cells (RBCs) were assessed. Low levels of EPA/AA (Eicosapentaenoic acid/Arachidonic acid), which were associated with insulin resistance, were demonstrated in young Japanese adults living in an urban area.
        -
          'Yanagisawa_et_al_03_31_2010
          'Yanagisawa_et_al_03_31_2010.!a

      # Make 5 or 6 claims
      - Omega 3
        'Singh_et_al_06_27_2014
        'Singh_et_al_06_27_2014.!a
        'Singh_et_al_06_27_2014.!b
        'Singh_et_al_06_27_2014.!c
        'Singh_et_al_06_27_2014.!d
        'Singh_et_al_06_27_2014.!e
        'Singh_et_al_06_27_2014.!f

      # Make 1 claims - Citing study and arcticle - study https://academic.oup.com/ajcn/advance-article/doi/10.1093/ajcn/nqab195/6301120
      -
        'McBurney_et_al_07_22_2021
        'McBurney_et_al_07_22_2021.!a
        'McBurney_et_al_07_22_2021.!b

    / Time Restricted Eating - Breast Cancer and Cardiovascular Disease
    claim !TREBCCVD = One study make the case for the use of time-restricted eating as a novel, safe, and feasible intervention for primary and secondary Breast Cancer prevention, as well as tertiary prevention as it relates to Cardiovascular Disease in Breast Cancer survivors.
      -
        'Christensen_et_al_09_30_2021
        'Christensen_et_al_09_30_2021.!a
