
/ Electric Potential Energy: Potential Difference
story 19_1
  >
    When a free positive charge  *q size 12&#123;q&#125; &#123;&#125;* is accelerated by an electric field, such as shown in {'Figure_20_1_1a Figure 20.1.1a}, it is given kinetic energy. The process is analogous to an object being accelerated by a gravitational field. It is as if the charge is going down an electrical hill where its electric potential energy is converted to kinetic energy. Let us explore the work done on a charge  *q size 12&#123;q&#125; &#123;&#125;* by the electric field in this process, so that we may develop a definition of electric potential energy.
    
    
            
    
    The electrostatic or Coulomb force is conservative, which means that the work done on  *q size 12&#123;q&#125; &#123;&#125;* is independent of the path taken. This is exactly analogous to the gravitational force in the absence of dissipative forces such as friction. When a force is conservative, it is possible to define a potential energy associated with the force, and it is usually easier to deal with the potential energy (because it depends only on position) than to calculate the work directly.
    
    We use the letters PE to denote electric potential energy, which has units of joules (J). The change in potential energy, <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>Δ</mtext><mtext>PE</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;?&quot;PE&quot;&#125; &#123;&#125;</annotation></semantics></math>, is crucial, since the work done by a conservative force is the negative of the change in potential energy; that is, <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>W  </mi><mo>=</mo><mtext>–Δ</mtext><mtext>PE</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;W&quot;=-&quot;?&quot;PE&quot;&#125; &#123;&#125;</annotation></semantics></math>. For example, work <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"> <semantics>  <mi>W</mi> </semantics></math> done to accelerate a positive charge from rest is positive and results from a loss in PE, or a negative <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>Δ</mtext><mtext>PE</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;?&quot;PE&quot;&#125; &#123;&#125;</annotation></semantics></math>. There must be a minus sign in front of <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>Δ</mtext><mtext>PE</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;?&quot;PE&quot;&#125; &#123;&#125;</annotation></semantics></math> to make <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"> <semantics>  <mi>W</mi> </semantics></math> positive. PE can be found at any point by taking one point as a reference and calculating the work needed to move a charge to the other point.
    
    Gravitational potential energy and electric potential energy are quite analogous. Potential energy accounts for work done by a conservative force and gives added insight regarding energy and energy transformation without the necessity of dealing with the force directly. It is much more common, for example, to use the concept of voltage (related to electric potential energy) than to deal with the Coulomb force directly. 
    
    Calculating the work directly is generally difficult, since <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mi>W</mi><mo stretchy="false"> = </mo><mstyle fontstyle="italic"><mrow><mtext>Fd</mtext></mrow></mstyle></mrow><mspace width="0.25em"/><mtext>cos</mtext><mspace width="0.25em"/><mi>θ</mi></mrow></mrow><mrow/></mrow></semantics></math> and the direction and magnitude of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>F </mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;F&#125; &#123;&#125;</annotation></semantics></math> can be complex for multiple charges, for odd-shaped objects, and along arbitrary paths. But we do know that, since <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>F </mi><mo stretchy="false">=</mo><mstyle fontstyle="italic"><mrow><mtext>qE</mtext></mrow></mstyle></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;F= ital &quot;qE&quot;&#125; &#123;&#125;</annotation></semantics></math>, the work, and hence <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>ΔPE</mtext></mrow></mrow><mrow/></mrow></semantics></math>, is proportional to the test charge <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi fontstyle="italic">q.</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;q&#125; &#123;&#125;</annotation></semantics></math> To have a physical quantity that is independent of test charge, we define  **electric potential**<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>V</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V&#125; &#123;&#125;</annotation></semantics></math> (or simply potential, since electric is understood) to be the potential energy per unit charge: 
    
    <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <mi>V</mi>                    <mo stretchy="false"> = </mo>                    <mfrac>                      <mtext>PE</mtext>                      <mi>q</mi>                    </mfrac>                  </mrow>                  <mtext>.</mtext>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;V= &#123;  &#123;&quot;PE&quot;&#125;  over  &#123;q&#125; &#125;  &quot;.&quot; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    Since PE is proportional to  *q size 12&#123;q&#125; &#123;&#125;* , the dependence on  *q size 12&#123;q&#125; &#123;&#125;* cancels. Thus <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>V</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V&#125; &#123;&#125;</annotation></semantics></math> does not depend on  *q size 12&#123;q&#125; &#123;&#125;*. The change in potential energy <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>ΔPE</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;?&quot;PE&quot;&#125; &#123;&#125;</annotation></semantics></math> is crucial, and so we are concerned with the difference in potential or potential difference <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mn>Δ</mn><mi fontstyle="italic">V</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;?V&#125; &#123;&#125;</annotation></semantics></math> between two points, where
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>            <mrow>              <mrow>                <mrow>                  <mrow>                    <mn>Δ</mn><mi fontstyle="italic">V</mi>                    <mo stretchy="false">=</mo>                    <mrow>                      <msub>                        <mi>V</mi>                        <mrow>                          <mtext>B</mtext>                        </mrow>                      </msub>                      <mo stretchy="false">−</mo>                      <msub>                        <mi>V</mi>                        <mrow>                          <mtext>A</mtext>                        </mrow>                      </msub>                    </mrow>                  </mrow>                  <mo stretchy="false">=</mo>                  <mfrac>                    <mrow>                      <mn>Δ</mn>                      <mtext>PE</mtext>                    </mrow>                    <mi>q</mi>                  </mfrac>                </mrow>                <mtext>.</mtext>              </mrow>            </mrow>            <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;ΔV=V rSub &#123; size 8&#123;B&#125; &#125;  - V rSub &#123; size 8&#123;A&#125; &#125; = &#123;  &#123;Δ&quot;PE&quot;&#125;  over  &#123;q&#125; &#125;  &quot;.&quot; &#125; &#123;&#125;</annotation>        </semantics>      </math>    
    
    The  **potential difference** between points A and B, <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mi>V</mi><mrow><mtext>B</mtext></mrow></msub><mspace width="0.25em"/><mo stretchy="false">–</mo><mspace width="0.25em"/><msub><mi>V</mi><mrow><mtext>A</mtext></mrow></msub></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V rSub &#123; size 8&#123;B&#125; &#125; -V rSub &#123; size 8&#123;A&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>, is thus defined to be the change in potential energy of a charge  *q  size 12&#123;q&#125; &#123;&#125;* moved from A to B, divided by the charge. Units of potential difference are joules per coulomb, given the name volt (V) after Alessandro Volta.
    
    <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">    <semantics>     <mrow>       <mrow>        <mrow>         <mtext>1 V = 1         </mtext><mspace width="0.25em"/>         <mrow>          <mfrac>           <mrow>            <mn>J            </mn>           </mrow>           <mrow>            <mn>C            </mn>           </mrow>          </mfrac>         </mrow>        </mrow>       </mrow>     </mrow>     <annotation encoding="StarMath 5.0">size 12&#123;1&quot; V=1 &quot; &#123;  &#123;J&#125;  over  &#123;C&#125; &#125; &#125; &#123;&#125;     </annotation>    </semantics>   </math>
    
    The familiar term  **voltage** is the common name for potential difference. Keep in mind that whenever a voltage is quoted, it is understood to be the potential difference between two points. For example, every battery has two terminals, and its voltage is the potential difference between them. More fundamentally, the point you choose to be zero volts is arbitrary. This is analogous to the fact that gravitational potential energy has an arbitrary zero, such as sea level or perhaps a lecture hall floor.
    
    In summary, the relationship between potential difference (or voltage) and electrical potential energy is given by
    
    <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow><mn>Δ</mn>                    <mi fontstyle="italic">V </mi>                    <mo stretchy="false">=</mo>                    <mfrac>                      <mrow>                        <mtext>ΔPE</mtext>                      </mrow>                      <mi>q</mi>                    </mfrac>                  </mrow><mspace width="0.25em"/>                  <mtext>and ΔPE =</mtext><mspace width="0.25em"/>                  <mi fontstyle="italic">q</mi><mn>Δ</mn><mi fontstyle="italic">V</mi>                  <mtext>.</mtext>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;?V= &#123;  &#123;?&quot;PE&quot;&#125;  over  &#123;q&#125; &#125; &quot;  and  &quot;D&quot;PE=&quot;q?V &quot;.&quot; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    Voltage is not the same as energy. Voltage is the energy per unit charge. Thus a motorcycle battery and a car battery can both have the same voltage (more precisely, the same potential difference between battery terminals), yet one stores much more energy than the other since <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>ΔPE =</mtext><mspace width="0.25em"/><mi fontstyle="italic">q</mi><mn>Δ</mn><mi fontstyle="italic">V</mi></mrow></mrow><mrow/></mrow></semantics></math>. The car battery can move more charge than the motorcycle battery, although both are 12 V batteries.
    
    Note that the energies calculated in the previous example are absolute values. The change in potential energy for the battery is negative, since it loses energy. These batteries, like many electrical systems, actually move negative charge—electrons in particular. The batteries repel electrons from their negative terminals (A) through whatever circuitry is involved and attract them to their positive terminals (B) as shown in {'Figure_20_1_2a Figure 20.1.2a}. The change in potential is <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mn>Δ</mn><mi fontstyle="italic">V</mi><mo stretchy="false">=</mo><mrow><msub><mi>V</mi><mrow><mtext>B</mtext></mrow></msub><msub><mi fontstyle="italic">–V</mi><mrow><mtext>A</mtext></mrow></msub></mrow></mrow><mo>=</mo><mtext>+12 V</mtext></mrow></mrow><mrow/></mrow></semantics></math> and the charge <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>q</mi></mrow><mrow/></mrow></semantics></math> is negative, so that <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>ΔPE</mtext><mo>=</mo><mi fontstyle="italic">q</mi><mn>Δ</mn><mi fontstyle="italic">V</mi></mrow></mrow><mrow/></mrow></semantics></math> is negative, meaning the potential energy of the battery has decreased when  *q* has moved from A to B.
    
    
            

  apply FullText

  ---
    19_1_0
    19_1_1
    19_1_2
    19_1_3

  / Electric Potential Energy: Potential Difference - Full Text
  path FullText
    step
      --
        19_1_0
    step
      --
        19_1_1
    step
      --
        19_1_2
    step
      --
        19_1_3

    