
/ Writing and Balancing Chemical Equations
story 7_1
  >
    An earlier chapter of this text introduced the use of element symbols to represent individual atoms. When atoms gain or lose electrons to yield ions, or combine with other atoms to form molecules, their symbols are modified or combined to generate chemical formulas that appropriately represent these species. Extending this symbolism to represent both the identities and the relative quantities of substances undergoing a chemical (or physical) change involves writing and balancing a  **chemical equation**. Consider as an example the reaction between one methane molecule (CH<sub>4</sub>) and two diatomic oxygen molecules (O<sub>2</sub>) to produce one carbon dioxide molecule (CO<sub>2</sub>) and two water molecules (H<sub>2</sub>O). The chemical equation representing this process is provided in the upper half of {'Figure_4_1_rxn2 Figure 4.1.rxn2}, with space-filling molecular models shown in the lower half of the figure.
    
    
            
    
    This example illustrates the fundamental aspects of any chemical equation:
    
      1. The substances undergoing reaction are called  **reactants**, and their formulas are placed on the left side of the equation.
      2. The substances generated by the reaction are called  **products**, and their formulas are placed on the right side of the equation.
      3. Plus signs (+) separate individual reactant and product formulas, and an arrow <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>(⟶)</mtext></mrow></math> separates the reactant and product (left and right) sides of the equation.
      4. The relative numbers of reactant and product species are represented by  **coefficients** (numbers placed immediately to the left of each formula). A coefficient of 1 is typically omitted.
    
    It is common practice to use the smallest possible whole-number coefficients in a chemical equation, as is done in this example. Realize, however, that these coefficients represent the  *relative* numbers of reactants and products, and, therefore, they may be correctly interpreted as ratios. Methane and oxygen react to yield carbon dioxide and water in a 1:2:1:2 ratio. This ratio is satisfied if the numbers of these molecules are, respectively, 1-2-1-2, or 2-4-2-4, or 3-6-3-6, and so on ({'Figure_4_1_rxn3 Figure 4.1.rxn3}). Likewise, these coefficients may be interpreted with regard to any amount (number) unit, and so this equation may be correctly read in many ways, including:
    
      *  *One* methane molecule and  *two* oxygen molecules react to yield  *one* carbon dioxide molecule and  *two* water molecules.
      *  *One dozen* methane molecules and  *two dozen* oxygen molecules react to yield  *one dozen* carbon dioxide molecules and  *two dozen* water molecules.
      *  *One mole* of methane molecules and  *2 moles* of oxygen molecules react to yield  *1 mole* of carbon dioxide molecules and  *2 moles* of water molecules.
    
    
            

  apply FullText

  ---
    7_1_0
    7_1_1
    7_1_2
    7_1_3
    7_1_4

  / Writing and Balancing Chemical Equations - Full Text
  path FullText
    step
      --
        7_1_0
    step
      --
        7_1_1
    step
      --
        7_1_2
    step
      --
        7_1_3
    step
      --
        7_1_4

    