
/ Waves
story 16_9
  >
    
            
    
    What do we mean when we say something is a wave? The most intuitive and easiest wave to imagine is the familiar water wave. More precisely, a  **wave** is a disturbance that propagates, or moves from the place it was created. For water waves, the disturbance is in the surface of the water, perhaps created by a rock thrown into a pond or by a swimmer splashing the surface repeatedly. For sound waves, the disturbance is a change in air pressure, perhaps created by the oscillating cone inside a speaker. For earthquakes, there are several types of disturbances, including disturbance of Earth’s surface and pressure disturbances under the surface. Even radio waves are most easily understood using an analogy with water waves. Visualizing water waves is useful because there is more to it than just a mental image. Water waves exhibit characteristics common to all waves, such as amplitude, period, frequency and energy. All wave characteristics can be described by a small set of underlying principles.
    
    A wave is a disturbance that propagates, or moves from the place it was created. The simplest waves repeat themselves for several cycles and are associated with simple harmonic motion. Let us start by considering the simplified water wave in {'Figure_17_9_2a Figure 17.9.2a} *.* The wave is an up and down disturbance of the water surface. It causes a sea gull to move up and down in simple harmonic motion as the wave crests and troughs (peaks and valleys) pass under the bird. The time for one complete up and down motion is the wave’s period <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>T</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;T&#125; &#123;&#125;</annotation></semantics></math>. The wave’s frequency is <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>f</mi><mo stretchy="false">=</mo><mrow><mn>1</mn><mo stretchy="false">/</mo><mi>T</mi></mrow></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f=1/&quot;T&quot;&#125; &#123;&#125;</annotation></semantics></math>, as usual. The wave itself moves to the right in the figure. This movement of the wave is actually the disturbance moving to the right, not the water itself (or the bird would move to the right). We define  **wave velocity**<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>v</mi><mrow><mtext>w</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v rSub &#123; size 8&#123;&quot;w&quot;&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> to be the speed at which the disturbance moves. Wave velocity is sometimes also called the  *propagation velocity or propagation speed* *,* because the disturbance propagates from one location to another.
    
    
            
    
    The water wave in the figure also has a length associated with it, called its  **wavelength**<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"> <semantics>  <mrow>   <mrow>    <mi>λ</mi>   </mrow>  </mrow> </semantics></math>, the distance between adjacent identical parts of a wave. (<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>λ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;λ&#125; &#123;&#125;</annotation></semantics></math> is the distance parallel to the direction of propagation.) The speed of propagation <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>v</mi><mrow><mtext>w</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v rSub &#123; size 8&#123;w&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the distance the wave travels in a given time, which is one wavelength in the time of one period. In equation form, that is
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow><msub>                  <mi>v</mi>                                                            <mrow>                        <mtext>w</mtext>                      </mrow></msub>                                        <mo stretchy="false">=</mo>                    <mfrac>                      <mi>λ</mi>                      <mi>T</mi>                    </mfrac>                                  </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;v size 8&#123;w&#125;= &#123;  &#123;λ&#125;  over  &#123;T&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    or
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow><msub>                  <mi>v</mi>                                                            <mrow>                        <mtext>w</mtext>                      </mrow></msub>                                        <mo stretchy="false">=</mo>                    <mi fontstyle="italic">fλ</mi>                                  </mrow>              </mrow>                        <mrow/><mo>.</mo>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;v size 8&#123;w&#125;=fλ&#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    This fundamental relationship holds for all types of waves. For water waves, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>v</mi><mrow><mtext>w</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v rSub &#123; size 8&#123;w&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the speed of a surface wave; for sound, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>v</mi><mrow><mtext>w</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v rSub &#123; size 8&#123;w&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the speed of sound; and for visible light, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>v</mi><mrow><mtext>w</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v rSub &#123; size 8&#123;w&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the speed of light, for example.

  apply FullText

  ---
    16_9_0
    16_9_1
    16_9_2

  / Waves - Full Text
  path FullText
    step
      --
        16_9_0
    step
      --
        16_9_1
    step
      --
        16_9_2

    