
/ Organizing Life on Earth
story 4_12_1
  >
    All life on Earth evolved from a common ancestor. Biologists map how organisms are related by constructing phylogenetic trees. In other words, a “tree of life” can be constructed to illustrate when different organisms evolved and to show the relationships among different organisms, as shown in {'Figure_12_1_1 Figure 12.1.1}. Notice that from a single point, the three domains of Archaea, Bacteria, and Eukarya diverge and then branch repeatedly. The small branch that plants and animals (including humans) occupy in this diagram shows how recently these groups had their origin compared with other groups.
    
    
            
    
    The phylogenetic tree in {'Figure_12_1_1 Figure 12.1.1} illustrates the pathway of evolutionary history. The pathway can be traced from the origin of life to any individual species by navigating through the evolutionary branches between the two points. Also, by starting with a single species and tracing backward to any branch point, the organisms related to it by various degrees of closeness can be identified.
    
    A  **phylogeny** is the evolutionary history and the relationships among a species or group of species. The study of organisms with the purpose of deriving their relationships is called  **systematics**.
    
    Many disciplines within the study of biology contribute to understanding how past and present life evolved over time, and together they contribute to building, updating, and maintaining the “tree of life.” Information gathered may include data collected from fossils, from studying morphology, from the structure of body parts, or from molecular structure, such as the sequence of amino acids in proteins or DNA nucleotides. By considering the trees generated by different sets of data scientists can put together the phylogeny of a species.
    
    Scientists continue to discover new species of life on Earth as well as new character information, thus trees change as new data arrive.

  apply FullText

  ---
    4_12_1_0
    4_12_1_1
    4_12_1_2
    4_12_1_3
    4_12_1_4

  / Organizing Life on Earth - Full Text
  path FullText
    step
      --
        4_12_1_0
    step
      --
        4_12_1_1
    step
      --
        4_12_1_2
    step
      --
        4_12_1_3
    step
      --
        4_12_1_4

    