
/ Kinematics of Rotational Motion
story 10_2
  >
    Just by using our intuition, we can begin to see how rotational quantities like <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>θ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ&#125; &#123;&#125;</annotation></semantics></math>, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>ω</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;ω&#125; &#123;&#125;</annotation></semantics></math>, and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>α</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;α&#125; &#123;&#125;</annotation></semantics></math> are related to one another. For example, if a motorcycle wheel has a large angular acceleration for a fairly long time, it ends up spinning rapidly and rotates through many revolutions. In more technical terms, if the wheel’s angular acceleration <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>α</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;α&#125; &#123;&#125;</annotation></semantics></math> is large for a long period of time <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>t</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;α&#125; &#123;&#125;</annotation></semantics></math>, then the final angular velocity <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>ω</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;ω&#125; &#123;&#125;</annotation></semantics></math> and angle of rotation <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>θ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ&#125; &#123;&#125;</annotation></semantics></math> are large. The wheel’s rotational motion is exactly analogous to the fact that the motorcycle’s large translational acceleration produces a large final velocity, and the distance traveled will also be large.
    
    Kinematics is the description of motion. The  **kinematics of rotational motion** describes the relationships among rotation angle, angular velocity, angular acceleration, and time. Let us start by finding an equation relating <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>ω</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;ω&#125; &#123;&#125;</annotation></semantics></math>, <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>α</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;α&#125; &#123;&#125;</annotation></semantics></math>, and <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>t</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;t&#125; &#123;&#125;</annotation></semantics></math>. To determine this equation, we recall a familiar kinematic equation for translational, or straight-line, motion:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <mi>v</mi>                    <mo stretchy="false">=</mo>                    <mrow>                      <msub>                        <mi>v</mi>                                                  <mrow>                            <mn>0</mn>                          </mrow>                                              </msub>                      <mo stretchy="false">+</mo>                      <mstyle fontstyle="italic">                        <mrow>                          <mtext>at</mtext>                        </mrow>                      </mstyle>                    </mrow>                  </mrow>                  <mtext>     </mtext>                  <mo stretchy="false">(</mo>                  <mtext>constant </mtext>                  <mi>a</mi>                  <mo stretchy="false">)</mo>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;v=v rSub &#123; size 8&#123;0&#125; &#125; + ital &quot;at&quot;&quot;    &quot; \[ &quot;constant &quot;a \] &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    Note that in rotational motion <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>a</mi><mo stretchy="false">=</mo><msub><mi>a</mi><mrow><mtext>t</mtext></mrow></msub></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a=a rSub &#123; size 8&#123;t&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>, and we shall use the symbol <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>a</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a&#125; &#123;&#125;</annotation></semantics></math> for tangential or linear acceleration from now on. As in linear kinematics, we assume <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>a</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a&#125; &#123;&#125;</annotation></semantics></math> is constant, which means that angular acceleration <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>α</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;α&#125; &#123;&#125;</annotation></semantics></math> is also a constant, because <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>a</mi><mo stretchy="false">=</mo><mi fontstyle="italic">rα</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a=rα&#125; &#123;&#125;</annotation></semantics></math>. Now, let us substitute <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>v</mi><mo stretchy="false">=</mo><mi fontstyle="italic">rω</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v=rω&#125; &#123;&#125;</annotation></semantics></math> and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>a</mi><mo stretchy="false">=</mo><mi fontstyle="italic">rα</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a=rα&#125; &#123;&#125;</annotation></semantics></math> into the linear equation above:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mi fontstyle="italic">rω</mi>                  <mo stretchy="false">=</mo>                  <mrow>                    <msub>                      <mi fontstyle="italic">rω</mi>                                              <mrow>                          <mn>0</mn>                        </mrow>                                          </msub>                    <mo stretchy="false">+</mo>                    <mi fontstyle="italic">rαt</mi>                  </mrow>                </mrow>              </mrow>                        <mrow/><mo>.</mo>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;rω=rω rSub &#123; size 8&#123;0&#125; &#125; +rαt&#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    The radius <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>r</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;r&#125; &#123;&#125;</annotation></semantics></math> cancels in the equation, yielding
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <mi>ω</mi>                    <mo stretchy="false">=</mo>                    <mrow>                      <msub>                        <mi>ω</mi>                                                  <mrow>                            <mn>0</mn>                          </mrow>                                              </msub>                      <mo stretchy="false">+</mo>                      <mstyle fontstyle="italic">                        <mrow>                          <mtext>at</mtext>                        </mrow>                      </mstyle>                    </mrow>                  </mrow>                  <mtext>     </mtext>                  <mo stretchy="false">(</mo>                  <mtext>constant </mtext>                  <mi>a</mi>                  <mo stretchy="false">)</mo>                  <mi>,</mi>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;ω=ω rSub &#123; size 8&#123;0&#125; &#125; + ital &quot;at&quot;&quot;    &quot; \[ &quot;constant &quot;a \] ,&#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    where <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>ω</mi><mrow><mn>0</mn></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;ω rSub &#123; size 8&#123;0&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the initial angular velocity. This last equation is a  *kinematic relationship* among <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>ω</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;ω&#125; &#123;&#125;</annotation></semantics></math>, <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>α</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;α&#125; &#123;&#125;</annotation></semantics></math>, and <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>t</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;t&#125; &#123;&#125;</annotation></semantics></math> —that is, it describes their relationship without reference to forces or masses that may affect rotation. It is also precisely analogous in form to its translational counterpart. 
    
    Starting with the four kinematic equations we developed in <link:>, we can derive the following four rotational kinematic equations (presented together with their translational counterparts):
    
    
        
    
    In these equations, the subscript 0 denotes initial values (<sub>θ0 size 12&#123;θ rSub &#123; size 8&#123;0&#125; &#125; &#125; &#123;&#125;</sub>, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>x</mi><mrow><mn>0</mn></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;x rSub &#123; size 8&#123;0&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>, and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>t</mi><mrow><mn>0</mn></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;t rSub &#123; size 8&#123;0&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> are initial values), and the average angular velocity <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mover accent="true"><mi>ω</mi><mo stretchy="true">-</mo></mover></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123; bar  &#123;ω&#125;&#125;&#125; &#123;&#125;</annotation></semantics></math> and average velocity <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mover accent="true"><mi>v</mi><mo stretchy="true">-</mo></mover></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123; bar  &#123;v&#125;&#125;&#125; &#123;&#125;</annotation></semantics></math> are defined as follows:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <mover accent="true">                      <mi>ω</mi>                      <mo>¯</mo>                    </mover>                    <mo stretchy="false">=</mo>                    <mfrac>                      <mrow>                        <msub>                          <mi>ω</mi>                                                      <mrow>                              <mn>0</mn>                            </mrow>                                                  </msub>                        <mo stretchy="false">+</mo>                        <mi>ω</mi>                      </mrow>                      <mn>2</mn>                    </mfrac>                  </mrow>                  <mtext> and </mtext>                  <mrow>                    <mover accent="true">                      <mi>v</mi>                      <mo>¯</mo>                    </mover>                    <mspace width="0.25em"/><mo stretchy="false">=</mo><mspace width="0.25em"/>                    <mfrac>                      <mrow>                        <msub>                          <mi>v</mi>                                                      <mrow>                              <mn>0</mn>                            </mrow>                                                  </msub>                        <mo stretchy="false">+</mo>                        <mi>v</mi>                      </mrow>                      <mn>2</mn>                    </mfrac>                  </mrow><mo>.</mo>                                                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123; &#123;overline  &#123;ω&#125;&#125; = &#123;  &#123;ω rSub &#123; size 8&#123;0&#125; &#125; +ω&#125;  over  &#123;2&#125; &#125; &quot; and &quot; &#123;overline  &#123;v&#125;&#125; = &#123;  &#123;v rSub &#123; size 8&#123;0&#125; &#125; +v&#125;  over  &#123;2&#125; &#125; &quot;   &quot; \( &quot;constant &quot;α, a \) &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    The equations given above in  can be used to solve any rotational or translational kinematics problem in which <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>a</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a&#125; &#123;&#125;</annotation></semantics></math> and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>α</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;α&#125; &#123;&#125;</annotation></semantics></math> are constant.
    
    
            
    
    There is translational motion even for something spinning in place, as the following example illustrates. {'Figure_11_2_2a Figure 11.2.2a} shows a fly on the edge of a rotating microwave oven plate. The example below calculates the total distance it travels.
    
    
            

  apply FullText

  ---
    10_2_0
    10_2_1

  / Kinematics of Rotational Motion - Full Text
  path FullText
    step
      --
        10_2_0
    step
      --
        10_2_1

    