
/ Standard Reduction Potentials
story 16_3
  >
    The cell potential in {'Figure_17_2_Galvanicel Figure 17.2.Galvanicel} (+0.46 V) results from the difference in the electrical potentials for each electrode. While it is impossible to determine the electrical potential of a single electrode, we can assign an electrode the value of zero and then use it as a reference. The electrode chosen as the zero is shown in {'Figure_17_3_SHE Figure 17.3.SHE} and is called the  **standard hydrogen electrode (SHE)**. The SHE consists of 1 atm of hydrogen gas bubbled through a 1 M HCl solution, usually at room temperature. Platinum, which is chemically inert, is used as the electrode. The reduction half-reaction chosen as the reference is
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msup><mrow><mtext>2H</mtext></mrow><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mtext>, 1</mtext><mspace width="0.2em"/><mi>M</mi><mo stretchy="false">)</mo><mo>+</mo><mn>2</mn><msup><mtext>e</mtext><mtext>−</mtext></msup><mo stretchy="false">⇌</mo><msub><mtext>H</mtext><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo>,</mo><mspace width="0.2em"/><mtext>1 atm</mtext><mo stretchy="false">)</mo><mspace width="5em"/><mi>E</mi><mtext>°</mtext><mo>=</mo><mtext>0 V</mtext></mrow></math>
    
     *E*° is the standard reduction potential. The superscript “°” on the  *E* denotes standard conditions (1 bar or 1 atm for gases, 1  *M* for solutes). This voltage is defined as zero for all temperatures.
    
    
            
    
    A galvanic cell consisting of a SHE and Cu<sup>2+</sup>/Cu half-cell can be used to determine the standard reduction potential for Cu<sup>2+</sup> ({'Figure_17_3_GalvanCu Figure 17.3.GalvanCu}). In cell notation, the reaction is
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>Pt</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>│</mo><msub><mtext>H</mtext><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo>,</mo><mspace width="0.2em"/><mtext>1 atm</mtext><mo stretchy="false">)</mo><mo>│</mo><msup><mtext>H</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo>,</mo><mspace width="0.2em"/><mn>1</mn><mspace width="0.2em"/><mi>M</mi><mo stretchy="false">)</mo><mo>║</mo><msup><mrow><mtext>Cu</mtext></mrow><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo>,</mo><mspace width="0.2em"/><mn>1</mn><mspace width="0.2em"/><mi>M</mi><mo stretchy="false">)</mo><mo>│</mo><mspace width="0.2em"/><mtext>Cu</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mrow></math>
    
    Electrons flow from the anode to the cathode. The reactions, which are reversible, are
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mtable columnalign="left"><mtr><mtd><munder accentunder="true"><mtable columnalign="left"><mtr><mtd><mtext>Anode (oxidation):</mtext><mspace width="5.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msup><mtext>2H</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><msup><mtext>) + 2e</mtext><mtext>−</mtext></msup></mtd></mtr><mtr><mtd><mtext>Cathode (reduction):</mtext><mspace width="0.2em"/><msup><mtext>Cu</mtext><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>2e</mtext><mtext>−</mtext></msup><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><mtext>Cu</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mtd></mtr></mtable><mo stretchy="true">¯</mo></munder></mtd></mtr><mtr><mtd><mtext>Overall:</mtext><mspace width="4.6em"/><msup><mtext>Cu</mtext><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msup><mtext>2H</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><mtext>Cu</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mtd></mtr></mtable></math>
    
    The standard cell potential, E°<sub>cell</sub>, can be determined by subtracting the standard reduction potential for the reaction occurring at the anode from the standard reduction potential for the reaction occurring at the cathode. The minus sign is necessary because oxidation is the reverse of reduction. The minus sign is necessary because oxidation is the reverse of reduction.
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msubsup><mi>E</mi><mrow><mtext>cell</mtext></mrow><mo>°</mo></msubsup><mspace width="0.1em"/><mo>=</mo><mspace width="0.1em"/><msubsup><mi>E</mi><mrow><mtext>cathode</mtext></mrow><mo>°</mo></msubsup><mo>−</mo><msubsup><mi>E</mi><mrow><mtext>anode</mtext></mrow><mo>°</mo></msubsup></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>+0.34 V</mtext><mo>=</mo><mspace width="0.1em"/><msubsup><mi>E</mi><mrow><msup><mrow><mtext>Cu</mtext></mrow><mrow><mn>2+</mn></mrow></msup><mtext>/Cu</mtext></mrow><mo>°</mo></msubsup><mo>−</mo><msubsup><mi>E</mi><mrow><msup><mtext>H</mtext><mtext>+</mtext></msup><msub><mrow><mtext>/H</mtext></mrow><mn>2</mn></msub></mrow><mo>°</mo></msubsup><mspace width="0.1em"/><mo>=</mo><mspace width="0.1em"/><msubsup><mi>E</mi><mrow><msup><mrow><mtext>Cu</mtext></mrow><mrow><mn>2+</mn></mrow></msup><mtext>/Cu</mtext></mrow><mo>°</mo></msubsup><mo>−</mo><mn>0</mn><mspace width="0.1em"/><mo>=</mo><mspace width="0.1em"/><msubsup><mi>E</mi><mrow><msup><mrow><mtext>Cu</mtext></mrow><mrow><mn>2+</mn></mrow></msup><mtext>/Cu</mtext></mrow><mo>°</mo></msubsup></mrow></math>
    
    
            
    
    Using the SHE as a reference, other standard reduction potentials can be determined. Consider the cell shown in {'Figure_17_3_GalvanAg Figure 17.3.GalvanAg}, where
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>Pt</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>│</mo><msub><mtext>H</mtext><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo>,</mo><mspace width="0.2em"/><mtext>1 atm</mtext><mo stretchy="false">)</mo><mo>│</mo><msup><mtext>H</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mtext>, 1</mtext><mspace width="0.2em"/><mi>M</mi><mo stretchy="false">)</mo><mo>║</mo><msup><mrow><mtext>Ag</mtext></mrow><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mtext>, 1</mtext><mspace width="0.2em"/><mi>M</mi><mo stretchy="false">)</mo><mo>│</mo><mtext>Ag</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mrow></math>
    
    Electrons flow from left to right, and the reactions are
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mtable columnalign="left"><mtr><mtd><munder accentunder="true"><mtable columnalign="left"><mtr><mtd><mtext>anode (oxidation):</mtext><mspace width="5.4em"/><msub><mtext>H</mtext><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msup><mtext>2H</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>2e</mtext><mtext>−</mtext></msup></mtd></mtr><mtr><mtd><mtext>cathode (reduction):</mtext><mspace width="0.2em"/><mn>2</mn><msup><mtext>Ag</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>2e</mtext><mtext>−</mtext></msup><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><mtext>2Ag</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mtd></mtr></mtable><mo stretchy="true">¯</mo></munder></mtd></mtr><mtr><mtd><mtext>overall:</mtext><mspace width="4.6em"/><mn>2</mn><msup><mtext>Ag</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msup><mtext>2H</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><mtext>2Ag</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mtd></mtr></mtable></math>
    
    The standard cell potential, E°<sub>cell</sub>, can be determined by subtracting the standard reduction potential for the reaction occurring at the anode from the standard reduction potential for the reaction occurring at the cathode. The minus sign is needed because oxidation is the reverse of reduction.
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msubsup><mi>E</mi><mrow><mtext>cell</mtext></mrow><mo>°</mo></msubsup><mspace width="0.1em"/><mo>=</mo><mspace width="0.1em"/><msubsup><mi>E</mi><mrow><mtext>cathode</mtext></mrow><mo>°</mo></msubsup><mo>−</mo><msubsup><mi>E</mi><mrow><mtext>anode</mtext></mrow><mo>°</mo></msubsup></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>+0.80 V</mtext><mo>=</mo><mspace width="0.1em"/><msubsup><mi>E</mi><mrow><msup><mrow><mtext>Ag</mtext></mrow><mtext>+</mtext></msup><mtext>/Ag</mtext></mrow><mo>°</mo></msubsup><mo>−</mo><msubsup><mi>E</mi><mrow><msup><mtext>H</mtext><mtext>+</mtext></msup><msub><mrow><mtext>/H</mtext></mrow><mn>2</mn></msub></mrow><mo>°</mo></msubsup><mspace width="0.1em"/><mo>=</mo><mspace width="0.1em"/><msubsup><mi>E</mi><mrow><msup><mrow><mtext>Ag</mtext></mrow><mtext>+</mtext></msup><mtext>/Ag</mtext></mrow><mo>°</mo></msubsup><mo>−</mo><mn>0</mn><mspace width="0.1em"/><mo>=</mo><mspace width="0.1em"/><msubsup><mi>E</mi><mrow><msup><mrow><mtext>Ag</mtext></mrow><mtext>+</mtext></msup><mtext>/Ag</mtext></mrow><mo>°</mo></msubsup></mrow></math>
    
    It is important to note that the potential is  *not* doubled for the cathode reaction.
    
    The SHE is rather dangerous and rarely used in the laboratory. Its main significance is that it established the zero for standard reduction potentials. Once determined, standard reduction potentials can be used to determine the  **standard cell potential**, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msubsup><mi>E</mi><mrow><mtext>cell</mtext></mrow><mo>°</mo></msubsup><mo>,</mo></mrow></math> for any cell. For example, for the cell shown in {'Figure_17_2_Galvanicel Figure 17.2.Galvanicel},
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>Cu</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>│</mo><msup><mrow><mtext>Cu</mtext></mrow><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo>,</mo><mspace width="0.2em"/><mn>1</mn><mspace width="0.2em"/><mi>M</mi><mo stretchy="false">)</mo><mo>║</mo><msup><mrow><mtext>Ag</mtext></mrow><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo>,</mo><mspace width="0.2em"/><mn>1</mn><mspace width="0.2em"/><mi>M</mi><mo stretchy="false">)</mo><mo>│</mo><mtext>Ag</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mtable columnalign="left"><mtr/><mtr><mtd><munder accentunder="true"><mtable columnalign="left"><mtr><mtd><mtext>anode (oxidation):</mtext><mspace width="5.5em"/><mtext>Cu</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msup><mtext>Cu</mtext><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>2e</mtext><mtext>−</mtext></msup></mtd></mtr><mtr><mtd><mtext>cathode (reduction):</mtext><mspace width="0.2em"/><mn>2</mn><msup><mtext>Ag</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>2e</mtext><mtext>−</mtext></msup><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><mtext>2Ag</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mtd></mtr></mtable><mo stretchy="true">¯</mo></munder></mtd></mtr><mtr><mtd><mtext>overall:</mtext><mspace width="4.7em"/><mtext>Cu</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>2Ag</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msup><mtext>Cu</mtext><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><mtext>2Ag</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mtd></mtr></mtable></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msubsup><mi>E</mi><mrow><mtext>cell</mtext></mrow><mo>°</mo></msubsup><mo>=</mo><msubsup><mi>E</mi><mrow><mtext>cathode</mtext></mrow><mo>°</mo></msubsup><mo>−</mo><msubsup><mi>E</mi><mrow><mtext>anode</mtext></mrow><mo>°</mo></msubsup><mo>=</mo><msubsup><mi>E</mi><mrow><msup><mrow><mtext>Ag</mtext></mrow><mtext>+</mtext></msup><mtext>/Ag</mtext></mrow><mo>°</mo></msubsup><mo>−</mo><msubsup><mi>E</mi><mrow><msup><mrow><mtext>Cu</mtext></mrow><mrow><mn>2+</mn></mrow></msup><mtext>/Cu</mtext></mrow><mo>°</mo></msubsup><mo>=</mo><mtext>0.80 V</mtext><mo>−</mo><mtext>0.34 V</mtext><mo>=</mo><mn>0.4</mn><mtext>6 V</mtext></mrow></math>
    
    Again, note that when calculating <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msubsup><mi>E</mi><mrow><mtext>cell</mtext></mrow><mo>°</mo></msubsup><mo>,</mo></mrow></math> standard reduction potentials always remain the same even when a half-reaction is multiplied by a factor. Standard reduction potentials for selected reduction reactions are shown in . A more complete list is provided in <link:>.
    
    
            
    
    
    
        
    
    Tables like this make it possible to determine the standard cell potential for many oxidation-reduction reactions.

  apply FullText

  ---
    16_3_0
    16_3_1
    16_3_2

  path FullText
    step
      --
        16_3_0
    step
      --
        16_3_1
    step
      --
        16_3_2

    