index: hide
. lib

  # https://www.cdc.gov/csels/dsepd/ss1978/lesson1/section10.html

  model InfectiousCycle

  model ViralLoad
    head = Viral load, also known as viral burden, viral titre or viral titer, is a numerical expression of the quantity of virus in a given volume.

  model Recombination
    # https://en.wikipedia.org/wiki/Genetic_recombination
    head = Genetic recombination (also known as genetic reshuffling) is the exchange of genetic material between different organisms which leads to production of offspring with combinations of traits that differ from those found in either parent.

  model Reservoirs

  model IndexCase
    head = The index case (sometimes referred to as patient zero) is the first documented patient in a disease epidemic within a population, or the first documented patient included in an epidemiological study.

  model Outbreak

  model Surveillance

  model Epidemic

  model Pandemic

  model R0
    head = In epidemiology, the basic reproduction number (sometimes called basic reproductive ratio, and denoted R0, pronounced R nought or R zero) of an infection can be thought of as the expected number of cases directly generated by one case in a population where all individuals are susceptible to infection.

  model SocialNetworks

  model SuperSpreader

  model Seasonality
