index: hide
. lib

  model R0
    head = In epidemiology, the basic reproduction number (sometimes called basic reproductive ratio, and denoted R0, pronounced R nought or R zero) of an infection can be thought of as the expected number of cases directly generated by one case in a population where all individuals are susceptible to infection.
  
