
/ Electrical Potential Due to a Point Charge
story 19_3
  >
    Point charges, such as electrons, are among the fundamental building blocks of matter. Furthermore, spherical charge distributions (like on a metal sphere) create external electric fields exactly like a point charge. The electric potential due to a point charge is, thus, a case we need to consider. Using calculus to find the work needed to move a test charge  *q size 12&#123;q&#125; &#123;&#125;* from a large distance away to a distance of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>r</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;r&#125; &#123;&#125;</annotation></semantics></math> from a point charge  *Q size 12&#123;Q&#125; &#123;&#125;*, and noting the connection between work and potential <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mfenced close=")" open="("><mrow><mi>W</mi><mo stretchy="false">=</mo><mspace width="0.25em"/><mrow><mo stretchy="false">–</mo><mi fontstyle="italic">q</mi><mn>Δ</mn><mi>V</mi></mrow></mrow></mfenced></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; left (W= - q?V right )&#125; &#123;&#125;</annotation></semantics></math>, it can be shown that the  *electric potential V size 12&#123;V&#125; &#123;&#125; of a point charge* is 
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">    <semantics>     <mrow>      <mstyle mathsize="12pt">       <mrow>        <mrow>         <mrow>          <mi>V          </mi>          <mo stretchy="false">=          </mo>          <mrow>           <mfrac>            <mrow>             <mstyle mathvariant="italic">              <mrow>               <mtext>kQ               </mtext>              </mrow>             </mstyle>            </mrow>            <mrow>             <mi>r             </mi>            </mrow>           </mfrac>          </mrow>         </mrow><mspace width="0.25em"/>         <mo stretchy="false">(         </mo>         <mtext>Point Charge         </mtext>         <mo stretchy="false">)         </mo>         <mi>,         </mi>        </mrow>       </mrow>      </mstyle>      <mrow/>     </mrow>     <annotation encoding="StarMath 5.0">size 12&#123;V= &#123;  &#123; ital &quot;kQ&quot;&#125;  over  &#123;r&#125; &#125;  \( &quot;Point Charge&quot; \) ,&#125; &#123;&#125;     </annotation>    </semantics>   </math>
    
    where  *k* is a constant equal to
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"> <semantics>  <mrow>    <mn>9.0</mn>    <mo>×</mo>   <msup>    <mtext>10</mtext>    <mtext>9</mtext>   </msup>   <mspace width="0.25em"/>   <mtext>N</mtext><mspace width="0.25em"/>   <mtext>·</mtext><mspace width="0.25em"/>   <msup>    <mtext>m</mtext>    <mtext>2</mtext>   </msup>   <mtext>/</mtext>   <msup>    <mtext>C</mtext>    <mtext>2</mtext>   </msup>  </mrow> </semantics></math>.
    
    The potential at infinity is chosen to be zero. Thus <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>V</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V&#125; &#123;&#125;</annotation></semantics></math> for a point charge decreases with distance, whereas <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mtext mathvariant="bold">E</mtext></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;E&#125; &#123;&#125;</annotation></semantics></math> for a point charge decreases with distance squared:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mtext fontstyle="italic">E</mtext><mo stretchy="false">=</mo><mfrac><mtext fontstyle="italic">F</mtext><mi>q</mi></mfrac></mrow><mo stretchy="false">=</mo><mfrac> <mtext fontstyle="italic">kQ</mtext> <msup>  <mi>r</mi>  <mn>2</mn> </msup></mfrac><mo>.</mo></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; left (E=F/q right )= ital &quot;kQ/r&quot; rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    Recall that the electric potential <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>V</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V&#125; &#123;&#125;</annotation></semantics></math> is a scalar and has no direction, whereas the electric field <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mtext mathvariant="bold">E</mtext></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;E&#125; &#123;&#125;</annotation></semantics></math> is a vector. To find the voltage due to a combination of point charges, you add the individual voltages as numbers. To find the total electric field, you must add the individual fields as  *vectors*, taking magnitude and direction into account. This is consistent with the fact that <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>V</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V&#125; &#123;&#125;</annotation></semantics></math> is closely associated with energy, a scalar, whereas <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mtext mathvariant="bold">E</mtext></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;E&#125; &#123;&#125;</annotation></semantics></math> is closely associated with force, a vector.
    
    The voltages in both of these examples could be measured with a meter that compares the measured potential with ground potential. Ground potential is often taken to be zero (instead of taking the potential at infinity to be zero). It is the potential difference between two points that is of importance, and very often there is a tacit assumption that some reference point, such as Earth or a very distant point, is at zero potential. As noted in <link:>, this is analogous to taking sea level as <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>h</mi><mo stretchy="false">=</mo><mi>0</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;h=0&#125; &#123;&#125;</annotation></semantics></math> when considering gravitational potential energy, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mtext>PE</mtext><mrow><mn>g</mn></mrow></msub><mo stretchy="false">=</mo><mstyle fontstyle="italic"><mrow><mtext>mgh</mtext></mrow></mstyle></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;PE&quot; rSub &#123; size 8&#123;g&#125; &#125; = ital &quot;mgh&quot;&#125; &#123;&#125;</annotation></semantics></math>.

  apply FullText

  ---
    19_3_0
    19_3_1

  path FullText
    step
      --
        19_3_0
    step
      --
        19_3_1

    