
/ Energy in Electromagnetic Waves
story 24_4
  >
    Anyone who has used a microwave oven knows there is energy in  **electromagnetic waves**. Sometimes this energy is obvious, such as in the warmth of the summer sun. Other times it is subtle, such as the unfelt energy of gamma rays, which can destroy living cells.
    
    Electromagnetic waves can bring energy into a system by virtue of their  **electric and magnetic fields**. These fields can exert forces and move charges in the system and, thus, do work on them. If the frequency of the electromagnetic wave is the same as the natural frequencies of the system (such as microwaves at the resonant frequency of water molecules), the transfer of energy is much more efficient.
    
    
            
    
    But there is energy in an electromagnetic wave, whether it is absorbed or not. Once created, the fields carry energy away from a source. If absorbed, the field strengths are diminished and anything left travels on. Clearly, the larger the strength of the electric and magnetic fields, the more work they can do and the greater the energy the electromagnetic wave carries. 
    
    A wave’s energy is proportional to its  **amplitude** squared (<math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mi>E</mi><mrow><mn>2</mn></mrow></msup></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;E rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> or <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mi>B</mi><mrow><mn>2</mn></mrow></msup></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;B rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>). This is true for waves on guitar strings, for water waves, and for sound waves, where amplitude is proportional to pressure. In electromagnetic waves, the amplitude is the  **maximum field strength** of the electric and magnetic fields. (See {'Figure25_4_1a Figure25.4.1a}.) 
    
    Thus the energy carried and the  **intensity**<math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>I</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I&#125; &#123;&#125;</annotation></semantics></math> of an electromagnetic wave is proportional to <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mi>E</mi><mrow><mn>2</mn></mrow></msup></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;E rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> and <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mi>B</mi><mrow><mn>2</mn></mrow></msup></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;B rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>. In fact, for a continuous sinusoidal electromagnetic wave, the average intensity <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>I</mi><mrow><mtext>ave</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I rSub &#123; size 8&#123;&quot;ave&quot;&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is given by
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mi>I</mi><mrow><mtext>ave</mtext></mrow></msub><mo stretchy="false">=</mo><mfrac><mrow><msub><mi fontstyle="italic">cε</mi><mrow><mn>0</mn></mrow></msub><msubsup><mi>E</mi><mrow><mn>0</mn></mrow><mrow><mn>2</mn></mrow></msubsup></mrow><mn>2</mn></mfrac><mo>,</mo></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I rSub &#123; size 8&#123;&quot;ave&quot;&#125; &#125; = &#123;  &#123;ce rSub &#123; size 8&#123;0&#125; &#125; E rSub &#123; size 8&#123;0&#125; &#125;  rSup &#123; size 8&#123;2&#125; &#125; &#125;  over  &#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    where <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>c</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;c&#125; &#123;&#125;</annotation></semantics></math> is the speed of light, <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>ε</mi><mrow><mn>0</mn></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;ε rSub &#123; size 8&#123;0&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the permittivity of free space, and <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>E</mi><mrow><mn>0</mn></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;E rSub &#123; size 8&#123;0&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the maximum electric field strength; intensity, as always, is power per unit area (here in <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mtext>W/m</mtext><mrow><mn>2</mn></mrow></msup></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;W/m&quot; rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>).
    
    The average intensity of an electromagnetic wave <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>I</mi><mrow><mtext>ave</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I rSub &#123; size 8&#123;&quot;ave&quot;&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> can also be expressed in terms of the magnetic field strength by using the relationship <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>B</mi><mo stretchy="false">=</mo><mrow><mi>E</mi><mo stretchy="false">/</mo><mi>c</mi></mrow></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;B= &#123;E&#125; slash &#123;c&#125; &#125; &#123;&#125;</annotation></semantics></math>, and the fact that <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>ε</mi><mrow><mn>0</mn></mrow></msub><mo stretchy="false">=</mo><mrow><mn>1</mn><mo stretchy="false">/</mo><msub><mi>μ</mi><mrow><mn>0</mn></mrow></msub></mrow></mrow><msup><mi>c</mi><mrow><mn>2</mn></mrow></msup></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;ε rSub &#123; size 8&#123;0&#125; &#125; = &#123;1&#125; slash &#123;μ rSub &#123; size 8&#123;0&#125; &#125; &#125; c rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>, where <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>μ</mi><mrow><mn>0</mn></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;μ rSub &#123; size 8&#123;0&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the permeability of free space. Algebraic manipulation produces the relationship
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mi>I</mi><mrow><mtext>ave</mtext></mrow></msub><mo stretchy="false">=</mo><mfrac><mrow><msubsup><mstyle fontstyle="italic"><mtext>cB</mtext></mstyle><mrow><mn>0</mn></mrow><mrow><mn>2</mn></mrow></msubsup></mrow><msub><mn>2μ</mn><mrow><mn>0</mn></mrow></msub></mfrac><mo>,</mo></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I rSub &#123; size 8&#123;&quot;ave&quot;&#125; &#125; = &#123;  &#123; ital &quot;cB&quot; rSub &#123; size 8&#123;0&#125; &#125;  rSup &#123; size 8&#123;2&#125; &#125; &#125;  over  &#123;2μ rSub &#123; size 8&#123;0&#125; &#125; &#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    where <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>B</mi><mrow><mn>0</mn></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;B rSub &#123; size 8&#123;0&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the maximum magnetic field strength.
    
    One more expression for <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>I</mi><mrow><mtext>ave</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I rSub &#123; size 8&#123;&quot;ave&quot;&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> in terms of both electric and magnetic field strengths is useful. Substituting the fact that <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mi>c</mi><mo stretchy="false">⋅</mo><msub><mi>B</mi><mrow><mn>0</mn></mrow></msub></mrow><mo stretchy="false">=</mo><msub><mi>E</mi><mrow><mn>0</mn></mrow></msub></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;c cdot B rSub &#123; size 8&#123;0&#125; &#125; =E rSub &#123; size 8&#123;0&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>, the previous expression becomes
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mi>I</mi><mrow><mtext>ave</mtext></mrow></msub><mo stretchy="false">=</mo><mfrac><mrow><msub><mi>E</mi><mrow><mn>0</mn></mrow></msub><msub><mi>B</mi><mrow><mn>0</mn></mrow></msub></mrow><msub><mn>2μ</mn><mrow><mn>0</mn></mrow></msub></mfrac><mo>.</mo></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I rSub &#123; size 8&#123;&quot;ave&quot;&#125; &#125; = &#123;  &#123;E rSub &#123; size 8&#123;0&#125; &#125; B rSub &#123; size 8&#123;0&#125; &#125; &#125;  over  &#123;2μ rSub &#123; size 8&#123;0&#125; &#125; &#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    Whichever of the three preceding equations is most convenient can be used, since they are really just different versions of the same principle: Energy in a wave is related to amplitude squared. Furthermore, since these equations are based on the assumption that the electromagnetic waves are sinusoidal, peak intensity is twice the average; that is, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mi>I</mi><mrow><mn>0</mn></mrow></msub><mo stretchy="false">=</mo><mn>2</mn><msub><mi>I</mi><mrow><mtext>ave</mtext></mrow></msub></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I rSub &#123; size 8&#123;0&#125; &#125; =2I rSub &#123; size 8&#123;&quot;ave&quot;&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>.

  apply FullText

  ---
    24_4_0
    24_4_1

  / Energy in Electromagnetic Waves - Full Text
  path FullText
    step
      --
        24_4_0
    step
      --
        24_4_1

    