
/ Rotational Kinetic Energy: Work and Energy Revisited
story 10_4
  >
    In this module, we will learn about work and energy associated with rotational motion. {'Figure_11_4_1a Figure 11.4.1a} shows a worker using an electric grindstone propelled by a motor. Sparks are flying, and noise and vibration are created as layers of steel are pared from the pole. The stone continues to turn even after the motor is turned off, but it is eventually brought to a stop by friction. Clearly, the motor had to work to get the stone spinning. This work went into heat, light, sound, vibration, and considerable  **rotational kinetic energy**.
    
    
            
    
    Work must be done to rotate objects such as grindstones or merry-go-rounds. Work was defined in <link:> for translational motion, and we can build on that knowledge when considering work done in rotational motion. The simplest rotational situation is one in which the net force is exerted perpendicular to the radius of a disk (as shown in {'Figure_11_4_2a Figure 11.4.2a}) and remains perpendicular as the disk starts to rotate. The force is parallel to the displacement, and so the net work done is the product of the force times the arc length traveled:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mtext>net </mtext><mspace width="0.25em"/>                    <mi>W</mi>                    <mo stretchy="false">=</mo>                      <mo>(</mo>                          <mtext>net </mtext><mspace width="0.25em"/>                          <mi>F</mi>                      <mo>)</mo>                    <mtext>Δ</mtext>                      <mi fontstyle="italic">s</mi>                </mrow><mo>.</mo>              </mrow>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;&quot;net &quot;W= left (&quot;net &quot;F right ) cdot Δs&#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    To get torque and other rotational quantities into the equation, we multiply and divide the right-hand side of the equation by <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>r</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;r&#125; &#123;&#125;</annotation></semantics></math>, and gather terms:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mtext>net</mtext><mspace width="0.25em"/><mi>W</mi>                    <mo stretchy="false">=</mo>                    <mo stretchy="false">(</mo>                        <mi>r</mi><mspace width="0.25em"/>                        <mtext> net </mtext><mspace width="0.25em"/>                        <mi>F</mi>                    <mo stretchy="false">)</mo>                  <mfrac><mrow><mtext>Δ</mtext><mi>s</mi></mrow>                    <mi>r</mi>                  </mfrac>                </mrow>              </mrow>            <mo>.</mo>                     <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;&quot;net&quot;W= left (r&quot; net &quot;F right ) &#123;  &#123;Δs&#125;  over  &#123;r&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    We recognize that <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mi>r</mi><mspace width="0.25em"/><mtext> net </mtext><mspace width="0.25em"/><mi>F</mi><mo stretchy="false">=</mo><mtext> net τ</mtext></mrow><annotation encoding="StarMath 5.0"> size 12&#123;r&quot; net &quot;F=&quot; net &quot;τ&#125; &#123;&#125;</annotation></semantics></math> and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mn>Δ</mn><mi fontstyle="italic">s</mi></mrow><mo stretchy="false">/</mo><mi>r</mi><mo stretchy="false">=</mo><mi>θ</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Δs/r=θ&#125; &#123;&#125;</annotation></semantics></math>, so that
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>net </mtext><mspace width="0.25em"/><mrow><mi>W</mi><mo stretchy="false">=</mo><mfenced close=")" open="("><mrow><mtext>net τ</mtext></mrow></mfenced></mrow><mi>θ</mi></mrow></mrow><mrow/><mo>.</mo></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;net &quot;W= left (&quot;net &quot;τ right )θ&#125; &#123;&#125;</annotation></semantics></math>
    
    This equation is the expression for rotational work. It is very similar to the familiar definition of translational work as force multiplied by distance. Here, torque is analogous to force, and angle is analogous to distance. The equation <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>net </mtext><mspace width="0.25em"/><mrow><mi>W</mi><mo stretchy="false">=</mo><mfenced close=")" open="("><mrow><mtext>net τ</mtext></mrow></mfenced></mrow><mi>θ</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;net &quot;W= left (&quot;net &quot;τ right )θ&#125; &#123;&#125;</annotation></semantics></math> is valid in general, even though it was derived for a special case.
    
    To get an expression for rotational kinetic energy, we must again perform some algebraic manipulations. The first step is to note that <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>net τ</mtext><mo stretchy="false">=</mo><mi fontstyle="italic">Iα</mi></mrow></mrow></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;net &quot;W=Iα&#125; &#123;&#125;</annotation></semantics></math>, so that
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>net </mtext><mspace width="0.25em"/><mrow><mi>W</mi><mo stretchy="false">=</mo><mi>I</mi></mrow><mstyle fontstyle="italic"><mrow><mtext>αθ</mtext></mrow></mstyle></mrow></mrow><mrow/><mo>.</mo></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;net &quot;W=I ital &quot;αθ&quot;&#125; &#123;&#125;</annotation></semantics></math>
    
    
            
    
    Now, we solve one of the rotational kinematics equations for <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mstyle fontstyle="italic"><mrow><mtext>αθ</mtext></mrow></mstyle></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;αθ&quot;&#125; &#123;&#125;</annotation></semantics></math>. We start with the equation
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <msup>                     <mrow>                      <msub>                       <mi>ω</mi>                                             </msub>                     </mrow>                                           <mrow>                       <mn>2</mn>                     </mrow>                                          </msup>                    <mo stretchy="false">=</mo>                    <mrow>                      <msup>                     <mrow>                      <msub>                       <mi>ω</mi>                       <mtext>0</mtext>                      </msub>                     </mrow>                                           <mrow>                       <mn>2</mn>                     </mrow>                                          </msup>                      <mo stretchy="false">+</mo>                      <mn>2</mn>                    </mrow>                  </mrow>                  <mstyle fontstyle="italic">                    <mrow>                      <mtext>αθ</mtext>                    </mrow>                  </mstyle>                </mrow>              </mrow>            <mo>.</mo>                    <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;ω rSup &#123; size 8&#123;2&#125; &#125; =ω rSub &#123; size 8&#123;0&#125;   rSup &#123; size 8&#123;2&#125; &#125; &#125; +2 ital &quot;αθ&quot;&#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    Next, we solve for <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mstyle fontstyle="italic"><mrow><mtext>αθ</mtext></mrow></mstyle></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;αθ&quot;&#125; &#123;&#125;</annotation></semantics></math>:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mstyle fontstyle="italic">                    <mrow>                      <mtext>αθ</mtext>                    </mrow>                  </mstyle>                  <mo stretchy="false">=</mo>                  <mfrac>                    <mrow>                      <msup>                        <mi>ω</mi>                            <mn>2</mn>                      </msup>                      <mo stretchy="false">−</mo>                      <msup>                     <mrow>                      <msub>                       <mi>ω</mi>                       <mtext>0</mtext>                      </msub>                     </mrow>                                           <mrow>                       <mn>2</mn>                     </mrow>                                          </msup>                    </mrow>                    <mn>2</mn>                  </mfrac>                </mrow>              </mrow>            <mo>.</mo>            <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;αθ&quot;= &#123;  &#123;ω rSup &#123; size 8&#123;2&#125; &#125;  - ω rSub &#123; size 8&#123;0&#125;   rSup &#123; size 8&#123;2&#125; &#125; &#125; &#125;  over  &#123;2&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    Substituting this into the equation for net <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>W</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;W&#125; &#123;&#125;</annotation></semantics></math> and gathering terms yields
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>net </mtext><mrow><mspace width="0.25em"/><mi>W</mi><mo stretchy="false">=</mo><mfrac><mn>1</mn><mn>2</mn></mfrac></mrow><mrow><msup><mi fontstyle="italic">Iω</mi><mn>2</mn></msup><mo stretchy="false">−</mo><mfrac><mn>1</mn><mn>2</mn></mfrac></mrow><mi fontstyle="italic">I</mi><msup>                     <mrow>                      <msub>                       <mi>ω</mi>                       <mtext>0</mtext>                      </msub>                     </mrow>                                           <mrow>                       <mn>2</mn>                     </mrow>                                          </msup></mrow></mrow><mrow/><mo>.</mo></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;net &quot;W= &#123;  &#123;1&#125;  over  &#123;2&#125; &#125; Iω rSup &#123; size 8&#123;2&#125; &#125;  -  &#123;  &#123;1&#125;  over  &#123;2&#125; &#125; Iω rSub &#123; size 8&#123;0&#125;   rSup &#123; size 8&#123;2&#125; &#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    This equation is the  **work-energy theorem** for rotational motion only. As you may recall, net work changes the kinetic energy of a system. Through an analogy with translational motion, we define the term <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mfenced close=")" open="("><mfrac><mn>1</mn><mn>2</mn></mfrac></mfenced><msup><mi fontstyle="italic">Iω</mi><mrow><mn>2</mn></mrow></msup></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; left ( &#123;  &#123;1&#125;  over  &#123;2&#125; &#125;  right )Iω rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> to be  **rotational kinetic energy**<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mtext>KE</mtext><mrow><mrow><mtext>rot</mtext></mrow></mrow></msub></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;KE&quot; rSub &#123; size 8&#123; ital &quot;rot&quot;&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> for an object with a moment of inertia <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>I</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I&#125; &#123;&#125;</annotation></semantics></math> and an angular velocity <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>ω</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;ω&#125; &#123;&#125;</annotation></semantics></math>:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <msub>                      <mtext>KE</mtext>                                              <mrow>                          <mtext>rot</mtext>                        </mrow>                                          </msub>                    <mo stretchy="false">=</mo>                    <mfrac>                      <mn>1</mn>                      <mn>2</mn>                    </mfrac>                  </mrow>                  <msup>                    <mi fontstyle="italic">Iω</mi>                                          <mrow>                        <mn>2</mn>                      </mrow>                                      </msup>                </mrow>              </mrow>            <mo>.</mo>            <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;&quot;KE&quot; rSub &#123; size 8&#123;&quot;rot&quot;&#125; &#125; = &#123;  &#123;1&#125;  over  &#123;2&#125; &#125; Iω rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    The expression for rotational kinetic energy is exactly analogous to translational kinetic energy, with <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>I</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I&#125; &#123;&#125;</annotation></semantics></math> being analogous to <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>m</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;m&#125; &#123;&#125;</annotation></semantics></math> and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>ω</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;ω&#125; &#123;&#125;</annotation></semantics></math> to <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>v</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v&#125; &#123;&#125;</annotation></semantics></math>. Rotational kinetic energy has important effects. Flywheels, for example, can be used to store large amounts of rotational kinetic energy in a vehicle, as seen in {'Figure_11_4_3a Figure 11.4.3a}.
    
    
            
    
    Helicopter pilots are quite familiar with rotational kinetic energy. They know, for example, that a point of no return will be reached if they allow their blades to slow below a critical angular velocity during flight. The blades lose lift, and it is impossible to immediately get the blades spinning fast enough to regain it. Rotational kinetic energy must be supplied to the blades to get them to rotate faster, and enough energy cannot be supplied in time to avoid a crash. Because of weight limitations, helicopter engines are too small to supply both the energy needed for lift and to replenish the rotational kinetic energy of the blades once they have slowed down. The rotational kinetic energy is put into them before takeoff and must not be allowed to drop below this crucial level. One possible way to avoid a crash is to use the gravitational potential energy of the helicopter to replenish the rotational kinetic energy of the blades by losing altitude and aligning the blades so that the helicopter is spun up in the descent. Of course, if the helicopter’s altitude is too low, then there is insufficient time for the blade to regain lift before reaching the ground.
    
    
            

  apply FullText

  ---
    10_4_0
    10_4_1
    10_4_2

  path FullText
    step
      --
        10_4_0
    step
      --
        10_4_1
    step
      --
        10_4_2

    