#!/bin/bash

mkdir ./app/versions

echo "Downloading latest application..."
curl https://static.common.page/app/common-dev.tar --output ./app/versions/common-dev.tar

echo "Removing old version..."
rm -rf ./app/versions/current

echo "Unzipping archive..."
tar -xzvf ./app/versions/common-dev.tar -C ./app/versions/

echo "Installing current version..."
mv ./app/versions/data/dev-release ./app/versions/current

echo
echo "Done"
echo
echo "Run the application with: ./app/run"
