
/ Galvanic Cells
story 16_2
  >
     **Galvanic cells**, also known as  **voltaic cells**, are electrochemical cells in which spontaneous oxidation-reduction reactions produce electrical energy. In writing the equations, it is often convenient to separate the oxidation-reduction reactions into half-reactions to facilitate balancing the overall equation and to emphasize the actual chemical transformations.
    
    Consider what happens when a clean piece of copper metal is placed in a solution of silver nitrate ({'Figure_17_2_CuAg Figure 17.2.CuAg}). As soon as the copper metal is added, silver metal begins to form and copper ions pass into the solution. The blue color of the solution on the far right indicates the presence of copper ions. The reaction may be split into its two half-reactions. Half-reactions separate the oxidation from the reduction, so each can be considered individually.
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mtable columnalign="left"><mtr/><mtr/><mtr><mtd><munder accentunder="true"><mtable columnalign="left"><mtr><mtd><mtext>oxidation:</mtext><mspace width="5.7em"/><mtext>Cu</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msup><mtext>Cu</mtext><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>2e</mtext><mtext>−</mtext></msup></mtd></mtr><mtr><mtd><mtext>reduction:</mtext><mspace width="0.2em"/><mtext>2</mtext><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><mo stretchy="false">(</mo><msup><mtext>Ag</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>e</mtext><mtext>−</mtext></msup><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><mtext>Ag</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo stretchy="false">)</mo><mspace width="5em"/><mtext>or</mtext><mspace width="5em"/><mn>2</mn><msup><mtext>Ag</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>2e</mtext><mtext>−</mtext></msup><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><mtext>2Ag</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mtd></mtr></mtable><mo stretchy="true">¯</mo></munder></mtd></mtr><mtr><mtd><mtext>overall:</mtext><mspace width="1.5em"/><mn>2</mn><msup><mtext>Ag</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><mtext>Cu</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><mtext>2Ag</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>Cu</mtext><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mtd></mtr></mtable></math>
    
    The equation for the reduction half-reaction had to be doubled so the number of electrons “gained” in the reduction half-reaction equaled the number of electrons “lost” in the oxidation half-reaction.
    
    
            
    
    Galvanic or voltaic cells involve spontaneous electrochemical reactions in which the half-reactions are separated ({'Figure_17_2_Galvanicel Figure 17.2.Galvanicel}) so that current can flow through an external wire. The beaker on the left side of the figure is called a half-cell, and contains a 1  *M* solution of copper(II) nitrate [Cu(NO<sub>3</sub>)<sub>2</sub>] with a piece of copper metal partially submerged in the solution. The copper metal is an electrode. The copper is undergoing oxidation; the copper electrode is referred to as the  **anode**. The anode is connected to a voltmeter with a wire and the other terminal of the voltmeter is connected to a silver electrode by a wire. The silver is undergoing reduction; the silver electrode is referred to as the  **cathode**. The half-cell on the right side of the figure consists of the silver electrode in a 1  *M* solution of silver nitrate (AgNO<sub>3</sub>). At this point, no current flows—that is, no significant movement of electrons through the wire occurs because the circuit is open. The circuit is closed using a salt bridge, which transmits the current with moving ions. The salt bridge consists of a concentrated, nonreactive, electrolyte solution such as the sodium nitrate (NaNO<sub>3</sub>) solution used in this example. As electrons flow from left to right through the electrode and wire, nitrate ions (anions) pass through the porous plug on the left into the copper(II) nitrate solution. This keeps the beaker on the left electrically neutral by neutralizing the charge on the copper(II) ions that are produced in the solution as the copper metal is oxidized. At the same time, the nitrate ions are moving to the left, sodium ions (cations) move to the right, through the porous plug, and into the silver nitrate solution on the right. These added cations “replace” the silver ions that are removed from the solution as they were reduced to silver metal, keeping the beaker on the right electrically neutral. Without the salt bridge, the compartments would not remain electrically neutral and no significant current would flow. However, if the two compartments are in direct contact, a salt bridge is not necessary. The instant the circuit is completed, the voltmeter reads +0.46 V, this is called the  **cell potential**. The cell potential is created when the two dissimilar metals are connected, and is a measure of the energy per unit charge available from the oxidation-reduction reaction. The volt is the derived SI unit for electrical potential
    
    <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>volt</mtext><mo>=</mo><mi>V</mi><mo>=</mo><mfrac><mtext>J</mtext><mrow><mtext>C</mtext></mrow></mfrac></mrow></math>
    
    
            
    
    When the electrochemical cell is constructed in this fashion, a positive cell potential indicates a spontaneous reaction  *and* that the electrons are flowing from the left to the right. There is a lot going on in {'Figure_17_2_Galvanicel Figure 17.2.Galvanicel}, so it is useful to summarize things for this system:
    
      * Electrons flow from the anode to the cathode: left to right in the standard galvanic cell in the figure.
      * The electrode in the left half-cell is the anode because oxidation occurs here. The name refers to the flow of anions in the salt bridge toward it.
      * The electrode in the right half-cell is the cathode because reduction occurs here. The name refers to the flow of cations in the salt bridge toward it.
      * Oxidation occurs at the anode (the left half-cell in the figure).
      * Reduction occurs at the cathode (the right half-cell in the figure).
      * The cell potential, +0.46 V, in this case, results from the inherent differences in the nature of the materials used to make the two half-cells.
      * The salt bridge must be present to close (complete) the circuit and both an oxidation and reduction must occur for current to flow.
    
    There are many possible galvanic cells, so a shorthand notation is usually used to describe them. The  **cell notation** (sometimes called a cell diagram) provides information about the various species involved in the reaction. This notation also works for other types of cells. A vertical line, │, denotes a phase boundary and a double line, ‖, the salt bridge. Information about the anode is written to the left, followed by the anode solution, then the salt bridge (when present), then the cathode solution, and, finally, information about the cathode to the right. The cell notation for the galvanic cell in {'Figure_17_2_Galvanicel Figure 17.2.Galvanicel} is then
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>Cu</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>│</mo><msup><mrow><mtext>Cu</mtext></mrow><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mtext>, 1</mtext><mspace width="0.2em"/><mi>M</mi><mo stretchy="false">)</mo><mo>║</mo><msup><mrow><mtext>Ag</mtext></mrow><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mtext>, 1</mtext><mspace width="0.2em"/><mi>M</mi><mo stretchy="false">)</mo><mo>│</mo><mtext>Ag</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mrow></math>
    
    Note that spectator ions are not included and that the simplest form of each half-reaction was used. When known, the initial concentrations of the various ions are usually included.
    
    One of the simplest cells is the Daniell cell. It is possible to construct this battery by placing a copper electrode at the bottom of a jar and covering the metal with a copper sulfate solution. A zinc sulfate solution is floated on top of the copper sulfate solution; then a zinc electrode is placed in the zinc sulfate solution. Connecting the copper electrode to the zinc electrode allows an electric current to flow. This is an example of a cell without a salt bridge, and ions may flow across the interface between the two solutions.
    
    Some oxidation-reduction reactions involve species that are poor conductors of electricity, and so an electrode is used that does not participate in the reactions. Frequently, the electrode is platinum, gold, or graphite, all of which are inert to many chemical reactions. One such system is shown in {'Figure_17_2_Oxidareduc Figure 17.2.Oxidareduc}. Magnesium undergoes oxidation at the anode on the left in the figure and hydrogen ions undergo reduction at the cathode on the right. The reaction may be summarized as
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mtable columnalign="left"><mtr/><mtr><mtd><munder accentunder="true"><mtable columnalign="left"><mtr><mtd><mtext>oxidation:</mtext><mspace width="4.1em"/><mtext>Mg</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msup><mtext>Mg</mtext><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>2e</mtext><mtext>−</mtext></msup></mtd></mtr><mtr><mtd><mtext>reduction:</mtext><mspace width="0.2em"/><msup><mtext>2H</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>2e</mtext><mtext>−</mtext></msup><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo></mtd></mtr></mtable><mo stretchy="true">¯</mo></munder></mtd></mtr><mtr><mtd><mtext>overall:</mtext><mspace width="0.45em"/><mtext>Mg</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>2H</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msup><mtext>Mg</mtext><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo></mtd></mtr></mtable></math>
    
    The cell used an inert platinum wire for the cathode, so the cell notation is
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>Mg</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>│</mo><mspace width="0.2em"/><msup><mrow><mtext>Mg</mtext></mrow><mrow><mn>2+</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>║</mo><msup><mtext>H</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>│</mo><msub><mtext>H</mtext><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mo>│</mo><mtext>Pt</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo></mrow></math>
    
    The magnesium electrode is an  **active electrode** because it participates in the oxidation-reduction reaction.  **Inert electrodes**, like the platinum electrode in {'Figure_17_2_Oxidareduc Figure 17.2.Oxidareduc}, do not participate in the oxidation-reduction reaction and are present so that current can flow through the cell. Platinum or gold generally make good inert electrodes because they are chemically unreactive.
    
    
            

  apply FullText

  ---
    16_2_0
    16_2_1

  path FullText
    step
      --
        16_2_0
    step
      --
        16_2_1

    