
/ Transformers
story 23_7
  >
     **Transformers** do what their name implies—they transform voltages from one value to another (The term voltage is used rather than emf, because transformers have internal resistance). For example, many cell phones, laptops, video games, and power tools and small appliances have a transformer built into their plug-in unit (like that in {'Figure_24_7_1 Figure 24.7.1}) that changes 120 V or 240 V AC into whatever voltage the device uses. Transformers are also used at several points in the power distribution systems, such as illustrated in {'Figure_24_7_2 Figure 24.7.2}. Power is sent long distances at high voltages, because less current is required for a given amount of power, and this means less line loss, as was discussed previously. But high voltages pose greater hazards, so that transformers are employed to produce lower voltage at the user’s location.
    
    
            
    
    
            
    
    The type of transformer considered in this text—see {'Figure_24_7_3 Figure 24.7.3}—is based on Faraday’s law of induction and is very similar in construction to the apparatus Faraday used to demonstrate magnetic fields could cause currents. The two coils are called the  *primary* and  *secondary coils*. In normal use, the input voltage is placed on the primary, and the secondary produces the transformed output voltage. Not only does the iron core trap the magnetic field created by the primary coil, its magnetization increases the field strength. Since the input voltage is AC, a time-varying magnetic flux is sent to the secondary, inducing its AC output voltage.
    
    
            
    
    For the simple transformer shown in {'Figure_24_7_3 Figure 24.7.3}, the output voltage <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>V</mi><mrow><mtext>s</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V rSub &#123; size 8&#123;s&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> depends almost entirely on the input voltage <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>V</mi><mrow><mtext>p</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V rSub &#123; size 8&#123;p&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> and the ratio of the number of loops in the primary and secondary coils. Faraday’s law of induction for the secondary coil gives its induced output voltage <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>V</mi><mrow><mtext>s</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V rSub &#123; size 8&#123;s&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> to be
    
    <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mml:mrow xmlns:mml="http://www.w3.org/1998/Math/MathML"><mrow><mrow><mrow><msub><mi>V</mi><mrow><mtext>s</mtext></mrow></msub><mo stretchy="false">=</mo><mrow><mo stretchy="false">−</mo><msub><mi>N</mi><mrow><mtext>s</mtext></mrow></msub></mrow></mrow><mfrac><mrow><mn>Δ</mn><mi>Φ</mi></mrow><mrow><mn>Δ</mn><mi>t</mi></mrow></mfrac></mrow></mrow><mrow><mtext>,</mtext></mrow></mml:mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V rSub &#123; size 8&#123;s&#125; &#125; = - N rSub &#123; size 8&#123;s&#125; &#125;  &#123;  &#123;ΔΦ&#125;  over  &#123;Δt&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    where <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>N</mi><mrow><mtext>s</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;N rSub &#123; size 8&#123;s&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the number of loops in the secondary coil and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mtext>Δ</mtext><mi>Φ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;ΔΦ&#125; &#123;&#125;</annotation></semantics></math>/ <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mtext>Δ</mtext><mi>t</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Δt&#125; &#123;&#125;</annotation></semantics></math> is the rate of change of magnetic flux. Note that the output voltage equals the induced emf (<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mi>V</mi><mrow><mtext>s</mtext></mrow></msub><mo stretchy="false">=</mo><msub><mtext>emf</mtext><mrow><mtext>s</mtext></mrow></msub></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V rSub &#123; size 8&#123;s&#125; &#125; =&quot;emf&quot; rSub &#123; size 8&#123;s&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>), provided coil resistance is small (a reasonable assumption for transformers). The cross-sectional area of the coils is the same on either side, as is the magnetic field strength, and so 
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mtext>Δ</mtext><mi>Φ</mi></mrow><mo>/</mo><mtext>Δ</mtext><mi>t</mi></mrow><annotation encoding="StarMath 5.0"> size 12&#123;ΔΦ&#125; &#123;&#125;</annotation></semantics></math>
    
    
    
    is the same on either side. The input primary voltage <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>V</mi><mrow><mtext>p</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V rSub &#123; size 8&#123;p&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is also related to changing flux by
    
    <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mml:mrow xmlns:mml="http://www.w3.org/1998/Math/MathML"><mrow><mrow><mrow><msub><mi>V</mi><mrow><mi>p</mi></mrow></msub><mo stretchy="false">=</mo><mrow><mo stretchy="false">−</mo><msub><mi>N</mi><mrow><mtext>p</mtext></mrow></msub></mrow></mrow><mfrac><mrow><mn>Δ</mn><mi>Φ</mi></mrow><mrow><mn>Δ</mn><mi>t</mi></mrow></mfrac></mrow></mrow><mrow><mtext>.</mtext></mrow></mml:mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V rSub &#123; size 8&#123;p&#125; &#125; = - N rSub &#123; size 8&#123;p&#125; &#125;  &#123;  &#123;ΔΦ&#125;  over  &#123;Δt&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    The reason for this is a little more subtle. Lenz’s law tells us that the primary coil opposes the change in flux caused by the input voltage <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>V</mi><mrow><mtext>p</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;V rSub &#123; size 8&#123;p&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>, hence the minus sign (This is an example of  *self-inductance*, a topic to be explored in some detail in later sections). Assuming negligible coil resistance, Kirchhoff’s loop rule tells us that the induced emf exactly equals the input voltage. Taking the ratio of these last two equations yields a useful relationship:
    
    <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mml:mrow xmlns:mml="http://www.w3.org/1998/Math/MathML"><mrow><mrow><mfrac><msub><mi>V</mi><mrow><mtext>s</mtext></mrow></msub><msub><mi>V</mi><mrow><mtext>p</mtext></mrow></msub></mfrac><mo stretchy="false">=</mo><mfrac><msub><mi>N</mi><mrow><mtext>s</mtext></mrow></msub><msub><mi>N</mi><mrow><mtext>p</mtext></mrow></msub></mfrac></mrow></mrow><mrow><mtext>.</mtext></mrow></mml:mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;  &#123;V rSub &#123; size 8&#123;s&#125; &#125; &#125;  over  &#123;V rSub &#123; size 8&#123;p&#125; &#125; &#125; &#125; = &#123;  &#123;N rSub &#123; size 8&#123;s&#125; &#125; &#125;  over  &#123;N rSub &#123; size 8&#123;p&#125; &#125; &#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    This is known as the  **transformer equation**, and it simply states that the ratio of the secondary to primary voltages in a transformer equals the ratio of the number of loops in their coils.
    
    The output voltage of a transformer can be less than, greater than, or equal to the input voltage, depending on the ratio of the number of loops in their coils. Some transformers even provide a variable output by allowing connection to be made at different points on the secondary coil. A  **step-up transformer** is one that increases voltage, whereas a  **step-down transformer** decreases voltage. Assuming, as we have, that resistance is negligible, the electrical power output of a transformer equals its input. This is nearly true in practice—transformer efficiency often exceeds 99%. Equating the power input and output,
    
    <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mml:mrow xmlns:mml="http://www.w3.org/1998/Math/MathML"><mrow><mrow><mrow><msub><mi>P</mi><mrow><mtext>p</mtext></mrow></msub><mo stretchy="false">=</mo><msub><mi>I</mi><mrow><mtext>p</mtext></mrow></msub></mrow><mrow><msub><mi>V</mi><mrow><mtext>p</mtext></mrow></msub><mo stretchy="false">=</mo><msub><mi>I</mi><mrow><mtext>s</mtext></mrow></msub></mrow><mrow><msub><mi>V</mi><mrow><mtext>s</mtext></mrow></msub><mo stretchy="false">=</mo><msub><mi>P</mi><mrow><mtext>s</mtext></mrow></msub></mrow></mrow></mrow><mrow><mtext>.</mtext></mrow></mml:mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;P rSub &#123; size 8&#123;p&#125; &#125; =I rSub &#123; size 8&#123;p&#125; &#125; V rSub &#123; size 8&#123;p&#125; &#125; =I rSub &#123; size 8&#123;s&#125; &#125; V rSub &#123; size 8&#123;s&#125; &#125; =P rSub &#123; size 8&#123;s&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    Rearranging terms gives
    
    <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mml:mrow xmlns:mml="http://www.w3.org/1998/Math/MathML"><mrow><mrow><mfrac><msub><mi>V</mi><mrow><mtext>s</mtext></mrow></msub><msub><mi>V</mi><mrow><mtext>p</mtext></mrow></msub></mfrac><mo stretchy="false">=</mo><mfrac><msub><mi>I</mi><mrow><mtext>p</mtext></mrow></msub><msub><mi>I</mi><mrow><mtext>s</mtext></mrow></msub></mfrac></mrow></mrow><mrow><mtext>.</mtext></mrow></mml:mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;  &#123;V rSub &#123; size 8&#123;s&#125; &#125; &#125;  over  &#123;V rSub &#123; size 8&#123;p&#125; &#125; &#125; &#125; = &#123;  &#123;I rSub &#123; size 8&#123;p&#125; &#125; &#125;  over  &#123;I rSub &#123; size 8&#123;s&#125; &#125; &#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    Combining this with <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mfrac><msub><mi>V</mi><mrow><mtext>s</mtext></mrow></msub><msub><mi>V</mi><mrow><mtext>p</mtext></mrow></msub></mfrac><mo stretchy="false">=</mo><mfrac><msub><mi>N</mi><mrow><mtext>s</mtext></mrow></msub><msub><mi>N</mi><mrow><mtext>p</mtext></mrow></msub></mfrac></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;  &#123;V rSub &#123; size 8&#123;s&#125; &#125; &#125;  over  &#123;V rSub &#123; size 8&#123;p&#125; &#125; &#125; &#125; = &#123;  &#123;N rSub &#123; size 8&#123;s&#125; &#125; &#125;  over  &#123;N rSub &#123; size 8&#123;p&#125; &#125; &#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>, we find that
    
    <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mfrac>                    <msub>                      <mi>I</mi>                                              <mrow>                          <mtext>s</mtext>                        </mrow>                                          </msub>                    <msub>                      <mi>I</mi>                                              <mrow>                          <mtext>p</mtext>                        </mrow>                                          </msub>                  </mfrac>                  <mo stretchy="false">=</mo>                  <mfrac>                    <msub>                      <mi>N</mi>                                              <mrow>                          <mtext>p</mtext>                        </mrow>                                          </msub>                    <msub>                      <mi>N</mi>                                              <mrow>                          <mtext>s</mtext>                        </mrow>                                          </msub>                  </mfrac>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123; &#123;  &#123;I rSub &#123; size 8&#123;s&#125; &#125; &#125;  over  &#123;I rSub &#123; size 8&#123;p&#125; &#125; &#125; &#125; = &#123;  &#123;N rSub &#123; size 8&#123;p&#125; &#125; &#125;  over  &#123;N rSub &#123; size 8&#123;s&#125; &#125; &#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    is the relationship between the output and input currents of a transformer. So if voltage increases, current decreases. Conversely, if voltage decreases, current increases.
    
    The fact that transformers are based on Faraday’s law of induction makes it clear why we cannot use transformers to change DC voltages. If there is no change in primary voltage, there is no voltage induced in the secondary. One possibility is to connect DC to the primary coil through a switch. As the switch is opened and closed, the secondary produces a voltage like that in {'Figure_24_7_4 Figure 24.7.4}. This is not really a practical alternative, and AC is in common use wherever it is necessary to increase or decrease voltages.
    
    
            
    
    Transformers have many applications in electrical safety systems, which are discussed in <link:>.

  apply FullText

  ---
    23_7_0
    23_7_1

  path FullText
    step
      --
        23_7_0
    step
      --
        23_7_1

    