
/ Sound Intensity and Sound Level
story 17_3
  >
    
            
    
    In a quiet forest, you can sometimes hear a single leaf fall to the ground. After settling into bed, you may hear your blood pulsing through your ears. But when a passing motorist has his stereo turned up, you cannot even hear what the person next to you in your car is saying. We are all very familiar with the loudness of sounds and aware that they are related to how energetically the source is vibrating. In cartoons depicting a screaming person (or an animal making a loud noise), the cartoonist often shows an open mouth with a vibrating uvula, the hanging tissue at the back of the mouth, to suggest a loud sound coming from the throat {'Figure_18_3_1ab Figure 18.3.1ab}. High noise exposure is hazardous to hearing, and it is common for musicians to have hearing losses that are sufficiently severe that they interfere with the musicians’ abilities to perform. The relevant physical quantity is sound intensity, a concept that is valid for all sounds whether or not they are in the audible range.
    
    Intensity is defined to be the power per unit area carried by a wave. Power is the rate at which energy is transferred by the wave. In equation form,  **intensity** *I size 12&#123;I&#125; &#123;&#125;* is
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>I</mi><mo stretchy="false">=</mo><mfrac><mi>P</mi><mi>A</mi></mfrac></mrow><mo>,</mo></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I= &#123;  &#123;P&#125;  over  &#123;A&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    where <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>P</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;P&#125; &#123;&#125;</annotation></semantics></math> is the power through an area  *A size 12&#123;A&#125; &#123;&#125;*. The SI unit for  *I size 12&#123;I&#125; &#123;&#125;* is <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><msup><mn>W/m</mn><mn>2</mn></msup></mrow></semantics></math>. The intensity of a sound wave is related to its amplitude squared by the following relationship:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>I</mi><mo stretchy="false">=</mo><mfrac><msup><mrow><mo>(</mo><mn>Δ</mn><mi fontstyle="italic">p</mi><mo>)</mo></mrow><mn>2</mn></msup><mrow><mn>2</mn><mrow><msub><mi fontstyle="italic">ρv</mi><mn>w</mn></msub></mrow></mrow></mfrac></mrow><mo>.</mo></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I= &#123;  &#123; left (Δp right )&#125;  over  &#123;2 ital &quot;pv&quot; size 8&#123;m&#125;&#125; &#125;  rSup &#123;2&#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    Here <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mn>Δ</mn><mi fontstyle="italic">p</mi></mrow></mrow></semantics></math> is the pressure variation or pressure amplitude (half the difference between the maximum and minimum pressure in the sound wave) in units of pascals (Pa) or <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><msup><mn>N/m</mn><mn>2</mn></msup></mrow></semantics></math>. (We are using a lower case <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi fontstyle="italic">p</mi></mrow></mrow></semantics></math>  for pressure to distinguish it from power, denoted by  <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi fontstyle="italic">P</mi></mrow></mrow></semantics></math> above.) The energy (as kinetic energy 
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mfrac><mrow><msup><mi fontstyle="italic">mv</mi><mrow><mn>2</mn></mrow></msup></mrow><mn>2</mn></mfrac></mrow><mrow/></mrow></semantics></math>) of an oscillating element of air due to a traveling sound wave is proportional to its amplitude squared. In this equation, 
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>ρ</mi></mrow></mrow></semantics></math> is the density of the material in which the sound wave travels, in units of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><msup><mn>kg/m</mn><mn>3</mn></msup></mrow></semantics></math>, and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>v</mi><mrow><mn>w</mn></mrow></msub></mrow><mrow/></mrow></semantics></math> is the speed of sound in the medium, in units of m/s. The pressure variation is proportional to the amplitude of the oscillation, and so  *I size 12&#123;I&#125; &#123;&#125;* varies as <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mo stretchy="false">(</mo><mn>Δ</mn><mi fontstyle="italic">p</mi><msup><mo stretchy="false">)</mo><mrow><mn>2</mn></mrow></msup></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; \( Λp \)  rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> ({'Figure_18_3_1ab Figure 18.3.1ab}). This relationship is consistent with the fact that the sound wave is produced by some vibration; the greater its pressure amplitude, the more the air is compressed in the sound it creates.
    
    
            
    
    Sound intensity levels are quoted in decibels (dB) much more often than sound intensities in watts per meter squared. Decibels are the unit of choice in the scientific literature as well as in the popular media. The reasons for this choice of units are related to how we perceive sounds. How our ears perceive sound can be more accurately described by the logarithm of the intensity rather than directly to the intensity. The  **sound intensity level** **** *β size 12&#123;β&#125; &#123;&#125;* in decibels of a sound having an intensity <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mi>I</mi></mrow></semantics></math> in watts per meter squared is defined to be
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>β</mi><mspace width="0.25em"/><mrow><mfenced close=")" open="("><mtext>dB</mtext></mfenced><mo stretchy="false">=</mo><mtext>10</mtext></mrow><mspace width="0.25em"/><msub><mtext>log</mtext><mrow><mtext>10</mtext></mrow></msub><mfenced close=")" open="("><mfrac><mi>I</mi><msub><mi>I</mi><mrow><mn>0</mn></mrow></msub></mfrac></mfenced></mrow><mo>,</mo></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;β left (&quot;dB&quot; right )=&quot;10&quot;&quot;log&quot; rSub &#123; size 8&#123;&quot;10&quot;&#125; &#125;  left ( &#123;  &#123;I&#125;  over  &#123;I rSub &#123; size 8&#123;0&#125; &#125; &#125; &#125;  right )&#125; &#123;&#125;</annotation></semantics></math>
    
    where <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>I</mi><mrow><mn>0</mn></mrow></msub><mo stretchy="false">=</mo><msup><mtext>10</mtext><mrow><mrow><mtext>–12</mtext></mrow></mrow></msup></mrow><mspace width="0.25em"/><msup><mtext>W/m</mtext><mrow><mn>2</mn></mrow></msup></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I rSub &#123; size 8&#123;0&#125; &#125; =&quot;10&quot; rSup &#123; size 8&#123; - &quot;12&quot;&#125; &#125; &quot;W/m&quot; rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is a reference intensity. In particular, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>I</mi><mrow><mn>0</mn></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;I rSub &#123; size 8&#123;0&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is the lowest or threshold intensity of sound a person with normal hearing can perceive at a frequency of 1000 Hz. Sound intensity level is not the same as intensity. Because  *β size 12&#123;β&#125; &#123;&#125;* is defined in terms of a ratio, it is a unitless quantity telling you the  *level* of the sound relative to a fixed standard (<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mtext>10</mtext><mrow><mrow><mtext>–12</mtext></mrow></mrow></msup><mspace width="0.25em"/><msup><mtext>W/m</mtext><mrow><mn>2</mn></mrow></msup></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;10&quot; rSup &#123; size 8&#123; - &quot;12&quot;&#125; &#125; &quot;W/m&quot; rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>, in this case). The units of decibels (dB) are used to indicate this ratio is multiplied by 10 in its definition. The bel, upon which the decibel is based, is named for Alexander Graham Bell, the inventor of the telephone.
    
    
        
    
    The decibel level of a sound having the threshold intensity of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mtext>10</mtext><mrow><mrow><mo stretchy="false">–</mo><mtext>12</mtext></mrow></mrow></msup><mspace width="0.25em"/><msup><mtext>W/m</mtext><mrow><mn>2</mn></mrow></msup></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;10&quot; rSup &#123; size 8&#123; - &quot;12&quot;&#125; &#125; &quot;W/m&quot; rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mi>β</mi><mo stretchy="false">=</mo><mn>0</mn></mrow><mspace width="0.25em"/><mtext>dB</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;β=0&quot;dB&quot;&#125; &#123;&#125;</annotation></semantics></math>, because <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mtext>log</mtext><mrow><mtext>10</mtext></mrow></msub><mrow><mn>1</mn><mo stretchy="false">=</mo><mn>0</mn></mrow></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;log&quot; rSub &#123; size 8&#123;&quot;10&quot;&#125; &#125; 1=0&#125; &#123;&#125;</annotation></semantics></math>. That is, the threshold of hearing is 0 decibels.  gives levels in decibels and intensities in watts per meter squared for some familiar sounds.
    
    One of the more striking things about the intensities in  is that the intensity in watts per meter squared is quite small for most sounds. The ear is sensitive to as little as a trillionth of a watt per meter squared—even more impressive when you realize that the area of the eardrum is only about <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><msup><mn>1 cm</mn><mn>2</mn></msup></mrow></semantics></math>, so that only <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mtext>10</mtext><mrow><mrow><mo stretchy="false">–</mo><mtext>16</mtext></mrow></mrow></msup></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;10&quot; rSup &#123; size 8&#123; - &quot;16&quot;&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> W falls on it at the threshold of hearing! Air molecules in a sound wave of this intensity vibrate over a distance of less than one molecular diameter, and the gauge pressures involved are less than <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mtext>10</mtext><mrow><mrow><mo stretchy="false">–</mo><mn>9</mn></mrow></mrow></msup></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;10&quot; rSup &#123; size 8&#123; - 9&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> atm.
    
    Another impressive feature of the sounds in  is their numerical range. Sound intensity varies by a factor of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mtext>10</mtext><mrow><mtext>12</mtext></mrow></msup></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;10&quot; rSup &#123; size 8&#123;&quot;12&quot;&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> from threshold to a sound that causes damage in seconds. You are unaware of this tremendous range in sound intensity because how your ears respond can be described approximately as the logarithm of intensity. Thus, sound intensity levels in decibels fit your experience better than intensities in watts per meter squared. The decibel scale is also easier to relate to because most people are more accustomed to dealing with numbers such as 0, 53, or 120 than numbers such as <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mn>1</mn><mtext>.</mtext><mrow><mtext>00</mtext><mo stretchy="false">×</mo><msup><mtext>10</mtext><mrow><mrow><mo stretchy="false">–</mo><mtext>11</mtext></mrow></mrow></msup></mrow></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;1 &quot;.&quot; &quot;00&quot; times &quot;10&quot; rSup &#123; size 8&#123; - &quot;11&quot;&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>.
    
    One more observation readily verified by examining  or using <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>I</mi><mo stretchy="false">=</mo><msup><mfrac><mrow><mo>(</mo><mn>Δ</mn><mi fontstyle="italic">p</mi><mo>)</mo></mrow><mrow><mn>2</mn><msub><mrow><mtext fontstyle="italic">ρv</mtext></mrow><mrow><mtext>w</mtext></mrow></msub></mrow></mfrac><mn>2</mn></msup></mrow></mrow><mrow/></mrow></semantics></math> is that each factor of 10 in intensity corresponds to 10 dB. For example, a 90 dB sound compared with a 60 dB sound is 30 dB greater, or three factors of 10 (that is, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mtext>10</mtext><mrow><mn>3</mn></mrow></msup></mrow></mrow></semantics></math> times) as intense. Another example is that if one sound is <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mtext>10</mtext><mrow><mn>7</mn></mrow></msup></mrow></mrow></semantics></math> as intense as another, it is 70 dB higher. See .
    
    
        
    
    It should be noted at this point that there is another decibel scale in use, called the  **sound pressure level**, based on the ratio of the pressure amplitude to a reference pressure. This scale is used particularly in applications where sound travels in water. It is beyond the scope of most introductory texts to treat this scale because it is not commonly used for sounds in air, but it is important to note that very different decibel levels may be encountered when sound pressure levels are quoted. For example, ocean noise pollution produced by ships may be as great as 200 dB expressed in the sound pressure level, where the more familiar sound intensity level we use here would be something under 140 dB for the same sound.

  apply FullText

  ---
    17_3_0
    17_3_1

  / Sound Intensity and Sound Level - Full Text
  path FullText
    step
      --
        17_3_0
    step
      --
        17_3_1

    