
/ ATP: Adenosine Triphosphate
story 2_6_4
  >
    Even exergonic, energy-releasing reactions require a small amount of activation energy in order to proceed. However, consider endergonic reactions, which require much more energy input, because their products have more free energy than their reactants. Within the cell, where does energy to power such reactions come from? The answer lies with an energy-supplying molecule called  **adenosine triphosphate**, or  **ATP**. ATP is a small, relatively simple molecule ({'Figure_6_4_1 Figure 6.4.1}), but within some of its bonds, it contains the potential for a quick burst of energy that can be harnessed to perform cellular work. This molecule can be thought of as the primary energy currency of cells in much the same way that money is the currency that people exchange for things they need. ATP is used to power the majority of energy-requiring cellular reactions.
    
    
            
    
    As its name suggests, adenosine triphosphate is comprised of adenosine bound to three phosphate groups ({'Figure_6_4_1 Figure 6.4.1}). Adenosine is a nucleoside consisting of the nitrogenous base adenine and a five-carbon sugar, ribose. The three phosphate groups, in order of closest to furthest from the ribose sugar, are labeled alpha, beta, and gamma. Together, these chemical groups constitute an energy powerhouse. However, not all bonds within this molecule exist in a particularly high-energy state. Both bonds that link the phosphates are equally high-energy bonds ( **phosphoanhydride bonds**)  that, when broken, release sufficient energy to power a variety of cellular reactions and processes. These high-energy bonds are the bonds between the second and third (or beta and gamma) phosphate groups and between the first and second phosphate groups. The reason that these bonds are considered “high-energy” is because the products of such bond breaking—adenosine diphosphate (ADP) and one inorganic phosphate group (P<sub>i</sub>)—have considerably lower free energy than the reactants: ATP and a water molecule. Because this reaction takes place with the use of a water molecule, it is considered a hydrolysis reaction. In other words, ATP is hydrolyzed into ADP in the following reaction:
    
    <math display="block" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics>        <mrow>            <mtext>ATP</mtext><mo>+</mo><msub>                <mtext>H</mtext>                <mtext>2</mtext>            </msub>            <mtext>O</mtext><mo stretchy="false">→</mo><mtext>ADP</mtext><mo>+</mo><msub>                <mtext>P</mtext>                <mtext>i</mtext>            </msub>            <mo>+</mo><mtext>free energy</mtext>        </mrow><annotation encoding="StarMath 5.0">size 12&#123;&#123;ATP&#125; + H rSub &#123; size 8&#123;2&#125; &#125; O  ADP + P rSub &#123; size 8&#123;i&#125;&#125; + &#123;free energy&#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    Like most chemical reactions, the hydrolysis of ATP to ADP is reversible. The reverse reaction regenerates ATP from ADP + P<sub>i</sub>. Indeed, cells rely on the regeneration of ATP just as people rely on the regeneration of spent money through some sort of income. Since ATP hydrolysis releases energy, ATP regeneration must require an input of free energy. The formation of ATP is expressed in this equation:
    
    <math display="block" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics>        <mrow>            <mtext>ADP</mtext><mo>+</mo><msub>                <mtext>P</mtext>                <mtext>i</mtext>            </msub>            <mo>+</mo><mtext>free energy</mtext><mo stretchy="false">→</mo><mtext>ATP</mtext><mo>+</mo><msub>                <mtext>H</mtext>                <mtext>2</mtext>            </msub>            <mtext>O</mtext>        </mrow><annotation encoding="StarMath 5.0">size 12&#123;&#123;ATP&#125; + H rSub &#123; size 8&#123;2&#125; &#125; O  ADP + P rSub &#123; size 8&#123;i&#125;&#125; + &#123;free energy&#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    Two prominent questions remain with regard to the use of ATP as an energy source. Exactly how much free energy is released with the hydrolysis of ATP, and how is that free energy used to do cellular work? The calculated ∆G  for the hydrolysis of one mole of ATP into ADP and P<sub>i</sub> is −7.3 kcal/mole (−30.5 kJ/mol). Since this calculation is true under standard conditions, it would be expected that a different value exists under cellular conditions. In fact, the ∆G  for the hydrolysis of one mole of ATP in a living cell is almost double the value at standard conditions: –14 kcal/mol (−57 kJ/mol).
    
    ATP is a highly unstable molecule. Unless quickly used to perform work, ATP spontaneously dissociates into ADP + P<sub>i</sub>, and the free energy released during this process is lost as heat. The second question posed above, that is, how the energy released by ATP hydrolysis is used to perform work inside the cell, depends on a strategy called energy coupling. Cells couple the exergonic reaction of ATP hydrolysis with endergonic reactions, allowing them to proceed. One example of energy coupling using ATP involves a transmembrane ion pump that is extremely important for cellular function. This sodium-potassium pump (Na<sup>+</sup>/K<sup>+</sup> pump) drives sodium out of the cell and potassium into the cell (). A large percentage of a cell’s ATP is spent powering this pump, because cellular processes bring a great deal of sodium into the cell and potassium out of the cell. The pump works constantly to stabilize cellular concentrations of sodium and potassium. In order for the pump to turn one cycle (exporting three Na+ ions and importing two K<sup>+</sup> ions), one molecule of ATP must be hydrolyzed. When ATP is hydrolyzed, its gamma phosphate doesn’t simply float away, but is actually transferred onto the pump protein. This process of a phosphate group binding to a molecule is called phosphorylation. As with most cases of ATP hydrolysis, a phosphate from ATP is transferred onto another molecule. In a phosphorylated state, the Na<sup>+</sup>/K<sup>+</sup> pump has more free energy and is triggered to undergo a conformational change. This change allows it to release Na<sup>+</sup> to the outside of the cell. It then binds extracellular K<sup>+</sup>, which, through another conformational change, causes the phosphate to detach from the pump. This release of phosphate triggers the K<sup>+</sup> to be released to the inside of the cell. Essentially, the energy released from the hydrolysis of ATP is coupled with the energy required to power the pump and transport Na<sup>+</sup> and K<sup>+</sup> ions. ATP performs cellular work using this basic form of energy coupling through phosphorylation.
    
    Often during cellular metabolic reactions, such as the synthesis and breakdown of nutrients, certain molecules must be altered slightly in their conformation to become substrates for the next step in the reaction series. One example is during the very first steps of cellular respiration, when a molecule of the sugar glucose is broken down in the process of glycolysis. In the first step of this process, ATP is required for the phosphorylation of glucose, creating a high-energy but unstable intermediate. This phosphorylation reaction powers a conformational change that allows the phosphorylated glucose molecule to be converted to the phosphorylated sugar fructose. Fructose is a necessary intermediate for glycolysis to move forward. Here, the exergonic reaction of ATP hydrolysis is coupled with the endergonic reaction of converting glucose into a phosphorylated intermediate in the pathway. Once again, the energy released by breaking a phosphate bond within ATP was used for the phosphorylation of another molecule, creating an unstable intermediate and powering an important conformational change.

  apply FullText

  ---
    2_6_4_0
    2_6_4_1

  path FullText
    step
      --
        2_6_4_0
    step
      --
        2_6_4_1

    