/ August, 2020
feed August2020
  -
    'Boulware_et_al_08_06_2020


  #

  // Immunogenicity and safety of a recombinant adenovirus type-5-vectored COVID-19 vaccine in healthy adults aged 18 years or older: a randomised, double-blind, placebo-controlled, phase 2 trial
  doi: https://doi.org/10.1016/S0140-6736(20)31605-6
  ref 'Zhu_et_al_08_15_2020
    head = 508 eligible participants consented to participate in the trial and were randomly assigned to receive the vaccine (1 × 1011 viral particles n=253; 5 × 1010 viral particles n=129) or placebo (n=126). In the 1 × 1011 and 5 × 1010 viral particles dose groups, the RBD-specific ELISA antibodies peaked, with seroconversion rates at 96% and 97%, respectively, at day 28.

    > Background
      This is the first randomised controlled trial for assessment of the immunogenicity and safety of a candidate non-replicating adenovirus type-5 (Ad5)-vectored COVID-19 vaccine, aiming to determine an appropriate dose of the candidate vaccine for an efficacy study.
    > Methods
      This randomised, double-blind, placebo-controlled, phase 2 trial of the Ad5-vectored COVID-19 vaccine was done in a single centre in Wuhan, China. Healthy adults aged 18 years or older, who were HIV-negative and previous severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) infection-free, were eligible to participate and were randomly assigned to receive the vaccine at a dose of 1 × 1011 viral particles per mL or 5 × 1010 viral particles per mL, or placebo. Investigators allocated participants at a ratio of 2:1:1 to receive a single injection intramuscularly in the arm. The randomisation list (block size 4) was generated by an independent statistician. Participants, investigators, and staff undertaking laboratory analyses were masked to group allocation. The primary endpoints for immunogenicity were the geometric mean titres (GMTs) of specific ELISA antibody responses to the receptor binding domain (RBD) and neutralising antibody responses at day 28. The primary endpoint for safety evaluation was the incidence of adverse reactions within 14 days. All recruited participants who received at least one dose were included in the primary and safety analyses. This study is registered with ClinicalTrials.gov, NCT04341389.
    >  Findings
      603 volunteers were recruited and screened for eligibility between April 11 and 16, 2020. 508 eligible participants (50% male; mean age 39·7 years, SD 12·5) consented to participate in the trial and were randomly assigned to receive the vaccine (1 × 1011 viral particles n=253; 5 × 1010 viral particles n=129) or placebo (n=126). In the 1 × 1011 and 5 × 1010 viral particles dose groups, the RBD-specific ELISA antibodies peaked at 656·5 (95% CI 575·2–749·2) and 571·0 (467·6–697·3), with seroconversion rates at 96% (95% CI 93–98) and 97% (92–99), respectively, at day 28. Both doses of the vaccine induced significant neutralising antibody responses to live SARS-CoV-2, with GMTs of 19·5 (95% CI 16·8–22·7) and 18·3 (14·4–23·3) in participants receiving 1 × 1011 and 5 × 1010 viral particles, respectively. Specific interferon γ enzyme-linked immunospot assay responses post vaccination were observed in 227 (90%, 95% CI 85–93) of 253 and 113 (88%, 81–92) of 129 participants in the 1 × 1011 and 5 × 1010 viral particles dose groups, respectively. Solicited adverse reactions were reported by 183 (72%) of 253 and 96 (74%) of 129 participants in the 1 × 1011 and 5 × 1010 viral particles dose groups, respectively. Severe adverse reactions were reported by 24 (9%) participants in the 1 × 1011 viral particles dose group and one (1%) participant in the 5 × 1010 viral particles dose group. No serious adverse reactions were documented.
    > Interpretation
      The Ad5-vectored COVID-19 vaccine at 5 × 1010 viral particles is safe, and induced significant immune responses in the majority of recipients after a single immunisation.


    - quotes
      !a
      !b

    / August, 2020 - The Lancet
    quote !a = Severe adverse reactions were reported by 24 (9%) participants in the 1 × 1011 viral particles dose group and one (1%) participant in the 5 × 1010 viral particles dose group.

    / August, 2020 - The Lancet
    quote !b = The Ad5-vectored COVID-19 vaccine at 5 × 1010 viral particles is safe, and induced significant immune responses in the majority of recipients after a single immunisation.

  // Safety and immunogenicity of the ChAdOx1 nCoV-19 vaccine against SARS-CoV-2: a preliminary report of a phase 1/2, single-blind, randomised controlled trial
  doi: https://dx.doi.org/10.1016%2FS0140-6736(20)31604-4
  ref 'Folegatti_et_al_08_15_2020
    head = ChAdOx1 nCoV-19 showed an acceptable safety profile, and homologous boosting increased antibody responses. These results, together with the induction of both humoral and cellular immune responses, support large-scale evaluation of this candidate vaccine in an ongoing phase 3 programme.

    > Background
      The pandemic of severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) might be curtailed by vaccination. We assessed the safety, reactogenicity, and immunogenicity of a viral vectored coronavirus vaccine that expresses the spike protein of SARS-CoV-2.

    > Methods
      We did a phase 1/2, single-blind, randomised controlled trial in five trial sites in the UK of a chimpanzee adenovirus-vectored vaccine (ChAdOx1 nCoV-19) expressing the SARS-CoV-2 spike protein compared with a meningococcal conjugate vaccine (MenACWY) as control. Healthy adults aged 18–55 years with no history of laboratory confirmed SARS-CoV-2 infection or of COVID-19-like symptoms were randomly assigned (1:1) to receive ChAdOx1 nCoV-19 at a dose of 5 × 1010 viral particles or MenACWY as a single intramuscular injection. A protocol amendment in two of the five sites allowed prophylactic paracetamol to be administered before vaccination. Ten participants assigned to a non-randomised, unblinded ChAdOx1 nCoV-19 prime-boost group received a two-dose schedule, with the booster vaccine administered 28 days after the first dose. Humoral responses at baseline and following vaccination were assessed using a standardised total IgG ELISA against trimeric SARS-CoV-2 spike protein, a muliplexed immunoassay, three live SARS-CoV-2 neutralisation assays (a 50% plaque reduction neutralisation assay [PRNT50]; a microneutralisation assay [MNA50, MNA80, and MNA90]; and Marburg VN), and a pseudovirus neutralisation assay. Cellular responses were assessed using an ex-vivo interferon-γ enzyme-linked immunospot assay. The co-primary outcomes are to assess efficacy, as measured by cases of symptomatic virologically confirmed COVID-19, and safety, as measured by the occurrence of serious adverse events. Analyses were done by group allocation in participants who received the vaccine. Safety was assessed over 28 days after vaccination. Here, we report the preliminary findings on safety, reactogenicity, and cellular and humoral immune responses. The study is ongoing, and was registered at ISRCTN, 15281137, and ClinicalTrials.gov, NCT04324606.

    >  Findings
      Between April 23 and May 21, 2020, 1077 participants were enrolled and assigned to receive either ChAdOx1 nCoV-19 (n=543) or MenACWY (n=534), ten of whom were enrolled in the non-randomised ChAdOx1 nCoV-19 prime-boost group. Local and systemic reactions were more common in the ChAdOx1 nCoV-19 group and many were reduced by use of prophylactic paracetamol, including pain, feeling feverish, chills, muscle ache, headache, and malaise (all p<0·05). There were no serious adverse events related to ChAdOx1 nCoV-19. In the ChAdOx1 nCoV-19 group, spike-specific T-cell responses peaked on day 14 (median 856 spot-forming cells per million peripheral blood mononuclear cells, IQR 493–1802; n=43). Anti-spike IgG responses rose by day 28 (median 157 ELISA units [EU], 96–317; n=127), and were boosted following a second dose (639 EU, 360–792; n=10). Neutralising antibody responses against SARS-CoV-2 were detected in 32 (91%) of 35 participants after a single dose when measured in MNA80 and in 35 (100%) participants when measured in PRNT50. After a booster dose, all participants had neutralising activity (nine of nine in MNA80 at day 42 and ten of ten in Marburg VN on day 56). Neutralising antibody responses correlated strongly with antibody levels measured by ELISA (R2=0·67 by Marburg VN; p<0·001).

    >  Interpretation
      ChAdOx1 nCoV-19 showed an acceptable safety profile, and homologous boosting increased antibody responses. These results, together with the induction of both humoral and cellular immune responses, support large-scale evaluation of this candidate vaccine in an ongoing phase 3 programme.

    - quotes
      !a
      !b

    / August, 2020 - Lancet
    quote !a = Local and systemic reactions were more common in the ChAdOx1 nCoV-19 group and many were reduced by use of prophylactic paracetamol, including pain, feeling feverish, chills, muscle ache, headache, and malaise. There were no serious adverse events related to ChAdOx1 nCoV-19.

    / August, 2020 - Lancet
    quote !b = ChAdOx1 nCoV-19 group, spike-specific T-cell responses peaked on day 14. Anti-spike IgG responses rose by day 28 and were boosted following a second dose. Neutralising antibody responses against SARS-CoV-2 were detected in 32 (91%) of 35 participants after a single dose


  # Phizer Vaccine
  // Phase I/II study of COVID-19 RNA vaccine BNT162b1 in adults
  doi: https://doi.org/10.1038/s41586-020-2639-4
  ref 'Mulligan_et_al_08_12_2020
    head = The RNA-based SARS-CoV-2 vaccine candidate BNT162b1, which was administered as 10-μg, 30-μg or 100-μg doses in healthy adults (18–55 years of age), exhibited a tolerability and safety profile consistent with those previously observed for mRNA-based vaccines. A clear dose-level response in elicited neutralizing titres was observed after doses 1 and 2 in participants with a particularly steep dose response between the 10 μg and 30 μg dose levels.

    > Abstract
      In March 2020, the World Health Organization (WHO) declared coronavirus disease 2019 (COVID-19), which is caused by severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2)1, a pandemic. With rapidly accumulating numbers of cases and deaths reported globally2, a vaccine is urgently needed. Here we report the available safety, tolerability and immunogenicity data from an ongoing placebo-controlled, observer-blinded dose-escalation study (ClinicalTrials.gov identifier NCT04368728) among 45 healthy adults (18–55 years of age), who were randomized to receive 2 doses—separated by 21 days—of 10 μg, 30 μg or 100 μg of BNT162b1. BNT162b1 is a lipid-nanoparticle-formulated, nucleoside-modified mRNA vaccine that encodes the trimerized receptor-binding domain (RBD) of the spike glycoprotein of SARS-CoV-2. Local reactions and systemic events were dose-dependent, generally mild to moderate, and transient. A second vaccination with 100 μg was not administered because of the increased reactogenicity and a lack of meaningfully increased immunogenicity after a single dose compared with the 30-μg dose. RBD-binding IgG concentrations and SARS-CoV-2 neutralizing titres in sera increased with dose level and after a second dose. Geometric mean neutralizing titres reached 1.9–4.6-fold that of a panel of COVID-19 convalescent human sera, which were obtained at least 14 days after a positive SARS-CoV-2 PCR. These results support further evaluation of this mRNA vaccine candidate.

    - quotes
      !a

    / August, 2020 - Nature
    quote !a = The most-common systemic events reported in the 7 days after each vaccination in both BNT162b1 and placebo groups were mild to moderate fatigue and headache. In addition, chills, muscle pain and joint pain were reported by individuals who received BNT162b1 but not by individuals who received the placebo.



  # Reinfection
  // Clinical, immunological and virological characterization of COVID-19 patients that test re-positive for SARS-CoV-2 by RT-PCR
  doi: https://doi.org/10.1016/j.ebiom.2020.102960
  ref 'Lu_et_al_08_24_2020
    head = SARS-CoV-2 RNA was detected. Among 619 discharged COVID-19 cases, 87 re-tested as SARS-CoV-2 positive in circumstances of social isolation. Re-positive cases exhibited similar neutralization antibodies to other COVID-19 cases. No infectious strain could be obtained by culture and no full-length viral genomes could be sequenced from re-positive cases.

    > Background
      Some COVID-19 cases test positive again for SARS-CoV-2 RNA following negative test results and discharge, raising questions about the meaning of virus detection. Better characterization of re-positive cases is urgently needed.
    >  Methods
      Clinical data were obtained through Guangdong's COVID-19 surveillance network. Neutralization antibody titre was determined using microneutralization assays. Potential infectivity of clinical samples was evaluated by cell inoculation. SARS-CoV-2 RNA was detected using three different RT-PCR kits and multiplex PCR with nanopore sequencing.
    > Findings
      Among 619 discharged COVID-19 cases, 87 re-tested as SARS-CoV-2 positive in circumstances of social isolation. All re-positive cases had mild or moderate symptoms at initial diagnosis and were younger on average (median, 28). Re-positive cases (n = 59) exhibited similar neutralization antibodies (NAbs) titre distributions to other COVID-19 cases (n = 218) tested here. No infectious strain could be obtained by culture and no full-length viral genomes could be sequenced from re-positive cases.
    >  Interpretation
      Re-positive SARS-CoV-2 cases do not appear to be caused by active reinfection and were identified in ~14% of discharged cases. A robust NAb response and potential virus genome degradation were detected in almost all re-positive cases, suggesting a substantially lower transmission risk, especially through respiratory routes.

    - quotes
      !a

    / August, 2020 - The Lancet
    quote !a = Re-positive SARS-CoV-2 cases do not appear to be caused by active reinfection. A robust NAb response and potential virus genome degradation were detected in almost all re-positive cases, suggesting a substantially lower transmission risk, especially through respiratory routes.


  # Antigen
  // Clinical Evaluation of Self-Collected Saliva by Quantitative Reverse Transcription-PCR (RT-qPCR), Direct RT-qPCR, Reverse Transcription-Loop-Mediated Isothermal Amplification, and a Rapid Antigen Test To Diagnose COVID-19
  doi: https://doi.org/10.1128/jcm.01438-20
  ref 'Nagura-Ikeda_et_al_08_24_2020
    head = The RT-qPCR LDT, a cobas SARS-CoV-2 high-throughput system, direct RT-qPCR kits (except for one commercial kit), and RT-LAMP showed sufficient sensitivities in clinical use to be selectively used in clinical settings and facilities. The rapid antigen test alone is not recommended for an initial COVID-19 diagnosis because of its low sensitivity.

    > Abstract
      The clinical performances of six molecular diagnostic tests and a rapid antigen test for severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) were clinically evaluated for the diagnosis of coronavirus disease 2019 (COVID-19) in self-collected saliva. Saliva samples from 103 patients with laboratory-confirmed COVID-19 (15 asymptomatic and 88 symptomatic) were collected on the day of hospital admission. SARS-CoV-2 RNA in saliva was detected using a quantitative reverse transcription-PCR (RT-qPCR) laboratory-developed test (LDT), a cobas SARS-CoV-2 high-throughput system, three direct RT-qPCR kits, and reverse transcription-loop-mediated isothermal amplification (RT-LAMP). The viral antigen was detected by a rapid antigen immunochromatographic assay. Of the 103 samples, viral RNA was detected in 50.5 to 81.6% of the specimens by molecular diagnostic tests, and an antigen was detected in 11.7% of the specimens by the rapid antigen test. Viral RNA was detected at significantly higher percentages (65.6 to 93.4%) in specimens collected within 9 days of symptom onset than in specimens collected after at least 10 days of symptoms (22.2 to 66.7%) and in specimens collected from asymptomatic patients (40.0 to 66.7%). Self-collected saliva is an alternative specimen option for diagnosing COVID-19. The RT-qPCR LDT, a cobas SARS-CoV-2 high-throughput system, direct RT-qPCR kits (except for one commercial kit), and RT-LAMP showed sufficient sensitivities in clinical use to be selectively used in clinical settings and facilities. The rapid antigen test alone is not recommended for an initial COVID-19 diagnosis because of its low sensitivity.


    / August, 2020 - J Clin Microbiol
    quote !a =


  # Ct value
  // Clinical Course and Molecular Viral Shedding Among Asymptomatic and Symptomatic Patients With SARS-CoV-2 Infection in a Community Treatment Center in the Republic of Korea
  doi: https://doi.org/10.1001/jamainternmed.2020.3862
  ref 'Lee_et_al_08_06_2020
    head = In this cohort study of symptomatic and asymptomatic patients with SARS-CoV-2 infection ,the Ct values in asymptomatic patients were similar to those in symptomatic patients. Isolation of asymptomatic patients may be necessary to control the spread of SARS-CoV-2.

    > Question
      Are there viral load differences between asymptomatic and symptomatic patients with severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) infection?

    > Findings
      In this cohort study that included 303 patients with SARS-CoV-2 infection isolated in a community treatment center in the Republic of Korea, 110 (36.3%) were asymptomatic at the time of isolation and 21 of these (19.1%) developed symptoms during isolation. The cycle threshold values of reverse transcription–polymerase chain reaction for SARS-CoV-2 in asymptomatic patients were similar to those in symptomatic patients.

    > Meaning
      Many individuals with SARS-CoV-2 infection remained asymptomatic for a prolonged period, and viral load was similar to that in symptomatic patients; therefore, isolation of infected persons should be performed regardless of symptoms.

    / August, 2020 - JAMA Intern Med.
    quote !a =

  # Rapid Testing - Antigen
  // Rapid, point-of-care antigen and molecular-based tests for diagnosis of SARS-CoV-2 infection
  doi: https://doi.org/10.1002/14651858.cd013705
  ref 'Dinnes_et_al_08_26_2020
    head = This review identifies early-stage evaluations of point-of-care tests for detecting SARS-CoV-2 infection, largely based on remnant laboratory samples.  Rapid tests have the potential to be used to inform triage of RT-PCR use, allowing earlier detection of those testing positive, but the evidence currently is not strong enough to determine how useful they are in clinical practice.

    > Background:
      Severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) and the resulting COVID-19 pandemic present important diagnostic challenges. Several diagnostic strategies are available to identify or rule out current infection, identify people in need of care escalation, or to test for past infection and immune response. Point-of-care antigen and molecular tests to detect current SARS-CoV-2 infection have the potential to allow earlier detection and isolation of confirmed cases compared to laboratory-based diagnostic methods, with the aim of reducing household and community transmission.

    > Objectives:
      To assess the diagnostic accuracy of point-of-care antigen and molecular-based tests to determine if a person presenting in the community or in primary or secondary care has current SARS-CoV-2 infection.

    > Search methods:
      On 25 May 2020 we undertook electronic searches in the Cochrane COVID-19 Study Register and the COVID-19 Living Evidence Database from the University of Bern, which is updated daily with published articles from PubMed and Embase and with preprints from medRxiv and bioRxiv. In addition, we checked repositories of COVID-19 publications. We did not apply any language restrictions.

    > Selection criteria:
      We included studies of people with suspected current SARS-CoV-2 infection, known to have, or not to have SARS-CoV-2 infection, or where tests were used to screen for infection. We included test accuracy studies of any design that evaluated antigen or molecular tests suitable for a point-of-care setting (minimal equipment, sample preparation, and biosafety requirements, with results available within two hours of sample collection). We included all reference standards to define the presence or absence of SARS-CoV-2 (including reverse transcription polymerase chain reaction (RT-PCR) tests and established clinical diagnostic criteria).

    > Data collection and analysis:
      Two review authors independently screened studies and resolved any disagreements by discussion with a third review author. One review author independently extracted study characteristics, which were checked by a second review author. Two review authors independently extracted 2x2 contingency table data and assessed risk of bias and applicability of the studies using the QUADAS-2 tool. We present sensitivity and specificity, with 95% confidence intervals (CIs), for each test using paired forest plots. We pooled data using the bivariate hierarchical model separately for antigen and molecular-based tests, with simplifications when few studies were available. We tabulated available data by test manufacturer.

    > Main results:
      We included 22 publications reporting on a total of 18 study cohorts with 3198 unique samples, of which 1775 had confirmed SARS-CoV-2 infection. Ten studies took place in North America, two in South America, four in Europe, one in China and one was conducted internationally. We identified data for eight commercial tests (four antigen and four molecular) and one in-house antigen test. Five of the studies included were only available as preprints. We did not find any studies at low risk of bias for all quality domains and had concerns about applicability of results across all studies. We judged patient selection to be at high risk of bias in 50% of the studies because of deliberate over-sampling of samples with confirmed COVID-19 infection and unclear in seven out of 18 studies because of poor reporting. Sixteen (89%) studies used only a single, negative RT-PCR to confirm the absence of COVID-19 infection, risking missing infection. There was a lack of information on blinding of index test (n = 11), and around participant exclusions from analyses (n = 10). We did not observe differences in methodological quality between antigen and molecular test evaluations. Antigen tests Sensitivity varied considerably across studies (from 0% to 94%): the average sensitivity was 56.2% (95% CI 29.5 to 79.8%) and average specificity was 99.5% (95% CI 98.1% to 99.9%; based on 8 evaluations in 5 studies on 943 samples). Data for individual antigen tests were limited with no more than two studies for any test. Rapid molecular assays Sensitivity showed less variation compared to antigen tests (from 68% to 100%), average sensitivity was 95.2% (95% CI 86.7% to 98.3%) and specificity 98.9% (95% CI 97.3% to 99.5%) based on 13 evaluations in 11 studies of on 2255 samples. Predicted values based on a hypothetical cohort of 1000 people with suspected COVID-19 infection (with a prevalence of 10%) result in 105 positive test results including 10 false positives (positive predictive value 90%), and 895 negative results including 5 false negatives (negative predictive value 99%). Individual tests We calculated pooled results of individual tests for ID NOW (Abbott Laboratories) (5 evaluations) and Xpert Xpress (Cepheid Inc) (6 evaluations). Summary sensitivity for the Xpert Xpress assay (99.4%, 95% CI 98.0% to 99.8%) was 22.6 (95% CI 18.8 to 26.3) percentage points higher than that of ID NOW (76.8%, (95% CI 72.9% to 80.3%), whilst the specificity of Xpert Xpress (96.8%, 95% CI 90.6% to 99.0%) was marginally lower than ID NOW (99.6%, 95% CI 98.4% to 99.9%; a difference of -2.8% (95% CI -6.4 to 0.8))
    > AUTHORS' CONCLUSIONS
      This review identifies early-stage evaluations of point-of-care tests for detecting SARS-CoV-2 infection, largely based on remnant laboratory samples. The findings currently have limited applicability, as we are uncertain whether tests will perform in the same way in clinical practice, and according to symptoms of COVID-19, duration of symptoms, or in asymptomatic people. Rapid tests have the potential to be used to inform triage of RT-PCR use, allowing earlier detection of those testing positive, but the evidence currently is not strong enough to determine how useful they are in clinical practice. Prospective and comparative evaluations of rapid tests for COVID-19 infection in clinically relevant settings are urgently needed. Studies should recruit consecutive series of eligible participants, including both those presenting for testing due to symptoms and asymptomatic people who may have come into contact with confirmed cases. Studies should clearly describe symptomatic status and document time from symptom onset or time since exposure. Point-of-care tests must be conducted on samples according to manufacturer instructions for use and be conducted at the point of care. Any future research study report should conform to the Standards for Reporting of Diagnostic Accuracy (STARD) guideline.


    / August, 2020 - Cochrane Database Syst Rev
    quote !a =

  # VitaminD - RCT
  // Effect of calcifediol treatment and best available therapy versus best available therapy on intensive care unit admission and mortality among patients hospitalized for COVID-19: A pilot randomized clinical study
  doi: https://dx.doi.org/10.1016%2Fj.jsbmb.2020.105751
  ref 'Castillo_et_al_08_29_2020
    head = Administration of a high dose of Calcifediol or 25-hydroxyvitamin D, a main metabolite of vitamin D endocrine system, significantly reduced the need for ICU treatment of patients requiring hospitalization due to proven COVID-19.

    > Objective
      The vitamin D endocrine system may have a variety of actions on cells and tissues involved in COVID-19 progression especially by decreasing the Acute Respiratory Distress Syndrome. Calcifediol can rapidly increase serum 25OHD concentration. We therefore evaluated the effect of calcifediol treatment, on Intensive Care Unit Admission and Mortality rate among Spanish patients hospitalized for COVID-19.

    > Design
      Parallel pilot randomized open label, double-masked clinical trial.

    > Setting
      University hospital setting (Reina Sofia University Hospital, Córdoba Spain.)

    > Participants
      76 consecutive patients hospitalized with COVID-19 infection, clinical picture of acute respiratory infection, confirmed by a radiographic pattern of viral pneumonia and by a positive SARS-CoV-2 PCR with CURB65 severity scale (recommending hospital admission in case of total score > 1).

    >  Procedures
      All hospitalized patients received as best available therapy the same standard care, (per hospital protocol), of a combination of hydroxychloroquine (400 mg every 12 h on the first day, and 200 mg every 12 h for the following 5 days), azithromycin (500 mg orally for 5 days. Eligible patients were allocated at a 2 calcifediol:1 no calcifediol ratio through electronic randomization on the day of admission to take oral calcifediol (0.532 mg), or not. Patients in the calcifediol treatment group continued with oral calcifediol (0.266 mg) on day 3 and 7, and then weekly until discharge or ICU admission. Outcomes of effectiveness included rate of ICU admission and deaths.

    > Results
      Of 50 patients treated with calcifediol, one required admission to the ICU (2%), while of 26 untreated patients, 13 required admission (50 %) p value X2 Fischer test p < 0.001. Univariate Risk Estimate Odds Ratio for ICU in patients with Calcifediol treatment versus without Calcifediol treatment: 0.02 (95 %CI 0.002−0.17). Multivariate Risk Estimate Odds Ratio for ICU in patients with Calcifediol treatment vs Without Calcifediol treatment ICU (adjusting by Hypertension and T2DM): 0.03 (95 %CI: 0.003-0.25). Of the patients treated with calcifediol, none died, and all were discharged, without complications. The 13 patients not treated with calcifediol, who were not admitted to the ICU, were discharged. Of the 13 patients admitted to the ICU, two died and the remaining 11 were discharged.

    > Conclusion
      Our pilot study demonstrated that administration of a high dose of Calcifediol or 25-hydroxyvitamin D, a main metabolite of vitamin D endocrine system, significantly reduced the need for ICU treatment of patients requiring hospitalization due to proven COVID-19. Calcifediol seems to be able to reduce severity of the disease, but larger trials with groups properly matched will be required to show a definitive answer.

    / August, 2020 - J Steroid Biochem Mol Biol
    quote !a =

  # Why Face Mask
  // Mask or no mask for COVID-19: A public health and market study
  doi: https://doi.org/10.1371/journal.pone.0237691
  ref 'Li_et_al_08_14_2020
    head = Our study combines mathematical modeling and existing scientific evidence to evaluate the potential impact of the utilization of normal medical masks in public to combat the COVID-19 pandemic. We recognize our study provides a projection based only on currently available data and estimates potential probabilities.

    > Abstract
      Efficient strategies to contain the coronavirus disease 2019 (COVID-19) pandemic are peremptory to relieve the negatively impacted public health and global economy, with the full scope yet to unfold. In the absence of highly effective drugs, vaccines, and abundant medical resources, many measures are used to manage the infection rate and avoid exhausting limited hospital resources. Wearing masks is among the non-pharmaceutical intervention (NPI) measures that could be effectively implemented at a minimum cost and without dramatically disrupting social practices. The mask-wearing guidelines vary significantly across countries. Regardless of the debates in the medical community and the global mask production shortage, more countries and regions are moving forward with recommendations or mandates to wear masks in public. Our study combines mathematical modeling and existing scientific evidence to evaluate the potential impact of the utilization of normal medical masks in public to combat the COVID-19 pandemic. We consider three key factors that contribute to the effectiveness of wearing a quality mask in reducing the transmission risk, including the mask aerosol reduction rate, mask population coverage, and mask availability. We first simulate the impact of these three factors on the virus reproduction number and infection attack rate in a general population. Using the intervened viral transmission route by wearing a mask, we further model the impact of mask-wearing on the epidemic curve with increasing mask awareness and availability. Our study indicates that wearing a face mask can be effectively combined with social distancing to flatten the epidemic curve. Wearing a mask presents a rational way to implement as an NPI to combat COVID-19. We recognize our study provides a projection based only on currently available data and estimates potential probabilities. As such, our model warrants further validation studies.

    - quotes
      !a

    / Plos One — August 14, 2020
    quote !a = Our study indicates that wearing a face mask can be effectively combined with social distancing to flatten the epidemic curve. Wearing a mask presents a rational way to implement as an NPI to combat COVID-19. We recognize our study provides a projection based only on currently available data and estimates potential probabilities.

  # Dust Mask
  // Evaluation of wearing comfort of dust masks
  doi: https://doi.org/10.1371/journal.pone.0237848
  ref 'Choi_et_al_08_20_2020
    head = This study presents a technique to quantify the wearing comfort of dust masks. We present a comprehensive evaluation of the performance of dust masks in terms of not only the filtering performance but also the wearing comfort. Our study suggests some design principles for dust mask filters, auxiliary electric fans, and check valves.

    > Abstract
      Dust masks are widely used to prevent the inhalation of particulate matter into the human respiratory organs in polluted air environments. The filter of a dust mask inherently obstructs the natural respiratory air flows, and this flow resistance is mainly responsible for the discomfort experienced when wearing a dust mask. In atmospheric conditions seriously contaminated with fine dust, it is recommended that common citizens wear a dust mask in their everyday lives, yet many people are reluctant to wear a dust mask owing to the discomfort experienced when wearing it for a long time. Understanding of physical reasons for the discomfort is thus crucial in designing a dust mask, but remains far from clear. This study presents a technique to quantify the wearing comfort of dust masks. By developing a respiration simulator to measure the pressure loss across a dust mask, we assessed the energy costs to overcome flow resistance when breathing through various types of dust masks. The energy cost for a single inhalation varies with the mask type in a range between 0 and 10 mJ. We compared the results with the survey results of 40 people about the wearing comfort of the dust masks, which revealed that the wearing comfort crucially depends on the energy cost required for air inhalation though the dust mask. Using the measured energy cost during inhalation as a parameter to quantify the wearing comfort, we present a comprehensive evaluation of the performance of dust masks in terms of not only the filtering performance but also the wearing comfort. Our study suggests some design principles for dust mask filters, auxiliary electric fans, and check valves.

    - quotes
      !a

    / Comfort of masks is dependent on the breathability
    quote !a = We compared the results with the survey results of 40 people about the wearing comfort of the dust masks, which revealed that the wearing comfort crucially depends on the energy cost required for air inhalation though the dust mask.
    / Design principles for good Masks
    quote !b = A raise in the internal pressure is also advantageous for limiting a leakage flow, and as a result improves the filtration ratio. In addition, we discuss the desirable power level of the electric fan. Zero energy cost during inhalation corresponds to breathing without a dust mask, and negative work can indicate forced inhalation. Accordingly, we conjecture that excessively negative work can produce an unpleasant feeling, and a fan power equal to the energy cost for breathing through the dust mask is thus most desirable for wearing comfort and for saving electric energy.

  # Mask Filters, design, New method for developing mask
  // Salt coatings functionalize inert membranes into high-performing filters against infectious respiratory diseases
  doi: https://doi.org/10.1038/s41598-020-70623-9
  ref 'Rubino_et_al_08_17_2020
    head = Conventional technologies have several drawbacks (i.e., cross-infection risk, filtration efficiency improvements limited by difficulty in breathing, and no safe reusability). We developed an antimicrobial respiratory protective system with high filtering performance and improved breathability levels compared to regular masks.

    > Abstract
      Respiratory protection is key in infection prevention of airborne diseases, as highlighted by the COVID-19 pandemic for instance. Conventional technologies have several drawbacks (i.e., cross-infection risk, filtration efficiency improvements limited by difficulty in breathing, and no safe reusability), which have yet to be addressed in a single device. Here, we report the development of a filter overcoming the major technical challenges of respiratory protective devices. Large-pore membranes, offering high breathability but low bacteria capture, were functionalized to have a uniform salt layer on the fibers. The salt-functionalized membranes achieved high filtration efficiency as opposed to the bare membrane, with differences of up to 48%, while maintaining high breathability (> 60% increase compared to commercial surgical masks even for the thickest salt filters tested). The salt-functionalized filters quickly killed Gram-positive and Gram-negative bacteria aerosols in vitro, with CFU reductions observed as early as within 5 min, and in vivo by causing structural damage due to salt recrystallization. The salt coatings retained the pathogen inactivation capability at harsh environmental conditions (37 °C and a relative humidity of 70%, 80% and 90%). Combination of these properties in one filter will lead to the production of an effective device, comprehensibly mitigating infection transmission globally.

    - quotes
      !a

    / Salt coatings for filtration
    quote !a = We developed an antimicrobial respiratory protective system with high filtering performance and improved breathability levels compared to regular masks. The salt-functionalized membranes achieved high filtration efficiency as opposed to the bare membrane, with differences of up to 48%, while maintaining high breathability. The salt coatings retained the pathogen inactivation capability at harsh environmental conditions. Combination of these properties in one filter will lead to the production of an effective device, comprehensibly mitigating infection transmission globally.

  # facemask, efficacy, surgical mask, n95 mask, Coughing and Sneezing
  // Universal trends in human cough airflows at large distances
  doi: https://doi.org/10.1063/5.0021666
  ref 'Simha_et_al_08_25_2020
    head = Voluntary coughs from five test subjects were analyzed. Without masks, the airflow from coughs is capable of traversing at least 1.5 m–3.0 m. A disposable surgical mask greatly reduces this distance to between 0.5 m and 1.5 m. N95 masks have the best effectiveness and completely contain the horizontal spread to between 0.1 m and 0.25 m.

    > ABSTRACT
      Coughs are one of the primary means of transmission of diseases such as influenza and SARS-CoV-2 (COVID-19). Disease spreading occurs by the expulsion of pathogen containing aerosol droplets. Fine droplets can pass through layers of masks and are carried away by the exhaled airflow unlike larger droplets that settle down due to gravity. Hence, it is important to quantitatively assess the maximum distance of travel of typical human coughs with and without different types of masks. Even though near field data are available near the mouth, far field data are scarce. In this study, the schlieren method that is a highly sensitive, non-intrusive flow visualization technique is used. It can directly image weak density gradients produced by coughs. An assessment of different methods of covering the mouth while coughing is arrived at by using observations from high speed schlieren images. The effectiveness of coughing into the elbow is examined. The velocity of propagation of coughs and the distance of propagation with and without masks are quantified. It is also found that normalizing the distance–velocity profiles causes all the data to collapse onto a universal non-dimensional curve irrespective of the usage of different types of masks or test subjects. Visualization of cough flow fields and analysis of experimental data reveal that the flow physics is governed by the propagation of viscous vortex rings.


    - quotes
      !a
      !b

    / August, 2020 - Physics of Fluids
    quote !a =  Long sleeve that covers the elbow substantially reduces the ejection of the cough airflow into the environment compared to coughing into a bare elbow.

    / N95 and medical mask comparison
    quote !b =  A disposable surgical mask greatly reduces this distance to between 0.5 m and 1.5 m. N95 masks have the best effectiveness and completely contain the horizontal spread to between 0.1 m and 0.25 m.

  # risks, Facemask, Exercising
  // COVID-19: Electrophysiological mechanisms underlying sudden cardiac death during exercise with facemasks
  doi: https://doi.org/10.1016/j.mehy.2020.110177
  ref 'Lee_et_al_08_11_2020
    head = Exercise with facemasks may increase the risk of ventricular tachycardia/ventricular fibrillation (VT/VF) leading to SCD via the development of acute and/or intermittent hypoxia and hypercapnia. We discuss the potential underlying mechanisms including increases in adrenergic stimulation and oxidative stress leading to electrophysiological abnormalities that promote arrhythmias via non-reentrant and reentrant mechanisms.

    > Abstract
      The mandatory use of facemasks is a public health measure implemented by various countries in response to the novel coronavirus disease 19 (COVID-19) pandemic. However, there have been case reports of sudden cardiac death (SCD) with the wearing of facemasks during exercise. In this paper, we hypothesize that exercise with facemasks may increase the risk of ventricular tachycardia/ventricular fibrillation (VT/VF) leading to SCD via the development of acute and/or intermittent hypoxia and hypercapnia. We discuss the potential underlying mechanisms including increases in adrenergic stimulation and oxidative stress leading to electrophysiological abnormalities that promote arrhythmias via non-reentrant and reentrant mechanisms. Given the interplay of multiple variables contributing to the increased arrhythmic risk, we advise avoidance of a facemask during high intensity exercise, or if wearing of a mask is mandatory, exercise intensity should remain low to avoid precipitation of lethal arrhythmias. However, we cannot exclude the possibility of an arrhythmic substrate even with low intensity exercise especially in those with established chronic cardiovascular disease in whom baseline electrophysiological abnormalities may be found.


    / Exercising with facemasks is risky
    quote !a = Exercise with facemasks may increase the risk of ventricular tachycardia/ventricular fibrillation (VT/VF) leading to SCD via the development of acute and/or intermittent hypoxia and hypercapnia. We discuss the potential underlying mechanisms including increases in adrenergic stimulation and oxidative stress leading to electrophysiological abnormalities that promote arrhythmias via non-reentrant and reentrant mechanisms.
    # this needs to be rewritten without the jargon



  # Decontamination of Mask, reuse,
  // Microwave- and Heat-Based Decontamination of N95 Filtering Facepiece Respirators: A Systematic Review
  doi: https://doi.org/10.1016/j.jhin.2020.08.016
  ref 'Gertsman_et_al_08_22_2020
    head = Microwave irradiation and heat may be safe and effective viral decontamination options for N95 FFR reuse during critical shortages. The evidence does not support autoclaving or high-heat (>90oC) approaches. Physical degradation may be an issue for certain mask models, and more real-world evidence on fit is needed.

    > Background
      In pandemics such as COVID-19, shortages of personal protective equipment are common. One solution may be to decontaminate equipment such as facemasks for reuse.

    > Aim
      To collect and synthesize existing information on decontamination of N95 filtering facepiece respirators (FFRs) using microwave and heat-based treatments, with special attention to impact on mask function (aerosol penetration, airflow resistance), fit, and physical traits.

    > Methods
      A systematic review (PROSPERO CRD42020177036) of literature available from Medline, Embase, Global Health, and other sources was conducted. Records were screened independently by two reviewers, and data was extracted from studies that reported on effects of microwave- or heat-based decontamination on N95 FFR performance, fit, physical traits, and/or reductions in microbial load.

    > Findings
      Thirteen studies were included that used dry/moist microwave irradiation, heat, or autoclaving. All treatment types reduced pathogen load by a log10 reduction factor of at least three when applied for sufficient duration (>30s microwave, >60 min dry heat), with most studies assessing viral pathogens. Mask function (aerosol penetration <5% and airflow resistance <25mmH2O) was preserved after all treatments except autoclaving. Fit was maintained for most N95 models, though all treatment types caused observable physical damage to at least one model.

    > Conclusions
      Microwave irradiation and heat may be safe and effective viral decontamination options for N95 FFR reuse during critical shortages. The evidence does not support autoclaving or high-heat (>90oC) approaches. Physical degradation may be an issue for certain mask models, and more real-world evidence on fit is needed.

    / N95 mask reuse
    quote !a = Microwave irradiation and heat may be safe and effective viral decontamination options for N95 FFR reuse during critical shortages. The evidence does not support autoclaving or high-heat (>90oC) approaches. Physical degradation may be an issue for certain mask models, and more real-world evidence on fit is needed.


  # Face Mask, Oncology Clinics, risks,
  // Face masks in radiation oncology clinics: based on evidence or source of mistakes?
  doi: https://doi.org/10.1007/s12032-020-01403-8
  ref 'Klement_et_al_08_01_2020
    head = Potential risks associated with wearing masks, such as the risk of confounding patients, outweigh any benefits of such a policy for which evidence of protection from COVID-19 is generally weak. For asymptomatic patients, wearing masks in addition to hygiene standards will not provide additional protection of others and should be cautioned against.

    > Abstract
      We here express our concern about a general decree to let patients wear face masks in radiation oncology clinics. We believe that potential risks associated with wearing masks, such as the risk of confounding patients, outweigh any benefits of such a policy for which evidence of protection from COVID-19 is generally weak. For asymptomatic patients, wearing masks in addition to hygiene standards will not provide additional protection of others and should be cautioned against.

    / Potential risks of wearing facemasks outweigh benefits in radiation oncology clinics
    quote !a = We believe that potential risks associated with wearing masks, such as the risk of confounding patients, outweigh any benefits of such a policy for which evidence of protection from Covid-19 is generally weak. For asymptomatic patients, wearing masks in addition to hygiene standards will not provide additional protection of others and should be cautioned against.

  # Low Mortality with mask adoption - Face Mask
  // Association of country-wide coronavirus mortality with demographics, testing, lockdowns, and public wearing of masks. Update August 4, 2020.
  doi: https://doi.org/10.1101/2020.05.22.20109231
  ref 'Leffler_et_al_08_05_2020
    head = We hypothesized that in countries where mask use was either an accepted cultural norm or favored by government policies on a national level, the per-capita mortality might be reduced, as compared with countries which did not advocate masks.

    > Purpose
      To determine sources of variation between countries in per-capita mortality from COVID-19 (caused by the SARS-CoV-2 virus).

    > Methods.
      Potential predictors of per-capita coronavirus-related mortality in 200 countries by May 9, 2020 were examined, including age, sex, obesity prevalence, temperature, urbanization, smoking, duration of infection, lockdowns, viral testing, contact tracing policies, and public mask-wearing norms and policies. Multivariable linear regression analysis was performed.

    > Results
      In univariate analyses, the prevalence of smoking, per-capita gross domestic product, urbanization, and colder average country temperature were positively associated with coronavirus-related mortality. In a multivariable analysis of 196 countries, the duration of infection in the country, and the proportion of the population 60 years of age or older were positively associated with per-capita mortality, while duration of mask-wearing by the public was negatively associated with mortality (all p<0.001). International travel restrictions and a lower prevalence of obesity were independently associated with mortality in a model which controlled for testing policy. Internal lockdown requirements and viral testing policies and levels were not associated with mortality. The association of contact tracing policy with mortality approached statistical significance (p=0.06). In countries with cultural norms or government policies supporting public mask-wearing, per-capita coronavirus mortality increased on average by just 15.8% each week, as compared with 62.1% each week in remaining countries.

    > Conclusions
      Societal norms and government policies supporting the wearing of masks by the public, as well as international travel controls, are independently associated with lower per-capita mortality from COVID-19.

    - quotes
      !a
      !b
      !c
      !d

    / ASTMH — October 26, 2020
    quote !a = Internal lockdown requirements and viral testing policies and levels were not associated with mortality.

    / ASTMH — October 26, 2020
    quote !b = The association of contact tracing policy with mortality approached statistical significance (p=0.06).

    / ASTMH — October 26, 2020
    quote !c = In countries with cultural norms or government policies supporting public mask-wearing, per-capita coronavirus mortality increased on average by just 15.8% each week, as compared with 62.1% each week in remaining countries.

    / ASTMH — October 26, 2020
    quote !d = Societal norms and government policies supporting the wearing of masks by the public, as well as international travel controls, are independently associated with lower per-capita mortality from COVID-19.



  # Hydroxychloroquine
  // Low-dose Hydroxychloroquine Therapy and Mortality in Hospitalized Patients with COVID-19: A Nationwide Observational Study of 8075 Participants
  doi: https://doi.org/10.1016/j.ijantimicag.2020.106144
  ref 'PharmD_et_al_08_24_2020
    head = Compared to supportive care only, low-dose HCQ monotherapy was independently associated with lower mortality in hospitalized patients with COVID-19 diagnosed and treated early or later after symptom onset.

    > Background
      Hydroxychloroquine (HCQ) has been largely used and investigated as therapy of COVID-19 across various settings, at total dose usually ranging from 2400 mg to 9600 mg. In Belgium, off-label use of low-dose HCQ (2400 mg in total over five days) was recommended for hospitalized patients with COVID-19.

    > Methods
      We conducted a retrospective analysis of in-hospital mortality in the Belgian national COVID-19 hospital surveillance data. Patients treated either with HCQ alone and supportive care (HCQ group) were compared to patients treated with supportive care only (no-HCQ group) using a competing risks proportional hazards regression with discharge alive as competing risk, adjusted for demographic and clinical features with robust standard errors.

    > Results
      Of 8075 patients with complete discharge data on 24th of May and diagnosed before the 1st of May, 4542 received HCQ in monotherapy and 3533 were in the no-HCQ group. Death was reported in 804/4542 (17.7%) and 957/3533 (27.1%), respectively. In the multivariable analysis, the mortality was lower in the HCQ group compared to the no-HCQ group (adjusted hazard ratio [HR] 0.684, 95% confidence interval [CI] 0.617–0.758). Compared to the no-HCQ group, mortality in the HCQ group was reduced both in patients diagnosed ≤ 5 days (n=3975) and > 5 days (n=3487) after symptom onset (adjusted HR 0.701, 95% CI 0.617–0.796 and adjusted HR 0.647, 95% CI 0.525–0.797, respectively).

    > Conclusions
      Compared to supportive care only, low-dose HCQ monotherapy was independently associated with lower mortality in hospitalized patients with COVID-19 diagnosed and treated early or later after symptom onset.

    / August, 2020 - International Journal of Antimicrobial Agents
    quote !a =


  # Airborne
  @@WilliamRawlinson
  // Respiratory virus RNA is detectable in airborne and droplet particles
  doi: https://doi.org/10.1002/jmv.23698
  ref 'Gralton_et_al_08_19_2013
    head = Individuals with symptomatic respiratory viral infections produce both large and small particles carrying viral RNA on coughing and breathing.

    > Abstract
      Aerosol transmission routes of respiratory viruses have been classified by the WHO on the basis of equilibrium particle size. Droplet transmission is associated with particles sized >5 µm in diameter and airborne transmission is associated with particles sized ≤5 µm in diameter. Current infection control measures for respiratory viruses are directed at preventing droplet transmission, although epidemiological evidence suggests concurrent airborne transmission also occurs. Understanding the size of particles carrying viruses can be used to inform infection control procedures and therefore reduce virus transmission. This study determined the size of particles carrying respiratory viral RNA produced on coughing and breathing by 12 adults and 41 children with symptomatic respiratory infections. A modified six-stage Andersen Sampler collected expelled particles. Each stage was washed to recover samples for viral RNA extraction. Influenza A and B, parainfluenza 1, 2 and 3, respiratory syncytial virus (RSV), human metapneumovirus and human rhinoviruses (hRV) were detected using RT-PCR. On breathing, 58% of participants produced large particles (>5 µm) containing viral RNA and 80% produced small particles (≤5 µm) carrying viral RNA. On coughing, 57% of participants produced large particles containing viral RNA and 82% produced small particles containing viral RNA. Forty five percent of participants produced samples positive for hRV viral RNA and 26% of participants produced samples positive for viral RNA from parainfluenza viruses. This study demonstrates that individuals with symptomatic respiratory viral infections produce both large and small particles carrying viral RNA on coughing and breathing.

    - quotes
      !a

    / August, 2013 - J Med Virol.
    quote !a =

  # Airborne Context
  // The role of particle size in experimental air-borne infection.
  doi: https://doi.org/10.1093/oxfordjournals.aje.a119459
  ref 'Sonkin_et_al_05_01_1951
    head = With increasing B.M.D. (bacterial median diameter) the Ct required to produce infections of the lower respiratory tract increased much more steeply than the Ct required to give infection of the upper respiratory tract.

    > Abstract :
      Groups of mice were exposed to bacterial clouds obtained by spraying cultures of a Group C streptococcus or a Type 1 pneumococcus from a radial jet atomizer. The size of the bacteria-carrying particles was altered by adjustment of the atomizer and by incorporation of various amounts of glycerol in the spray suspension. The animals were exposed in a chamber through which the infected air was passing, and the air was sampled with a cascade impactor and an impinger in series to determine the " bacterial median diameter " (B.M.D.) of the inhaled particles. The dose of bacteria to which the animals were exposed was expressed as the product of the bacterial concentration in the air and the time of exposure (Ct), and the LCt50 was the dose that gave rise to fatal infections in 50 per cent. of mice.
      With the Group C streptococcus the LCt50 increased with increase in the B.M.D. In one series of experiments the LCtBO was 6×103 when the B.M.D. was 0.97 µ, and 1 × 108 with a B.M.D. of 12.0 µ. Small particles were necessary to produce lung lesions, but with all but the largest-particle clouds, lung lesions were produced more readily than upper respiratory tract lesions. With increasing B.M.D. the Ct required to produce infections of the lower respiratory tract increased much more steeply than the Ct required to give infection of the upper respiratory tract.

    / May, 1951 - American Journal of Hygiene
    quote !a =

  # Mitigatin
  // Associations between Wearing Masks, Washing Hands, and Social Distancing Practices, and Risk of COVID-19 Infection in Public: A Cohort-Based Case-Control Study in Thailand
  doi: https://dx.doi.org/10.2139/ssrn.3633162
  ref 'Doung-ngern_et_al_08_14_2020
    head = Our findings support consistently wearing masks, washing hands, and social distancing in public to protect against COVID-19 infections. Combining measures could substantially reduce infections in Thailand.


    > Background:
      Effectiveness of personal protective measure against COVID-19 infection is largely unknown.

    > Methods:
      We conducted a retrospective case-control study, using a cohort of contact tracing records in Thailand. A total of 1,050 asymptomatic contacts of COVID-19 patients between 1 and 31 March 2020 were retrospectively interviewed by phone about their protective measures against COVID-19 infection. Cases were defined as asymptomatic contacts who were diagnosed with COVID-19 by 21 April 2020. Multilevel mixed-effect logistic regression models were used

    > Findings:
      Overall, 211 (20%) were diagnosed with COVID-19 by 21 Apr 2020 (case group) while 839 (80%) were not (control group). Fourteen percent of cases (29/210) and 24% of controls (198/823) reported wearing either non-medical or medical masks all the time during the contact period. Wearing masks all the time (adjusted odds ratio [aOR] 0.23; 95%CI 0.09-0.60) was independently associated with lower risk of COVID-19 infection compared to not wearing masks, while wearing masks sometimes (aOR 0.87; 95%CI 0.41-1.84) was not. Shortest distance of contact >1 meter (aOR 0.15; 95%CI 0.04-0.63), duration of close contact ≤15 minutes (aOR 0.24; 95%CI 0.07-0.90) and washing hands often (aOR 0.33; 95%CI 0.13-0.87) were significantly associated with lower risk of infection. Sharing a cigarette (aOR 3.47; 95%CI 1.09-11.02) was associated with higher risk of infection. Those who wore masks all the time were more likely to wash hands and practice social distancing. We estimated that if everyone wore a mask all the time, washed hands often, did not share a dish, cup or cigarette, maintained distances >1 meter and spent ≤15 minutes with close contacts, cases would have been reduced by 84%.

    > Interpretation:
      Our findings support consistently wearing masks, washing hands, and social distancing in public to protect against COVID-19 infections. Combining measures could substantially reduce infections in Thailand.


    / August, 2020 - SSRN
    quote !a =

  # Ventilation - Air conditioning system - Public Policy
  // Air conditioning system usage and SARS-CoV-2 transmission dynamics in Iran
  doi: https://dx.doi.org/10.1016%2Fj.mehy.2020.110164
  ref 'RezaPourkarim_et_al_08_03_2020
    head = Based on the current evidence and the pattern of the epidemic, we believe that cooling systems could contribute to the spread of SARS-CoV-2 in Iran.

    - quotes
      !a

    / August, 2020 - Med Hypotheses
    quote !a = Besides creating air circulation in closed environments, these systems also reduce air humidity, which promotes the spread of virus-laden micro-droplets.


  # Side effects Hydroxychloroquine
  // Safety of hydroxychloroquine in COVID-19 and other diseases: a systematic review and meta-analysis of 53 randomized trials
  doi: https://doi.org/10.1007/s00228-020-02962-5
  ref 'Chen_et_al_08_11_2020
    head = We identified 53 eligible studies involving 5496 patients. HCQ is associated with more total AEs (Adverse Effects), gastrointestinal AEs, and skin and subcutaneous tissue AEs compared with placebo or no intervention in the overall population.

    > Objectives
      The purpose of this study was to evaluate the safety of HCQ in the treatment of COVID-19 and other diseases by performing a systematic review and meta-analysis.

    > Methods
      Randomized controlled trials (RCTs) reporting the safety of HCQ in PubMed, Embase, and Cochrane Library were retrieved starting from the establishment of the database till June 5, 2020. Literature screening, data extraction, and assessment of risk bias were performed independently by two reviewers.

    > Results
      We identified 53 eligible studies involving 5496 patients. The meta-analysis indicated that the risk of adverse effects (AEs) in the HCQ group was significantly increased compared with that in the control group (RD 0.05, 95%CI, 0.02 to 0.07, P = 0.0002), and the difference was also statistically significant in the COVID-19 subgroup (RD 0.15, 95%CI, 0.07 to 0.23, P = 0.0002) as well as in the subgroup for other diseases (RD 0.03, 95%CI, 0.01 to 0.04, P = 0.003).

    > Conclusions
      HCQ is associated with a high total risk of AEs compared with the placebo or no intervention in the overall population. Given the small number of COVID-19 participants included, we should be cautious regarding the conclusion stating that HCQ is linked with an increase incidence of AEs in patients with COVID-19, which we hope to confirm in the future through well-designed and larger sample size studies.

    - quotes
      !a
      !b

    / August, 2020 - European Journal of Clinical Pharmacology
    quote !a =  The risks of gastrointestinal AEs, skin and subcutaneous tissue disorders AEs, and treatment discontinuation due to AEs in the HCQ group were higher than in the control group. It is worth mentioning that patients treated with HCQ did not have a significantly increased risk of ophthalmic AEs, cardiac AEs, and total SAEs compared to those who were not treated with HCQ.

    / August, 2020 - European Journal of Clinical Pharmacology
    quote !b = There were two SAEs reported in the HCQ group, one being erythema multiforme and the other one being acute generalized erythematous pustulosis, while none were reported in the control group. Previous studies revealed that skin ADRs generally occurred 5~14 days after the beginning of HCQ therapy, and the rash was characterized as lichen-like, urticaria or simply rash. Additionally, the symptoms were generally mild, which could be relieved after withdrawal of therapy


  # Nosocomial
  // Toilets dominate environmental detection of severe acute respiratory syndrome coronavirus 2 in a hospital
  doi: https://doi.org/10.1016/j.scitotenv.2020.141710
  ref 'Ding_et_al_08_15_2020
    head = 107 surface samples, 46 air samples, two exhaled condensate samples, and two expired air samples were collected within and beyond four three-bed isolation rooms. The fecal-derived aerosols in patients' toilets contained most of the detected SARS-CoV-2, highlighting the importance of surface and hand hygiene for intervention.

    > Abstract
      Respiratory and fecal aerosols play confirmed and suspected roles, respectively, in transmitting severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2). An extensive environmental sampling campaign of both toilet and non-toilet environments was performed in a dedicated hospital building for patients with coronavirus disease 2019 (COVID-19), and the associated environmental factors were analyzed. In total, 107 surface samples, 46 air samples, two exhaled condensate samples, and two expired air samples were collected within and beyond four three-bed isolation rooms. The data of the COVID-19 patients were collected. The building environmental design and the cleaning routines were reviewed. Field measurements of airflow and CO2 concentrations were conducted. The 107 surface samples comprised 37 from toilets, 34 from other surfaces in isolation rooms, and 36 from other surfaces outside the isolation rooms in the hospital. Four of these samples were positive, namely two ward door handles, one bathroom toilet seat cover, and one bathroom door handle. Three were weakly positive, namely one bathroom toilet seat, one bathroom washbasin tap lever, and one bathroom ceiling exhaust louver. Of the 46 air samples, one collected from a corridor was weakly positive. The two exhaled condensate samples and the two expired air samples were negative. The fecal-derived aerosols in patients' toilets contained most of the detected SARS-CoV-2 in the hospital, highlighting the importance of surface and hand hygiene for intervention.


    / August, 2020 - Science of The Total Environment
    quote !a =


  # Hydroxychloroquine
  // A Randomized Trial of Hydroxychloroquine as Postexposure Prophylaxis for Covid-19
  doi: https://doi.org/10.1056/NEJMoa2016638
  ref 'Boulware_et_al_08_06_2020
    head = After high-risk or moderate-risk exposure to Covid-19, hydroxychloroquine did not prevent illness compatible with Covid-19 or confirmed infection when used as postexposure prophylaxis within 4 days after exposure. Side effects were more common with hydroxychloroquine than with placebo, but no serious adverse reactions were reported.

    > BACKGROUND
      Coronavirus disease 2019 (Covid-19) occurs after exposure to severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2). For persons who are exposed, the standard of care is observation and quarantine. Whether hydroxychloroquine can prevent symptomatic infection after SARS-CoV-2 exposure is unknown.

    > METHODS
      We conducted a randomized, double-blind, placebo-controlled trial across the United States and parts of Canada testing hydroxychloroquine as postexposure prophylaxis. We enrolled adults who had household or occupational exposure to someone with confirmed Covid-19 at a distance of less than 6 ft for more than 10 minutes while wearing neither a face mask nor an eye shield (high-risk exposure) or while wearing a face mask but no eye shield (moderate-risk exposure). Within 4 days after exposure, we randomly assigned participants to receive either placebo or hydroxychloroquine (800 mg once, followed by 600 mg in 6 to 8 hours, then 600 mg daily for 4 additional days). The primary outcome was the incidence of either laboratory-confirmed Covid-19 or illness compatible with Covid-19 within 14 days.

    > RESULTS
      We enrolled 821 asymptomatic participants. Overall, 87.6% of the participants (719 of 821) reported a high-risk exposure to a confirmed Covid-19 contact. The incidence of new illness compatible with Covid-19 did not differ significantly between participants receiving hydroxychloroquine (49 of 414 [11.8%]) and those receiving placebo (58 of 407 [14.3%]); the absolute difference was −2.4 percentage points (95% confidence interval, −7.0 to 2.2; P=0.35). Side effects were more common with hydroxychloroquine than with placebo (40.1% vs. 16.8%), but no serious adverse reactions were reported.

    > CONCLUSIONS
      After high-risk or moderate-risk exposure to Covid-19, hydroxychloroquine did not prevent illness compatible with Covid-19 or confirmed infection when used as postexposure prophylaxis within 4 days after exposure.

    / August, 2020 - NEJM
    quote !a =
