
/ Fusion
story 32_5
  >
    While basking in the warmth of the summer sun, a student reads of the latest breakthrough in achieving sustained thermonuclear power and vaguely recalls hearing about the cold fusion controversy. The three are connected. The Sun’s energy is produced by nuclear fusion (see {'Figure_33_5_1a Figure 33.5.1a}). Thermonuclear power is the name given to the use of controlled nuclear fusion as an energy source. While research in the area of thermonuclear power is progressing, high temperatures and containment difficulties remain. The cold fusion controversy centered around unsubstantiated claims of practical fusion power at room temperatures.
    
    
            
    
     **Nuclear fusion** is a reaction in which two nuclei are combined, or  *fused*, to form a larger nucleus. We know that all nuclei have less mass than the sum of the masses of the protons and neutrons that form them. The missing mass times <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mi>c</mi><mrow><mn>2</mn></mrow></msup></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;c rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> equals the binding energy of the nucleus—the greater the binding energy, the greater the missing mass. We also know that <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>BE</mtext><mo stretchy="false">/</mo><mi>A</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;BE&quot;/A&#125; &#123;&#125;</annotation></semantics></math>, the binding energy per nucleon, is greater for medium-mass nuclei and has a maximum at Fe (iron). This means that if two low-mass nuclei can be fused together to form a larger nucleus, energy can be released. The larger nucleus has a greater binding energy and less mass per nucleon than the two that combined. Thus mass is destroyed in the fusion reaction, and energy is released (see {'Figure_33_5_2a Figure 33.5.2a}). On average, fusion of low-mass nuclei releases energy, but the details depend on the actual nuclides involved.
    
    
            
    
    The major obstruction to fusion is the Coulomb repulsion between nuclei. Since the attractive nuclear force that can fuse nuclei together is short ranged, the repulsion of like positive charges must be overcome to get nuclei close enough to induce fusion. {'Figure_33_5_3a Figure 33.5.3a} shows an approximate graph of the potential energy between two nuclei as a function of the distance between their centers. The graph is analogous to a hill with a well in its center. A ball rolled from the right must have enough kinetic energy to get over the hump before it falls into the deeper well with a net gain in energy. So it is with fusion. If the nuclei are given enough kinetic energy to overcome the electric potential energy due to repulsion, then they can combine, release energy, and fall into a deep well. One way to accomplish this is to heat fusion fuel to high temperatures so that the kinetic energy of thermal motion is sufficient to get the nuclei together.
    
    
            
    
    You might think that, in the core of our Sun, nuclei are coming into contact and fusing. However, in fact, temperatures on the order of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mtext>10</mtext><mrow><mn>8</mn></mrow></msup><mn>K</mn></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;10&quot; rSup &#123; size 8&#123;8&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>  are needed to actually get the nuclei in contact, exceeding the core temperature of the Sun. Quantum mechanical tunneling is what makes fusion in the Sun possible, and tunneling is an important process in most other practical applications of fusion, too. Since the probability of tunneling is extremely sensitive to barrier height and width, increasing the temperature greatly increases the rate of fusion. The closer reactants get to one another, the more likely they are to fuse (see {'Figure_33_5_4a Figure 33.5.4a}). Thus most fusion in the Sun and other stars takes place at their centers, where temperatures are highest. Moreover, high temperature is needed for thermonuclear power to be a practical source of energy.
    
    
            
    
    The Sun produces energy by fusing protons or hydrogen nuclei <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mrow><mn>1</mn></mrow></msup><mtext>H</mtext></mrow></mrow><mrow/></mrow></semantics></math> (by far the Sun’s most abundant nuclide) into helium nuclei <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mrow><mn>4</mn></mrow></msup><mtext>He</mtext></mrow></mrow><mrow/></mrow></semantics></math>. The principal sequence of fusion reactions forms what is called the  **proton-proton cycle**:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mn>1</mn></msup><mrow><mtext>H </mtext><mo stretchy="false">+</mo><msup><mrow/><mn>1</mn></msup></mrow><mtext>H </mtext><mo stretchy="false">→</mo><msup><mrow/><mn>2</mn></msup><mrow><mrow><mtext>H </mtext><mo stretchy="false">+</mo><msup><mi>e</mi><mrow><mrow><mo stretchy="false">+</mo><mrow/></mrow></mrow></msup></mrow><mo stretchy="false">+</mo><msub><mi>v</mi><mrow><mtext>e</mtext></mrow></msub><mo>                 (0.42 MeV)</mo></mrow></mrow></mrow><mrow/></mrow></semantics></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mn>1</mn></msup><mrow><mtext>H </mtext><mo stretchy="false">+</mo><msup><mrow/><mn>2</mn></msup></mrow><mtext>H</mtext><mo stretchy="false">→</mo><msup><mrow/><mn>3</mn></msup><mrow><mtext>He</mtext><mo stretchy="false">+</mo><mi>γ</mi></mrow></mrow><mo>                          (5.49 MeV)</mo></mrow><mrow/></mrow></semantics></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mn>3</mn></msup><mrow><mtext>He </mtext><mo stretchy="false">+</mo><msup><mrow/><mn>3</mn></msup></mrow><mtext>He </mtext><mo stretchy="false">→</mo><msup><mrow/><mn>4</mn></msup><mrow><mtext>He </mtext><mo stretchy="false">+</mo><msup><mrow/><mn>1</mn></msup></mrow><mrow><mtext>H </mtext><mo stretchy="false">+</mo><msup><mrow/><mn>1</mn></msup></mrow><mtext>H</mtext></mrow><mo>        (12.86 MeV)</mo></mrow><mrow/></mrow></semantics></math>
    
    where <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mi>e</mi><mrow><mrow><mo stretchy="false">+</mo><mrow/></mrow></mrow></msup></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;e rSup &#123; size 8&#123;+&#123;&#125;&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> stands for a positron and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>v</mi><mrow><mtext>e</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v rSub &#123; size 8&#123;e&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is an electron neutrino. (The energy in parentheses is  *released* by the reaction.) Note that the first two reactions must occur twice for the third to be possible, so that the cycle consumes six protons (<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mrow><mn>1</mn></mrow></msup><mtext>H</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;&#125; rSup &#123; size 8&#123;1&#125; &#125; H&#125; &#123;&#125;</annotation></semantics></math>) but gives back two. Furthermore, the two positrons produced will find two electrons and annihilate to form four more <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>γ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;γ&#125; &#123;&#125;</annotation></semantics></math> rays, for a total of six. The overall effect of the cycle is thus
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mn>2</mn><mrow><msup><mi>e</mi><mrow><mrow><mo stretchy="false">−</mo><mrow/></mrow></mrow></msup><mo stretchy="false">+</mo><mn>4</mn></mrow><msup><mrow/><mn>1</mn></msup><mtext>H</mtext><mo stretchy="false">→</mo><msup><mrow/><mn>4</mn></msup><mrow><mrow><mtext>He</mtext><mo stretchy="false">+</mo><msub><mn>2v</mn><mrow><mtext>e</mtext></mrow></msub></mrow><mo stretchy="false">+</mo><mn>6γ</mn></mrow><mo>         (26.7 MeV)</mo></mrow></mrow><mrow/></mrow></semantics></math>
    
    where the 26.7 MeV includes the annihilation energy of the positrons and electrons and is distributed among all the reaction products. The solar interior is dense, and the reactions occur deep in the Sun where temperatures are highest. It takes about 32,000 years for the energy to diffuse to the surface and radiate away. However, the neutrinos escape the Sun in less than two seconds, carrying their energy with them, because they interact so weakly that the Sun is transparent to them. Negative feedback in the Sun acts as a thermostat to regulate the overall energy output. For instance, if the interior of the Sun becomes hotter than normal, the reaction rate increases, producing energy that expands the interior. This cools it and lowers the reaction rate. Conversely, if the interior becomes too cool, it contracts, increasing the temperature and reaction rate (see {'Figure_33_5_5a Figure 33.5.5a}). Stars like the Sun are stable for billions of years, until a significant fraction of their hydrogen has been depleted. What happens then is discussed in <link:>.
    
    
            
    
    Theories of the proton-proton cycle (and other energy-producing cycles in stars) were pioneered by the German-born, American physicist Hans Bethe (1906–2005), starting in 1938. He was awarded the 1967 Nobel Prize in physics for this work, and he has made many other contributions to physics and society. Neutrinos produced in these cycles escape so readily that they provide us an excellent means to test these theories and study stellar interiors. Detectors have been constructed and operated for more than four decades now to measure solar neutrinos (see {'Figure_33_5_6a Figure 33.5.6a}). Although solar neutrinos are detected and neutrinos were observed from Supernova 1987A ({'Figure_33_5_7a Figure 33.5.7a}), too few solar neutrinos were observed to be consistent with predictions of solar energy production. After many years, this solar neutrino problem was resolved with a blend of theory and experiment that showed that the neutrino does indeed have mass. It was also found that there are three types of neutrinos, each associated with a different type of nuclear decay. 
    
    
            
    
    
            
    
    The proton-proton cycle is not a practical source of energy on Earth, in spite of the great abundance of hydrogen (<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mrow><mn>1</mn></mrow></msup><mtext>H</mtext></mrow></mrow><mrow/></mrow></semantics></math>). The reaction 
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mn>1</mn></msup><mrow><mtext>H </mtext><mo stretchy="false">+</mo><msup><mrow/><mn>1</mn></msup></mrow><mtext>H </mtext><mo stretchy="false">→</mo><msup><mrow/><mn>2</mn></msup><mrow><mrow><mtext>H </mtext><mo stretchy="false">+</mo><msup><mi>e</mi><mrow><mrow><mo stretchy="false">+</mo><mrow/></mrow></mrow></msup></mrow><mo stretchy="false">+</mo><msub><mi>v</mi><mrow><mtext>e</mtext></mrow></msub></mrow></mrow></mrow><mrow/></mrow></semantics></math> has a very low probability of occurring. (This is why our Sun will last for about ten billion years.) However, a number of other fusion reactions are easier to induce. Among them are:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mn>2</mn></msup><mrow><mtext>H </mtext><mo stretchy="false">+</mo><msup><mrow/><mn>2</mn></msup></mrow><mtext>H </mtext><mo stretchy="false">→</mo><msup><mrow/><mn>3</mn></msup><mrow><mtext>H </mtext><mo stretchy="false">+</mo><msup><mrow/><mn>1</mn></msup></mrow><mtext>H</mtext></mrow><mo>        (4.03 MeV)</mo></mrow><mrow/></mrow></semantics></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mrow/><mn>2</mn></msup><mrow><mtext>H </mtext><mo stretchy="false">+</mo><msup><mrow/><mn>2</mn></msup></mrow><mtext>H </mtext><mo stretchy="false">→</mo><msup><mrow/><mn>3</mn></msup><mrow><mtext>He </mtext><mo stretchy="false">+</mo><mi>n</mi></mrow><mo>         (3.27 MeV)</mo></mrow></mrow></semantics></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mn>2</mn></msup><mrow><mtext>H</mtext><mo stretchy="false">+</mo><msup><mrow/><mn>3</mn></msup></mrow><mtext>H</mtext><mo stretchy="false">→</mo><msup><mrow/><mn>4</mn></msup><mrow><mtext>He </mtext><mo stretchy="false">+</mo><mi>n</mi></mrow><mo>       (17.59 MeV)</mo></mrow></mrow><mrow/></mrow></semantics></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mn>2</mn></msup><mrow><mtext>H </mtext><mo stretchy="false">+</mo><msup><mrow/><mn>2</mn></msup></mrow><mtext>H </mtext><mo stretchy="false">→</mo><msup><mrow/><mn>4</mn></msup><mrow><mtext>He </mtext><mo stretchy="false">+</mo><mi>γ</mi></mrow><mo>           (23.85 MeV).</mo></mrow></mrow><mrow/></mrow></semantics></math>
    
    Deuterium (<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mrow><mn>2</mn></mrow></msup><mtext>H</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;&#125; rSup &#123; size 8&#123;2&#125; &#125; H&#125; &#123;&#125;</annotation></semantics></math>) is about 0.015% of natural hydrogen, so there is an immense amount of it in sea water alone. In addition to an abundance of deuterium fuel, these fusion reactions produce large energies per reaction (in parentheses), but they do not produce much radioactive waste. Tritium (<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mrow><mn>3</mn></mrow></msup><mtext>H</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;&#125; rSup &#123; size 8&#123;3&#125; &#125; H&#125; &#123;&#125;</annotation></semantics></math>) is radioactive, but it is consumed as a fuel (the reaction <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mn>2</mn></msup><mrow><mtext>H</mtext><mo stretchy="false">+</mo><msup><mrow/><mn>3</mn></msup></mrow><mtext>H</mtext><mo stretchy="false">→</mo><msup><mrow/><mn>4</mn></msup><mrow><mtext>He </mtext><mo stretchy="false">+</mo><mi>n</mi></mrow></mrow></mrow><mrow/></mrow></semantics></math>), and the neutrons and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>γ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;γ&#125; &#123;&#125;</annotation></semantics></math>s can be shielded. The neutrons produced can also be used to create more energy and fuel in reactions like
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mi>n</mi><mo stretchy="false">+</mo><msup><mrow/><mn>1</mn></msup></mrow><mtext>H </mtext><mo stretchy="false">→</mo><msup><mrow/><mn>2</mn></msup><mrow><mtext>H</mtext><mo stretchy="false">+</mo><mi>γ</mi></mrow><mo>       (20.68 MeV)</mo></mrow></mrow><mrow/></mrow></semantics></math>
    
    and
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mi>n</mi><mo stretchy="false">+</mo><msup><mrow/><mn>1</mn></msup></mrow><mtext>H </mtext><mo stretchy="false">→</mo><msup><mrow/><mn>2</mn></msup><mrow><mtext>H</mtext><mo stretchy="false">+</mo><mi>γ</mi></mrow><mo>       (2.22 MeV).</mo></mrow></mrow><mrow/></mrow></semantics></math>
    
    Note that these last two reactions, and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mrow/><mn>2</mn></msup><mrow><mtext>H </mtext><mo stretchy="false">+</mo><msup><mrow/><mn>2</mn></msup></mrow><mtext>H </mtext><mo stretchy="false">→</mo><msup><mrow/><mn>4</mn></msup><mrow><mtext>He </mtext><mo stretchy="false">+</mo><mi>γ</mi></mrow></mrow></mrow><mrow/></mrow></semantics></math>, put most of their energy output into the <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>γ</mi></mrow><mrow/></mrow></semantics></math> ray, and such energy is difficult to utilize.
    
    The three keys to practical fusion energy generation are to achieve the temperatures necessary to make the reactions likely, to raise the density of the fuel, and to confine it long enough to produce large amounts of energy. These three factors—temperature, density, and time—complement one another, and so a deficiency in one can be compensated for by the others.  **Ignition** is defined to occur when the reactions produce enough energy to be self-sustaining after external energy input is cut off. This goal, which must be reached before commercial plants can be a reality, has not been achieved. Another milestone, called  **break-even**, occurs when the fusion power produced equals the heating power input. Break-even has nearly been reached and gives hope that ignition and commercial plants may become a reality in a few decades.
    
    Two techniques have shown considerable promise. The first of these is called  **magnetic confinement** and uses the property that charged particles have difficulty crossing magnetic field lines. The tokamak, shown in {'Figure_33_5_8a Figure 33.5.8a}, has shown particular promise. The tokamak’s toroidal coil confines charged particles into a circular path with a helical twist due to the circulating ions themselves. In 1995, the Tokamak Fusion Test Reactor at Princeton in the US achieved world-record plasma temperatures as high as 500 million degrees Celsius. This facility operated between 1982 and 1997. A joint international effort is underway in France to build a tokamak-type reactor that will be the stepping stone to commercial power. ITER, as it is called, will be a full-scale device that aims to demonstrate the feasibility of fusion energy. It will generate 500 MW of power for extended periods of time and will achieve break-even conditions. It will study plasmas in conditions similar to those expected in a fusion power plant. Completion is scheduled for 2018.
    
    
            
    
    The second promising technique aims multiple lasers at tiny fuel pellets filled with a mixture of deuterium and tritium. Huge power input heats the fuel, evaporating the confining pellet and crushing the fuel to high density with the expanding hot plasma produced. This technique is called  **inertial confinement**, because the fuel’s inertia prevents it from escaping before significant fusion can take place. Higher densities have been reached than with tokamaks, but with smaller confinement times. In 2009, the Lawrence Livermore Laboratory (CA) completed a laser fusion device with 192 ultraviolet laser beams that are focused upon a D-T pellet (see {'Figure_33_5_9a Figure 33.5.9a}). 
    
    
            

  apply FullText

  ---
    32_5_0
    32_5_1

  path FullText
    step
      --
        32_5_0
    step
      --
        32_5_1

    