
/ Carnot’s Perfect Heat Engine: The Second Law of Thermodynamics Restated
story 15_4
  >
    
            
    
    We know from the second law of thermodynamics that a heat engine cannot be 100% efficient, since there must always be some heat transfer <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>Q</mi><mrow><mtext>c</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Q rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> to the environment, which is often called waste heat. How efficient, then, can a heat engine be? This question was answered at a theoretical level in 1824 by a young French engineer, Sadi Carnot (1796–1832), in his study of the then-emerging heat engine technology crucial to the Industrial Revolution. He devised a theoretical cycle, now called the  **Carnot cycle**, which is the most efficient cyclical process possible. The second law of thermodynamics can be restated in terms of the Carnot cycle, and so what Carnot actually discovered was this fundamental law. Any heat engine employing the Carnot cycle is called a  **Carnot engine**.
    
    What is crucial to the Carnot cycle—and, in fact, defines it—is that only reversible processes are used. Irreversible processes involve dissipative factors, such as friction and turbulence. This increases heat transfer <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>Q</mi><mrow><mtext>c</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Q rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> to the environment and reduces the efficiency of the engine. Obviously, then, reversible processes are superior.
    
    {'Figure_16_4_2 Figure 16.4.2} shows the <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mstyle fontstyle="italic"><mrow><mtext>PV</mtext></mrow></mstyle></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;PV&quot;&#125; &#123;&#125;</annotation></semantics></math> diagram for a Carnot cycle. The cycle comprises two isothermal and two adiabatic processes. Recall that both isothermal and adiabatic processes are, in principle, reversible.
    
    Carnot also determined the efficiency of a perfect heat engine—that is, a Carnot engine. It is always true that the efficiency of a cyclical heat engine is given by:
    
    <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mml:mrow xmlns:mml="http://www.w3.org/1998/Math/MathML"><mrow><mrow><mrow><mstyle fontstyle="italic"><mrow><mtext>Eff</mtext></mrow></mstyle><mo stretchy="false">=</mo><mfrac><mrow><msub><mi>Q</mi><mrow><mtext>h</mtext></mrow></msub><mo stretchy="false">−</mo><msub><mi>Q</mi><mrow><mtext>c</mtext></mrow></msub></mrow><msub><mi>Q</mi><mrow><mtext>h</mtext></mrow></msub></mfrac></mrow><mo stretchy="false">=</mo><mrow><mn>1</mn><mo stretchy="false">−</mo><mfrac><msub><mi>Q</mi><mrow><mtext>c</mtext></mrow></msub><msub><mi>Q</mi><mrow><mtext>h</mtext></mrow></msub></mfrac></mrow></mrow></mrow><mrow><mtext>.</mtext></mrow></mml:mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;Eff&quot;= &#123;  &#123;Q rSub &#123; size 8&#123;h&#125; &#125;  - Q rSub &#123; size 8&#123;c&#125; &#125; &#125;  over  &#123;Q rSub &#123; size 8&#123;h&#125; &#125; &#125; &#125; =1 -  &#123;  &#123;Q rSub &#123; size 8&#123;c&#125; &#125; &#125;  over  &#123;Q rSub &#123; size 8&#123;h&#125; &#125; &#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    What Carnot found was that for a perfect heat engine, the ratio <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mi>Q</mi><mrow><mtext>c</mtext></mrow></msub><mo stretchy="false">/</mo><msub><mi>Q</mi><mrow><mtext>h</mtext></mrow></msub></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Q rSub &#123; size 8&#123;c&#125; &#125; /Q rSub &#123; size 8&#123;h&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> equals the ratio of the absolute temperatures of the heat reservoirs. That is, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>Q</mi><mrow><mtext>c</mtext></mrow></msub><mo stretchy="false">/</mo><msub><mi>Q</mi><mrow><mtext>h</mtext></mrow></msub></mrow><mo stretchy="false">=</mo><mrow><msub><mi>T</mi><mrow><mtext>c</mtext></mrow></msub><mo stretchy="false">/</mo><msub><mi>T</mi><mrow><mtext>h</mtext></mrow></msub></mrow></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Q rSub &#123; size 8&#123;c&#125; &#125; /Q rSub &#123; size 8&#123;h&#125; &#125; =T rSub &#123; size 8&#123;c&#125; &#125; /T rSub &#123; size 8&#123;h&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> for a Carnot engine, so that the maximum or  **Carnot efficiency**<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mstyle><mrow><msub><mi fontstyle="italic">Eff</mi><mrow><mtext>C</mtext></mrow></msub></mrow></mstyle></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;Eff&quot; rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is given by
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mstyle><mrow><msub><mi fontstyle="italic">Eff</mi><mrow><mtext>C</mtext></mrow></msub></mrow></mstyle><mo stretchy="false">=</mo><mrow><mn>1</mn><mo stretchy="false">−</mo><mfrac><msub><mi>T</mi><mrow><mtext>c</mtext></mrow></msub><msub><mi>T</mi><mrow><mtext>h</mtext></mrow></msub></mfrac></mrow></mrow></mrow><mrow><mtext>,</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;Eff&quot; rSub &#123; size 8&#123;c&#125; &#125; =1 -  &#123;  &#123;T rSub &#123; size 8&#123;c&#125; &#125; &#125;  over  &#123;T rSub &#123; size 8&#123;h&#125; &#125; &#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    where <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>T</mi><mrow><mtext>h</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;T rSub &#123; size 8&#123;h&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> and <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>T</mi><mrow><mtext>c</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;T rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> are in kelvins (or any other absolute temperature scale). No real heat engine can do as well as the Carnot efficiency—an actual efficiency of about 0.7 of this maximum is usually the best that can be accomplished. But the ideal Carnot engine, like the drinking bird above, while a fascinating novelty, has zero power. This makes it unrealistic for any applications.
    
    Carnot’s interesting result implies that 100% efficiency would be possible only if <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>T</mi><mrow><mtext>c</mtext></mrow></msub><mo stretchy="false">=</mo><mn>0 K</mn></mrow></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;T rSub &#123; size 8&#123;c&#125; &#125; =0&quot; K&quot;&#125; &#123;&#125;</annotation></semantics></math> —that is, only if the cold reservoir were at absolute zero, a practical and theoretical impossibility. But the physical implication is this—the only way to have all heat transfer go into doing work is to remove  *all* thermal energy, and this requires a cold reservoir at absolute zero.
    
    It is also apparent that the greatest efficiencies are obtained when the ratio <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mi>T</mi><mrow><mtext>c</mtext></mrow></msub><mo stretchy="false">/</mo><msub><mi>T</mi><mrow><mtext>h</mtext></mrow></msub></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;T rSub &#123; size 8&#123;c&#125; &#125; /T rSub &#123; size 8&#123;h&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is as small as possible. Just as discussed for the Otto cycle in the previous section, this means that efficiency is greatest for the highest possible temperature of the hot reservoir and lowest possible temperature of the cold reservoir. (This setup increases the area inside the closed loop on the <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mstyle fontstyle="italic"><mrow><mtext>PV</mtext></mrow></mstyle></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;PV&quot;&#125; &#123;&#125;</annotation></semantics></math> diagram; also, it seems reasonable that the greater the temperature difference, the easier it is to divert the heat transfer to work.) The actual reservoir temperatures of a heat engine are usually related to the type of heat source and the temperature of the environment into which heat transfer occurs. Consider the following example.
    
    
            
    
    
            
    
    Since all real processes are irreversible, the actual efficiency of a heat engine can never be as great as that of a Carnot engine, as illustrated in {'Figure_16_4_5 Figure 16.4.5}(a). Even with the best heat engine possible, there are always dissipative processes in peripheral equipment, such as electrical transformers or car transmissions. These further reduce the overall efficiency by converting some of the engine’s work output back into heat transfer, as shown in {'Figure_16_4_5 Figure 16.4.5}(b).
    
    
            

  apply FullText

  ---
    15_4_0
    15_4_1

  / Carnot’s Perfect Heat Engine: The Second Law of Thermodynamics Restated - Full Text
  path FullText
    step
      --
        15_4_0
    step
      --
        15_4_1

    