
/ Physics of the Eye
story 26_1
  >
    The eye is perhaps the most interesting of all optical instruments. The eye is remarkable in how it forms images and in the richness of detail and color it can detect. However, our eyes commonly need some correction, to reach what is called “normal” vision, but should be called ideal rather than normal. Image formation by our eyes and common vision correction are easy to analyze with the optics discussed in <link:>.
    
    {'Figure_27_1_1 Figure 27.1.1} shows the basic anatomy of the eye. The cornea and lens form a system that, to a good approximation, acts as a single thin lens. For clear vision, a real image must be projected onto the light-sensitive retina, which lies at a fixed distance from the lens. The lens of the eye adjusts its power to produce an image on the retina for objects at different distances. The center of the image falls on the fovea, which has the greatest density of light receptors and the greatest acuity (sharpness) in the visual field. The variable opening (or pupil) of the eye along with chemical adaptation allows the eye to detect light intensities from the lowest observable to <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msup><mtext>10</mtext><mrow><mtext>10</mtext></mrow></msup></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;10&quot; rSup &#123; size 8&#123;&quot;10&quot;&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> times greater (without damage). This is an incredible range of detection. Our eyes perform a vast number of functions, such as sense direction, movement, sophisticated colors, and distance. Processing of visual nerve impulses begins with interconnections in the retina and continues in the brain. The optic nerve conveys signals received by the eye to the brain. 
    
    
            
    
    Refractive indices are crucial to image formation using lenses.  shows refractive indices relevant to the eye. The biggest change in the refractive index, and bending of rays, occurs at the cornea rather than the lens. The ray diagram in {'Figure_27_1_2 Figure 27.1.2} shows image formation by the cornea and lens of the eye. The rays bend according to the refractive indices provided in . The cornea provides about two-thirds of the power of the eye, owing to the fact that speed of light changes considerably while traveling from air into cornea. The lens provides the remaining power needed to produce an image on the retina. The cornea and lens can be treated as a single thin lens, even though the light rays pass through several layers of material (such as cornea, aqueous humor, several layers in the lens, and vitreous humor), changing direction at each interface. The image formed is much like the one produced by a single convex lens. This is a case 1 image. Images formed in the eye are inverted but the brain inverts them once more to make them seem upright.
    
    
        
    
    
            
    
    As noted, the image must fall precisely on the retina to produce clear vision — that is, the image distance <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>d</mi><mrow><mtext>i</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;d rSub &#123; size 8&#123;i&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> must equal the lens-to-retina distance. Because the lens-to-retina distance does not change, the image distance <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>d</mi><mrow><mtext>i</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;d rSub &#123; size 8&#123;i&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> must be the same for objects at all distances. The eye manages this by varying the power (and focal length) of the lens to accommodate for objects at various distances. The process of adjusting the eye’s focal length is called  **accommodation**. A person with normal (ideal) vision can see objects clearly at distances ranging from 25 cm to essentially infinity. However, although the near point (the shortest distance at which a sharp focus can be obtained) increases with age (becoming meters for some older people), we will consider it to be 25 cm in our treatment here.
    
    {'Figure_27_1_3 Figure 27.1.3} shows the accommodation of the eye for distant and near vision. Since light rays from a nearby object can diverge and still enter the eye, the lens must be more converging (more powerful) for close vision than for distant vision. To be more converging, the lens is made thicker by the action of the ciliary muscle surrounding it. The eye is most relaxed when viewing distant objects, one reason that microscopes and telescopes are designed to produce distant images. Vision of very distant objects is called  *totally relaxed*, while close vision is termed  *accommodated*, with the closest vision being  *fully accommodated*.
    
    
            
    
    We will use the thin lens equations to examine image formation by the eye quantitatively. First, note the power of a lens is given as <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>p</mi><mo stretchy="false">=</mo><mrow><mn>1</mn><mo stretchy="false">/</mo><mi>f</mi></mrow></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;p= &#123;1&#125; slash &#123;f&#125; &#125; &#123;&#125;</annotation></semantics></math>, so we rewrite the thin lens equations as
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mi>P</mi>                  <mo stretchy="false">=</mo>                  <mrow>                    <mfrac>                      <mn>1</mn>                      <msub>                        <mi>d</mi>                                                  <mrow>                            <mtext>o</mtext>                          </mrow>                                              </msub>                    </mfrac>                    <mo stretchy="false">+</mo>                    <mfrac>                      <mn>1</mn>                      <msub>                        <mi>d</mi>                                                  <mrow>                            <mtext>i</mtext>                          </mrow>                                              </msub>                    </mfrac>                  </mrow>                </mrow>              </mrow>          </mrow>        </semantics>      </math>     
    
    and
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <mfrac>                      <msub>                        <mi>h</mi>                                                  <mrow>                            <mtext>i</mtext>                          </mrow>                                              </msub>                      <msub>                        <mi>h</mi>                                                  <mrow>                            <mtext>o</mtext>                          </mrow>                                              </msub>                    </mfrac>                    <mo stretchy="false">=</mo>                    <mrow>                      <mo stretchy="false">−</mo>                      <mfrac>                        <msub>                          <mi>d</mi>                                                      <mrow>                              <mtext>i</mtext>                            </mrow>                                                  </msub>                        <msub>                          <mi>d</mi>                                                      <mrow>                              <mtext>o</mtext>                            </mrow>                                                  </msub>                      </mfrac>                    </mrow>                  </mrow>                  <mo stretchy="false">=</mo>                  <mi fontstyle="italic">m.</mi>                </mrow>              </mrow>          </mrow>        </semantics>      </math>     
    
    We understand that <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>d</mi><mrow><mtext>i</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;d rSub &#123; size 8&#123;i&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> must equal the lens-to-retina distance to obtain clear vision, and that normal vision is possible for objects at distances <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>d</mi><mrow><mn>o</mn></mrow></msub></mrow><mo stretchy="false">=</mo><mtext>25 cm</mtext></mrow></mrow><mrow/></mrow></semantics></math> to infinity.
    
    The eye can detect an impressive amount of detail, considering how small the image is on the retina. To get some idea of how small the image can be, consider the following example.

  apply FullText

  ---
    26_1_0
    26_1_1

  path FullText
    step
      --
        26_1_0
    step
      --
        26_1_1

    