
/ Fermentation
story 8_4
  >
    Many cells are unable to carry out respiration because of one or more of the following circumstances:
    
      1. The cell lacks a sufficient amount of any appropriate, inorganic, final electron acceptor to carry out cellular respiration.
      2. The cell lacks genes to make appropriate complexes and electron carriers in the electron transport system.
      3. The cell lacks genes to make one or more enzymes in the Krebs cycle.
    
    Whereas lack of an appropriate inorganic final electron acceptor is environmentally dependent, the other two conditions are genetically determined. Thus, many prokaryotes, including members of the clinically important genus  *Streptococcus*, are permanently incapable of respiration, even in the presence of oxygen. Conversely, many prokaryotes are facultative, meaning that, should the environmental conditions change to provide an appropriate inorganic final electron acceptor for respiration, organisms containing all the genes required to do so will switch to cellular respiration for glucose metabolism because respiration allows for much greater ATP production per glucose molecule.
    
    If respiration does not occur, NADH must be reoxidized to NAD<sup>+</sup> for reuse as an electron carrier for glycolysis, the cell’s only mechanism for producing any ATP, to continue. Some living systems use an organic molecule (commonly pyruvate) as a final electron acceptor through a process called  **fermentation**. Fermentation does not involve an electron transport system and does not directly produce any additional ATP beyond that produced during glycolysis by substrate-level phosphorylation. Organisms carrying out fermentation, called fermenters, produce a maximum of two ATP molecules per glucose during glycolysis.  compares the final electron acceptors and methods of ATP synthesis in aerobic respiration, anaerobic respiration, and fermentation. Note that the number of ATP molecules shown for glycolysis assumes the  **Embden-Meyerhof-Parnas pathway**. The number of ATP molecules made by  **substrate-level phosphorylation** (SLP) versus  **oxidative phosphorylation** (OP) are indicated.
    
    
    
        
    
    Microbial fermentation processes have been manipulated by humans and are used extensively in the production of various foods and other commercial products, including pharmaceuticals. Microbial fermentation can also be useful for identifying microbes for diagnostic purposes.
    
    Fermentation by some bacteria, like those in yogurt and other soured food products, and by animals in muscles during oxygen depletion, is  **lactic acid fermentation**. The chemical reaction of lactic acid fermentation is as follows:
    
    <label xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"/><math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>Pyruvate  +  NADH</mtext><mspace width="0.2em"/><mtext> </mtext><mover><mo>↔</mo><mrow/></mover><mtext> </mtext><msup><mrow><mtext>lactic acid  + NAD</mtext></mrow><mtext>+</mtext></msup></mrow></math>
    
    Bacteria of several gram-positive genera, including  **Lactobacillus**,  **Leuconostoc**, and  **Streptococcus**, are collectively known as the  **lactic acid bacteria (LAB)**, and various strains are important in food production. During  **yogurt**and  **cheese**production, the highly acidic environment generated by lactic acid fermentation denatures proteins contained in milk, causing it to solidify. When lactic acid is the only fermentation product, the process is said to be  **homolactic fermentation**; such is the case for  *Lactobacillus delbrueckii* and  *S. thermophiles* used in yogurt production. However, many bacteria perform  **heterolactic fermentation**, producing a mixture of lactic acid, ethanol and/or acetic acid, and CO<sub>2</sub> as a result, because of their use of the branched pentose phosphate pathway instead of the EMP pathway for glycolysis. One important heterolactic fermenter is  *Leuconostoc mesenteroides*, which is used for souring vegetables like cucumbers and cabbage, producing pickles and sauerkraut, respectively.
    
    Lactic acid bacteria are also important medically. The production of low pH environments within the body inhibits the establishment and growth of pathogens in these areas. For example, the vaginal microbiota is composed largely of lactic acid bacteria, but when these bacteria are reduced, yeast can proliferate, causing a yeast infection. Additionally, lactic acid bacteria are important in maintaining the health of the gastrointestinal tract and, as such, are the primary component of probiotics.
    
    Another familiar fermentation process is  **alcohol fermentation**, which produces ethanol. The ethanol fermentation reaction is shown in {'Figure_8_4_EthFerm Figure 8.4.EthFerm}. In the first reaction, the enzyme  **pyruvate decarboxylase** removes a carboxyl group from pyruvate, releasing CO<sub>2</sub> gas while producing the two-carbon molecule acetaldehyde. The second reaction, catalyzed by the enzyme alcohol dehydrogenase, transfers an electron from NADH to acetaldehyde, producing ethanol and NAD<sup>+</sup>. The ethanol fermentation of pyruvate by the yeast  **Saccharomyces cerevisiae** is used in the production of alcoholic beverages and also makes bread products rise due to CO<sub>2</sub> production. Outside of the food industry, ethanol fermentation of plant products is important in  **biofuel** production.
    
    
            
    
    Beyond lactic acid fermentation and alcohol fermentation, many other fermentation methods occur in prokaryotes, all for the purpose of ensuring an adequate supply of NAD<sup>+</sup> for glycolysis (). Without these pathways, glycolysis would not occur and no ATP would be harvested from the breakdown of glucose. It should be noted that most forms of fermentation besides  **homolactic fermentation** produce gas, commonly CO<sub>2</sub> and/or hydrogen gas. Many of these different types of fermentation pathways are also used in food production and each results in the production of different organic acids, contributing to the unique flavor of a particular fermented food product. The propionic acid produced during  **propionic acid fermentation** contributes to the distinctive flavor of Swiss cheese, for example.
    
    Several fermentation products are important commercially outside of the food industry. For example, chemical solvents such as  **acetone** and  **butanol** are produced during  **acetone-butanol-ethanol fermentation**. Complex organic pharmaceutical compounds used in antibiotics (e.g., penicillin), vaccines, and vitamins are produced through  **mixed acid fermentation**. Fermentation products are used in the laboratory to differentiate various bacteria for diagnostic purposes. For example, enteric bacteria are known for their ability to perform mixed acid fermentation, reducing the pH, which can be detected using a pH indicator. Similarly, the bacterial production of acetoin during butanediol fermentation can also be detected. Gas production from fermentation can also be seen in an inverted Durham tube that traps produced gas in a broth culture.
    
    Microbes can also be differentiated according to the substrates they can ferment. For example,  *E. coli* can ferment lactose, forming gas, whereas some of its close gram-negative relatives cannot. The ability to ferment the sugar alcohol sorbitol is used to identify the pathogenic enterohemorrhagic O157:H7 strain of  *E. coli* because, unlike other  *E. coli* strains, it is unable to ferment sorbitol. Last, mannitol fermentation differentiates the mannitol-fermenting  **Staphylococcus aureus** from other non–mannitol-fermenting staphylococci.
    
    
    
        

  apply FullText

  ---
    8_4_1
    8_4_2
    8_4_4

  / Fermentation - Full Text
  path FullText
    step
      --
        8_4_1
    step
      --
        8_4_2
    step
      --
        8_4_4

    