
/ The Wave Nature of Matter Causes Quantization
story 30_6
  >
    After visiting some of the applications of different aspects of atomic physics, we now return to the basic theory that was built upon Bohr’s atom. Einstein once said it was important to keep asking the questions we eventually teach children not to ask. Why is angular momentum quantized? You already know the answer. Electrons have wave-like properties, as de Broglie later proposed. They can exist only where they interfere constructively, and only certain orbits meet proper conditions, as we shall see in the next module.
    
    Following Bohr’s initial work on the hydrogen atom, a decade was to pass before de Broglie proposed that matter has wave properties. The wave-like properties of matter were subsequently confirmed by observations of electron interference when scattered from crystals. Electrons can exist only in locations where they interfere constructively. How does this affect electrons in atomic orbits? When an electron is bound to an atom, its wavelength must fit into a small space, something like a standing wave on a string. (See {'Figure_31_6_a Figure 31.6.a}.) Allowed orbits are those orbits in which an electron constructively interferes with itself. Not all orbits produce constructive interference. Thus only certain orbits are allowed—the orbits are quantized.
    
    
            
    
    For a circular orbit, constructive interference occurs when the electron’s wavelength fits neatly into the circumference, so that wave crests always align with crests and wave troughs align with troughs, as shown in {'Figure_31_6_a Figure 31.6.a} (b). More precisely, when an integral multiple of the electron’s wavelength equals the circumference of the orbit, constructive interference is obtained. In equation form, the   *condition for constructive interference and an allowed electron orbit* is
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mi fontstyle="italic">nλ</mi><mrow><mi>n</mi></mrow></msub><mo stretchy="false">=</mo><msub><mrow><mn>2</mn><mi fontstyle="italic">πr</mi></mrow><mrow><mi>n</mi></mrow></msub></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;nλ rSub &#123; size 8&#123;n&#125; &#125; =2πr rSub &#123; size 8&#123;n&#125; &#125; &#125; &#123;&#125;</annotation></semantics><semantics><mrow><mrow><mfenced close=")" open="("><mrow><mrow><mi>n</mi><mo stretchy="false">=</mo></mrow><mn>1, 2, 3 ...</mn></mrow></mfenced><mtext>,</mtext></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; left (n=1, 2, 3  &quot;.&quot;   &quot;.&quot;   &quot;.&quot;  right )&#125; &#123;&#125;</annotation></semantics></math>
    
    where <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>λ</mi><mrow><mi>n</mi></mrow></msub></mrow></mrow></semantics></math> is the electron’s wavelength and 
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>r</mi><mrow><mi>n</mi></mrow></msub></mrow></mrow></semantics></math> is the radius of that circular orbit. The de Broglie wavelength is 
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow>   <mi>λ</mi><mo>=</mo><mi>h</mi><mo>/</mo><mi>p</mi><mo>=</mo><mi>h</mi><mo>/</mo><mi fontstyle="italic">mv</mi></mrow></semantics></math>, and so here 
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"> <semantics>  <mrow>    <mi>λ</mi><mo>=</mo><mi>h</mi><mo>/</mo><msub><mi>m</mi>    <mi>e</mi></msub>   <mi>v</mi>  </mrow> </semantics></math>. Substituting this into the previous condition for constructive interference produces an interesting result:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mfrac>                    <mstyle fontstyle="italic">                      <mrow>                        <mtext>nh</mtext>                      </mrow>                    </mstyle>                    <mrow>                      <msub>                        <mi>m</mi>                                                  <mrow>                            <mi>e</mi>                          </mrow>                                              </msub>                      <mi>v</mi>                    </mrow>                  </mfrac>                  <mo stretchy="false">=</mo>                  <msub>                   <mrow>                    <mn>2π</mn>                    <mi>r</mi>                   </mrow>                                          <mrow>                        <mi>n</mi>                      </mrow>                                      </msub><mi>.</mi>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123; &#123;  &#123; ital &quot;nh&quot;&#125;  over  &#123;m rSub &#123; size 8&#123;e&#125; &#125; v&#125; &#125; =2πr rSub &#123; size 8&#123;n&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    Rearranging terms, and noting that  **<math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>L</mi><mo stretchy="false">=</mo><mstyle fontstyle="italic"><mrow><mtext>mvr</mtext></mrow></mstyle></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;L= ital &quot;mvr&quot;&#125; &#123;&#125;</annotation></semantics></math> for a circular orbit, we obtain the quantization of angular momentum as the condition for allowed orbits:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <mi>L</mi>                    <mo stretchy="false">=</mo>                    <msub>                      <mi>m</mi>                                              <mrow>                          <mi>e</mi>                        </mrow>                                          </msub>                  </mrow>                  <mrow>                    <mstyle fontstyle="italic">                      <mrow>                        <msub>                          <mtext>vr</mtext>                                                      <mrow>                              <mi>n</mi>                            </mrow>                                                  </msub>                      </mrow>                    </mstyle>                    <mo stretchy="false">=</mo>                    <mi>n</mi>                  </mrow>                  <mfrac>                    <mi>h</mi>                    <mn>2π</mn>                  </mfrac>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;L=m rSub &#123; size 8&#123;e&#125; &#125;  ital &quot;vr&quot; rSub &#123; size 8&#123;n&#125; &#125; =n &#123;  &#123;h&#125;  over  &#123;2π&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>        <semantics>          <mrow>                          <mrow>                <mfenced close=")" open="(">                  <mrow>                    <mrow>                      <mi>n</mi>                      <mo stretchy="false">=</mo>                                         </mrow>                    <mn>1, 2, 3 ...</mn>                  </mrow>                </mfenced><mtext>.</mtext>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123; left (n=1, 2, 3  &quot;.&quot;   &quot;.&quot;   &quot;.&quot;  right )&#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    This is what Bohr was forced to hypothesize as the rule for allowed orbits, as stated earlier. We now realize that it is the condition for constructive interference of an electron in a circular orbit. {'Figure_31_6_1a Figure 31.6.1a} illustrates this for <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>n</mi><mo stretchy="false">=</mo><mn>3</mn></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;n=3&#125; &#123;&#125;</annotation></semantics></math> and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>n</mi><mo stretchy="false">=</mo><mn>4.</mn></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;n=3&#125; &#123;&#125;</annotation></semantics></math>
    
    
            
    
    Because of the wave character of matter, the idea of well-defined orbits gives way to a model in which there is a cloud of probability, consistent with Heisenberg’s uncertainty principle. {'Figure_31_6_2a Figure 31.6.2a} shows how this applies to the ground state of hydrogen. If you try to follow the electron in some well-defined orbit using a probe that has a small enough wavelength to get some details, you will instead knock the electron out of its orbit. Each measurement of the electron’s position will find it to be in a definite location somewhere near the nucleus. Repeated measurements reveal a cloud of probability like that in the figure, with each speck the location determined by a single measurement. There is not a well-defined, circular-orbit type of distribution. Nature again proves to be different on a small scale than on a macroscopic scale.
    
    
            
    
    There are many examples in which the wave nature of matter causes quantization in bound systems such as the atom. Whenever a particle is confined or bound to a small space, its allowed wavelengths are those which fit into that space. For example, the particle in a box model describes a particle free to move in a small space surrounded by impenetrable barriers. This is true in blackbody radiators (atoms and molecules) as well as in atomic and molecular spectra. Various atoms and molecules will have different sets of electron orbits, depending on the size and complexity of the system. When a system is large, such as a grain of sand, the tiny particle waves in it can fit in so many ways that it becomes impossible to see that the allowed states are discrete. Thus the correspondence principle is satisfied. As systems become large, they gradually look less grainy, and quantization becomes less evident. Unbound systems (small or not), such as an electron freed from an atom, do not have quantized energies, since their wavelengths are not constrained to fit in a certain volume.

  apply FullText

  ---
    30_6_0
    30_6_1

  / The Wave Nature of Matter Causes Quantization - Full Text
  path FullText
    step
      --
        30_6_0
    step
      --
        30_6_1

    