
/ Centripetal Acceleration
story 6_2
  >
    We know from kinematics that acceleration is a change in velocity, either in its magnitude or in its direction, or both. In uniform circular motion, the direction of the velocity changes constantly, so there is always an associated acceleration, even though the magnitude of the velocity might be constant. You experience this acceleration yourself when you turn a corner in your car. (If you hold the wheel steady during a turn and move at constant speed, you are in uniform circular motion.) What you notice is a sideways acceleration because you and the car are changing direction. The sharper the curve and the greater your speed, the more noticeable this acceleration will become. In this section we examine the direction and magnitude of that acceleration.
    
    {'Figure_7_2_1a Figure 7.2.1a} shows an object moving in a circular path at constant speed. The direction of the instantaneous velocity is shown at two points along the path. Acceleration is in the direction of the change in velocity, which points directly toward the center of rotation (the center of the circular path). This pointing is shown with the vector diagram in the figure. We call the acceleration of an object moving in uniform circular motion (resulting from a net external force) the  **centripetal acceleration**(<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>a</mi><mrow><mtext>c</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>); centripetal means “toward the center” or “center seeking.” 
    
    
            
    
    The direction of centripetal acceleration is toward the center of curvature, but what is its magnitude? Note that the triangle formed by the velocity vectors and the one formed by the radii <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>r</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;r&#125; &#123;&#125;</annotation></semantics></math> and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mtext>Δ</mtext><mi fontstyle="italic">s</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Δs&#125; &#123;&#125;</annotation></semantics></math> are similar. Both the triangles ABC and PQR are isosceles triangles (two equal sides). The two equal sides of the velocity vector triangle are the speeds <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>v</mi><mrow><mn>1</mn></mrow></msub><mo stretchy="false">=</mo><msub><mi>v</mi><mrow><mn>2</mn></mrow></msub></mrow><mo stretchy="false">=</mo><mi>v</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v rSub &#123; size 8&#123;1&#125; &#125; =v rSub &#123; size 8&#123;2&#125; &#125; =v&#125; &#123;&#125;</annotation></semantics></math>. Using the properties of two similar triangles, we obtain
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mfrac><mrow><mtext>Δ</mtext><mi fontstyle="italic">v</mi></mrow><mi>v</mi></mfrac><mo stretchy="false">=</mo><mfrac><mrow><mtext>Δ</mtext><mi fontstyle="italic">s</mi></mrow><mi>r</mi></mfrac></mrow></mrow><mtext>.</mtext><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;  &#123;Δv&#125;  over  &#123;v&#125; &#125; = &#123;  &#123;Δs&#125;  over  &#123;r&#125; &#125; &quot;.&quot;&#125; &#123;&#125;</annotation></semantics></math>
    
    Acceleration is <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>Δ</mtext><mi fontstyle="italic">v</mi><mo stretchy="false">/</mo><mtext>Δ</mtext><mi fontstyle="italic">t</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Δv/Δt&#125; &#123;&#125;</annotation></semantics></math>, and so we first solve this expression for <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mtext>Δ</mtext><mi fontstyle="italic">v</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Δv&#125; &#123;&#125;</annotation></semantics></math>:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mtext>Δ</mtext><mi fontstyle="italic">v</mi><mo stretchy="false">=</mo><mfrac><mi>v</mi><mi>r</mi></mfrac></mrow><mtext>Δ</mtext><mi fontstyle="italic">s</mi></mrow></mrow><mtext>.</mtext><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Δv= &#123;  &#123;v&#125;  over  &#123;r&#125; &#125; Δs&quot;.&quot;&#125; &#123;&#125;</annotation></semantics></math>
    
    Then we divide this by <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mtext>Δ</mtext><mi fontstyle="italic">t</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Δt&#125; &#123;&#125;</annotation></semantics></math>, yielding
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mfrac><mrow><mtext>Δ</mtext><mi fontstyle="italic">v</mi></mrow><mrow><mtext>Δ</mtext><mi fontstyle="italic">t</mi></mrow></mfrac><mo stretchy="false">=</mo><mrow><mfrac><mi>v</mi><mi>r</mi></mfrac><mo stretchy="false">×</mo><mfrac><mrow><mtext>Δ</mtext><mi fontstyle="italic">s</mi></mrow><mrow><mtext>Δ</mtext><mi fontstyle="italic">t</mi></mrow></mfrac></mrow></mrow></mrow><mtext>.</mtext><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;  &#123;Δv&#125;  over  &#123;Δt&#125; &#125; = &#123;  &#123;v&#125;  over  &#123;r&#125; &#125;  times  &#123;  &#123;Δs&#125;  over  &#123;Δt&#125; &#125; &quot;.&quot;&#125; &#123;&#125;</annotation></semantics></math>
    
    Finally, noting that <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mtext>Δ</mtext><mi fontstyle="italic">v</mi><mo stretchy="false">/</mo><mtext>Δ</mtext><mi fontstyle="italic">t</mi></mrow><mo stretchy="false">=</mo><msub><mi>a</mi><mrow><mtext>c</mtext></mrow></msub></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Δv/Δt=a rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> and that <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mtext>Δ</mtext><mi fontstyle="italic">s</mi><mo stretchy="false">/</mo><mtext>Δ</mtext><mi fontstyle="italic">t</mi></mrow><mo stretchy="false">=</mo><mi>v</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;Δs/Δt=v&#125; &#123;&#125;</annotation></semantics></math>, the linear or tangential speed, we see that the magnitude of the centripetal acceleration is
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msub><mi>a</mi><mrow><mtext>c</mtext></mrow></msub><mo stretchy="false">=</mo><mfrac><msup><mi>v</mi><mrow><mn>2</mn></mrow></msup><mi>r</mi></mfrac></mrow></mrow><mtext>,</mtext><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a rSub &#123; size 8&#123;c&#125; &#125; = &#123;  &#123;v rSup &#123; size 8&#123;2&#125; &#125; &#125;  over  &#123;r&#125; &#125; &quot;,&quot;&#125; &#123;&#125;</annotation></semantics></math>
    
    which is the acceleration of an object in a circle of radius <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>r</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;r&#125; &#123;&#125;</annotation></semantics></math> at a speed <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>v</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v&#125; &#123;&#125;</annotation></semantics></math>. So, centripetal acceleration is greater at high speeds and in sharp curves  (smaller radius), as you have noticed when driving a car. But it is a bit surprising that <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>a</mi><mrow><mtext>c</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is proportional to speed squared, implying, for example, that it is four times as hard to take a curve at 100 km/h than at 50 km/h. A sharp corner has a small radius, so that <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>a</mi><mrow><mtext>c</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is greater for tighter turns, as you have probably noticed.
    
    It is also useful to express <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>a</mi><mrow><mtext>c</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> in terms of angular velocity. Substituting <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>v</mi><mo stretchy="false">=</mo><mi fontstyle="italic">rω</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v=rω&#125; &#123;&#125;</annotation></semantics></math> into the above expression, we find <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>a</mi><mrow><mtext>c</mtext></mrow></msub><mo stretchy="false">=</mo><mrow><msup><mfenced close=")" open="("><mi fontstyle="italic">rω</mi></mfenced><mrow><mn>2</mn></mrow></msup><mo stretchy="false">/</mo><mi>r</mi></mrow></mrow><mo stretchy="false">=</mo><msup><mi fontstyle="italic">rω</mi><mrow><mn>2</mn></mrow></msup></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a rSub &#123; size 8&#123;c&#125; &#125; = left (rω right ) rSup &#123; size 8&#123;2&#125; &#125; /r=rω rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>. We can express the magnitude of centripetal acceleration using either of two equations:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>a</mi><mrow><mtext>c</mtext></mrow></msub><mo stretchy="false">=</mo><mfrac><msup><mi>v</mi><mrow><mn>2</mn></mrow></msup><mi>r</mi></mfrac></mrow><mi/><mi>; </mi><mrow><mspace width="0.25em"/><msub><mi>a</mi><mrow><mtext>c</mtext></mrow></msub><mo stretchy="false">=</mo><msup><mi fontstyle="italic">rω</mi><mrow><mn>2</mn></mrow></msup></mrow></mrow></mrow><mtext>.</mtext><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a rSub &#123; size 8&#123;c&#125; &#125; = &#123;  &#123;v rSup &#123; size 8&#123;2&#125; &#125; &#125;  over  &#123;r&#125; &#125; `; a rSub &#123; size 8&#123;c&#125; &#125; =rω rSup &#123; size 8&#123;2&#125; &#125; &quot;.&quot;&#125; &#123;&#125;</annotation></semantics></math>
    
    Recall that the direction of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>a</mi><mrow><mtext>c</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is toward the center. You may use whichever expression is more convenient, as illustrated in examples below.
    
    A  **centrifuge** (see {'Figure_7_2_2a Figure 7.2.2a}b) is a rotating device used to separate specimens of different densities. High centripetal acceleration significantly decreases the time it takes for separation to occur, and makes separation possible with small samples. Centrifuges are used in a variety of applications in science and medicine, including the separation of single cell suspensions such as bacteria, viruses, and blood cells from a liquid medium and the separation of macromolecules, such as DNA and protein, from a solution. Centrifuges are often rated in terms of their centripetal acceleration relative to acceleration due to gravity <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mtext>(</mtext><mi>g</mi><mtext>)</mtext></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;g&#125; &#123;&#125;</annotation></semantics></math>; maximum centripetal acceleration of several hundred thousand <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"> <semantics>  <mi>g</mi>  </semantics></math> is possible in a vacuum. Human centrifuges, extremely large centrifuges, have been used to test the tolerance of astronauts to the effects of accelerations larger than that of Earth’s gravity.
    
    
            
    
    Of course, a net external force is needed to cause any acceleration, just as Newton proposed in his second law of motion. So a net external force is needed to cause a centripetal acceleration. In <link:>, we will consider the forces involved in circular motion.

  apply FullText

  ---
    6_2_0
    6_2_1

  / Centripetal Acceleration - Full Text
  path FullText
    step
      --
        6_2_0
    step
      --
        6_2_1

    