
.. Lung Specific Testing
  >>>
    Traditional Bronchoscopy
    Traditional Bronchoscopy is typically performed by a pulmonologist. In this procedure, a flexible tube called a bronchoscope is passed down the nose or mouth into the trachea, bronchi and larger tubes in the lungs. A bronchoscopy allows the physician to actually see the central regions of the lungs and take a tissue sample for the pathologist to examine. Usually done under local anesthesia with sedation, your healthcare team may do this procedure as an outpatient, so you will not have to spend the night in the hospital. A quick procedure, a bronchoscopy usually takes less than an hour. You may spend several hours “recovering” from the procedure. During this time, the healthcare team will make sure you are awake and not having any problems before you are sent home with your family. 
    Robotic Bronchoscopy
    Robotic Bronchoscopy is a robotically-assisted procedure performed by a pulmonologist or thoracic surgeon to biopsy suspicious nodules in the lung. The procedure is as safe as a traditional bronchoscopy and provides the physician with advanced control that comes from robotic technology.
    Robotic bronchoscopy may be used to reach small tumors that are in the periphery of the lung. As the physician moves the scope deeper into the lung, the tubes get more windy and smaller. It can be very challenging for physicians to reach these small tumors using traditional, manual bronchoscopes.
    During the procedure, the physician guides the Monarch robotic bronchoscope through the mouth into the lungs using a controller that looks similar to a video game controller. This controller allows the physician to make very precise movements required to maneuver through the small tubes in the lung.
    The robotic bronchoscopy combines traditional camera views into the lung with computer-assisted navigation based on 3-D models of the patient’s own lung anatomy. Now, physicians have the benefit of seeing inside the lung while getting additional navigational guidance to reach the precise location of the tumor for biopsy.
    Electromagnetic Navigation BronchoscopyTM Procedure:
    Also known as ENBTM procedures, Electromagnetic Navigation BronchoscopyTM procedures are performed by a pulmonologist or thoracic surgeon. ENBTM procedures provide a minimally invasive approach to accessing difficult-to-reach areas of the lung aiding in the diagnosis of lung disease.
    Using your CAT scan, Covidien’s superDimensionTM navigation system with LungGPSTM technology creates a roadmap of your lungs, like a GPS (Global Positioning System) does in a car. That roadmap guides your physician through the airways of your lungs to the nodule. Your physician will insert a bronchoscope through your mouth or nose and into your lungs. With the bronchoscope in place, your physician is able to navigate through your natural airways to the lung nodule. Using tiny instruments, your physician will take a sample of the nodule for testing. In some cases, small markers may be placed near the lung nodule to help guide a physician delivering follow-up treatment or therapy.
    Thoracentesis
    Thoracentesisis performed by an interventional radiologist or pulmonologist. If any of the x-ray procedures show that fluid is present in the chest cavity outside of the lungs, your doctor may insert a thin needle into the chest between the ribs to pull out a sample of the fluid. If you are having trouble breathing because of the amount of fluid in the chest, the doctor may remove more of the fluid to help your breathing. The pathologist will examine the fluid that is removed from the chest.
    Lymph Node Biopsy
    Lymph Node Biopsy is performed by an interventional radiologist or pulmonologist. A lymph node biopsy is done after the initial diagnosis of lung cancer to see if cancer has spread from the lung to the lymph nodes. Lymph node biopsy is an important step in determining the stage of the lung cancer. This procedure can be done in one of three ways: by inserting a needle directly into the lymph node, by using a needle during a bronchoscopy or mediastinoscopy, or by complete removal of the lymph node with surgery. Any of these methods will typically be done on an outpatient basis with local anesthesia. The type of anesthesia and recovery will differ by type of procedure.
    Mediastinoscopy
    Mediastinoscopy is performed by a thoracic or general surgeon. For this procedure, you will go to the operating room where you will be given general anesthesia so that you are asleep during the procedure. Your surgeon will place a tube called a mediastinoscope through a small incision in your neck. With the bronchoscopy, the surgeon is able to see inside your lungs; during the mediastinoscopy, the surgeon will be examining the mediastinum (the area between and in front of your lungs). During this procedure, the surgeon can biopsy any lymph nodes or masses seen outside of the lungs. The mediastinoscopy may be done at the same time as a bronchoscopy; if so, both procedures will take less than two hours. If no other procedures are done, a mediastinoscopy usually takes about 45 minutes and may be done on an outpatient basis.
    Video-Assisted Thoracoscopic Surgery (VATS)
    Video-Assisted Thoracoscopic Surgery (VATS) is performed by a thoracic surgeon. For the VATS procedure, you will be taken to the operating room and will be given general anesthesia so that you are asleep during the procedure. A thoracoscope is placed into the chest through an incision in the chest wall. A thoracoscope is a camera on the end of flexible tubing that allows your doctor to look into your chest. Your surgeon can then look at the surface of the lung and the chest wall. Your doctor may use the VATS technique to remove some lung cancer tumors. This procedure is less invasive than a thoracotomy and has a shorter recovery time.
    Thoracotomy
    Thoracotomy is performed by a thoracic surgeon. A thoracotomy is something like a VATS procedure; however, instead of inserting a scope through a small incision, your surgeon will make a larger incision into the chest in order to see the lung directly. In a thoracotomy, a tumor, lung tissue or lymph nodes may be removed. This procedure is done under general anesthesia and you will probably be in the hospital for 3 to 5 days. Your surgeon may elect to do the VATS procedure instead of a thoracotomy.


.. Additional Evaluation
  >>>
    ### Pulmonary Function Test (PFT)
    The PFT is a breathing test to determine how well your lungs are working. This non-painful test may be performed in your pulmonologist’s office or in the hospital on an outpatient basis.

    ### Pulse Oximetry (Pulse Ox)
    One of the common symptoms you might experience with lung cancer is shortness of breath. Your team may use a device called a pulse oximeter to measure the level of oxygen in your blood. The pulse oximeter is placed on your fingertip for a minute. A low level of oxygen in your blood may prompt your doctor to order extra oxygen for you during your illness.

    ### High Altitude Simulation Test (HAST)
    The High Altitude Simulation Test (HAST) is a test your doctor may use to find out if you will need oxygen when you fly or travel to a high altitude city or country.

    You may also hear HAST called a “hypoxia altitude simulation test.” When you fly or are at a high altitude, you may be at risk for cardiopulmonary (heart or lung) problems due to the lower oxygen available. During the HAST exam, your doctor will take your blood pressure, pulse and respiratory rate before the test begins and while you are breathing your normal air mixture. The doctor may also connect you to a cardiac monitor that will allow the team to monitor your heart rhythm. After those initial measurements, you will breathe air that contains a lower percentage of oxygen than you may be used to. During the 20 to 30 minutes of the test, your doctor will monitor you for any significant symptoms you have while breathing the air with lower oxygen. If you have symptoms during the test, the doctor will test you again while giving you oxygen to ensure that the additional oxygen will prevent the symptoms. The doctor doing the test will send results of the HAST to your oncologist and pulmonologist.

    ### Complete Blood Count (CBC)
    Chemotherapy and radiation therapy can temporarily affect the cells of the bone marrow that produce normal blood cells, so your healthcare team will want to keep track of this important test before and during treatment. A CBC can also alert your doctor to certain abnormalities in the blood that may indicate problems with the function of your kidneys or liver. Your doctor will order a CBC on a regular basis to determine if your blood has the correct number and types of cells.

    ### Sputum Cytology
    For the sputum cytology test, a member of your healthcare team will ask you to cough up a sample of mucus (sputum) from as deep in your lungs as possible. Lung cancer cells can shed into the airway and mix with mucus there. When you produce a sputum sample, the cytologist or pathologist will examine the sputum looking for normal or abnormal cells. Cytology is the study of cells and a cytologist is a scientist who studies the identification of cancer cells.
