
/ Microscopes
story 26_4
  >
    Although the eye is marvelous in its ability to see objects large and small, it obviously has limitations to the smallest details it can detect. Human desire to see beyond what is possible with the naked eye led to the use of optical instruments. In this section we will examine microscopes, instruments for enlarging the detail that we cannot see with the unaided eye. The microscope is a multiple-element system having more than a single lens or mirror. (See {'Figure_27_4_1 Figure 27.4.1}) A microscope can be made from two convex lenses. The image formed by the first element becomes the object for the second element. The second element forms its own image, which is the object for the third element, and so on. Ray tracing helps to visualize the image formed. If the device is composed of thin lenses and mirrors that obey the thin lens equations, then it is not difficult to describe their behavior numerically. 
    
    
            
    
    Microscopes were first developed in the early 1600s by eyeglass makers in The Netherlands and Denmark. The simplest  **compound microscope** is constructed from two convex lenses as shown schematically in {'Figure_27_4_2 Figure 27.4.2}. The first lens is called the  **objective lens**, and has typical magnification values from <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mn>5×</mn></mrow></semantics></math>  to <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mn>100×</mn></mrow></semantics></math>. In standard microscopes, the objectives are mounted such that when you switch between objectives, the sample remains in focus. Objectives arranged in this way are described as parfocal. The second, the  **eyepiece**, also referred to as the ocular, has several lenses which slide inside a cylindrical barrel. The focusing ability is provided by the movement of both the objective lens and the eyepiece. The purpose of a microscope is to magnify small objects, and both lenses contribute to the final magnification. Additionally, the final enlarged image is produced in a location far enough from the observer to be easily viewed, since the eye cannot focus on objects or images that are too close.
    
    
            
    
    To see how the microscope in {'Figure_27_4_2 Figure 27.4.2} forms an image, we consider its two lenses in succession. The object is slightly farther away from the objective lens than its focal length <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>f</mi><mrow><mtext>o</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f rSub &#123; size 8&#123;o&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>, producing a case 1 image that is larger than the object. This first image is the object for the second lens, or eyepiece. The eyepiece is intentionally located so it can further magnify the image. The eyepiece is placed so that the first image is closer to it than its focal length <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>f</mi><mrow><mtext>e</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f rSub &#123; size 8&#123;e&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>. Thus the eyepiece acts as a magnifying glass, and the final image is made even larger. The final image remains inverted, but it is farther from the observer, making it easy to view (the eye is most relaxed when viewing distant objects and normally cannot focus closer than 25 cm). Since each lens produces a magnification that multiplies the height of the image, it is apparent that the overall magnification <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>m</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;m&#125; &#123;&#125;</annotation></semantics></math> is the product of the individual magnifications:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mi>m</mi><mo stretchy="false">=</mo><msub><mi>m</mi><mrow><mtext>o</mtext></mrow></msub></mrow><msub><mi>m</mi><mrow><mtext>e</mtext></mrow></msub><mo>,</mo></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;m=m rSub &#123; size 8&#123;o&#125; &#125; m rSub &#123; size 8&#123;e&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    where <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>m</mi><mrow><mtext>o</mtext></mrow></msub></mrow><mrow/></mrow></semantics></math> is the magnification of the objective and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>m</mi><mrow><mtext>e</mtext></mrow></msub></mrow><mrow/></mrow></semantics></math> is the magnification of the eyepiece. This equation can be generalized for any combination of thin lenses and mirrors that obey the thin lens equations.
    
    Normal optical microscopes can magnify up to  <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mn>1500×</mn></mrow></semantics></math>  with a theoretical resolution of  <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mo>–</mo><mn>0.2</mn><mspace width="0.25em"/><mtext>μm</mtext></mrow></semantics></math>. The lenses can be quite complicated and are composed of multiple elements to reduce aberrations. Microscope objective lenses are particularly important as they primarily gather light from the specimen. Three parameters describe microscope objectives: the  **numerical aperture (NA)**, the magnification <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mo stretchy="false">(</mo><mi>m</mi><mo stretchy="false">)</mo></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;  \( m \) &#125; &#123;&#125;</annotation></semantics></math>, and the working distance. The <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mstyle fontstyle="italic"><mrow><mtext>NA</mtext></mrow></mstyle></mrow><mrow/></mrow></semantics></math> is related to the light gathering ability of a lens and is obtained using the angle of acceptance <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>θ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ&#125; &#123;&#125;</annotation></semantics></math> formed by the maximum cone of rays focusing on the specimen (see {'Figure_27_4_3 Figure 27.4.3}(a)) and is given by
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mstyle fontstyle="italic"><mrow><mtext>NA</mtext></mrow></mstyle><mo stretchy="false">=</mo><mi>n</mi></mrow><mspace width="0.25em"/><mtext>sin</mtext><mspace width="0.25em"/><mi>α,</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;NA&quot;=n&quot;sin&quot;α&#125; &#123;&#125;</annotation></semantics></math>
    
    where <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>n</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;n&#125; &#123;&#125;</annotation></semantics></math> is the refractive index of the medium between the lens and the specimen and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>α</mi><mo stretchy="false">=</mo><mrow><mi>θ</mi><mo stretchy="false">/</mo><mn>2</mn></mrow></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;α= &#123;θ&#125; slash &#123;2&#125; &#125; &#123;&#125;</annotation></semantics></math>. As the angle of acceptance given by  *θ size 12&#123;θ&#125; &#123;&#125;* increases,  <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mstyle fontstyle="italic"><mrow><mtext>NA</mtext></mrow></mstyle></mrow><mrow/></mrow></semantics></math>  becomes larger and more light is gathered from a smaller focal region giving higher resolution. A <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mn>0</mn><mtext>.</mtext><mtext>75</mtext><mstyle fontstyle="italic"><mrow><mtext>NA</mtext></mrow></mstyle></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;0 &quot;.&quot; &quot;75&quot; ital &quot;NA&quot;&#125; &#123;&#125;</annotation></semantics></math> objective gives more detail than a <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mn>0</mn><mtext>.</mtext><mtext>10</mtext><mrow><mtext fontstyle="italic">NA</mtext></mrow></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;0 &quot;.&quot; &quot;10&quot; ital &quot;NA&quot;&#125; &#123;&#125;</annotation></semantics></math> objective. 
    
    
            
    
    While the numerical aperture can be used to compare resolutions of various objectives, it does not indicate how far the lens could be from the specimen. This is specified by the “working distance,” which is the distance (in mm usually) from the front lens element of the objective to the specimen, or cover glass. The higher the <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mstyle fontstyle="italic"><mrow><mtext>NA</mtext></mrow></mstyle></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;NA&quot;&#125; &#123;&#125;</annotation></semantics></math> the closer the lens will be to the specimen and the more chances there are of breaking the cover slip and damaging both the specimen and the lens. The focal length of an objective lens is different than the working distance. This is because objective lenses are made of a combination of lenses and the focal length is measured from inside the barrel. The working distance is a parameter that microscopists can use more readily as it is measured from the outermost lens. The working distance decreases as the <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mstyle fontstyle="italic"><mrow><mtext>NA</mtext></mrow></mstyle></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;NA&quot;&#125; &#123;&#125;</annotation></semantics></math> and magnification both increase.
    
    The term <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>f</mi><mo stretchy="false">/</mo><mrow/></mrow><mo>#</mo></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;f&#125; slash &#123;#&#125; &#125; &#123;&#125;</annotation></semantics></math> in general is called the  *f size 12&#123;f&#125; &#123;&#125;*-number and is used to denote the light per unit area reaching the image plane. In photography, an image of an object at infinity is formed at the focal point and the <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>f</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f&#125; &#123;&#125;</annotation></semantics></math>-number is given by the ratio of the focal length <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>f</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f&#125; &#123;&#125;</annotation></semantics></math> of the lens and the diameter  *D size 12&#123;D&#125; &#123;&#125;* of the aperture controlling the light into the lens (see {'Figure_27_4_3 Figure 27.4.3}(b)). If the acceptance angle is small the  *NA size 12&#123; ital "NA"&#125; &#123;&#125;* of the lens can also be used as given below. 
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mi>f</mi>                  <mrow>                    <mrow>                      <mtext>/#</mtext>                      <mo stretchy="false">=</mo>                      <mfrac>                        <mi>f</mi>                        <mi>D</mi>                      </mfrac>                    </mrow>                    <mo stretchy="false">≈</mo>                    <mfrac>                      <mn>1</mn>                      <mrow>                        <mn>2</mn>                        <mstyle fontstyle="italic">                          <mrow>                            <mtext>NA</mtext>                          </mrow>                        </mstyle>                      </mrow>                    </mfrac><mo>.</mo>                  </mrow>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;f&quot;/#&quot;= &#123;  &#123;f&#125;  over  &#123;D&#125; &#125;  approx  &#123;  &#123;1&#125;  over  &#123;2 ital &quot;NA&quot;&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    As the <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>f</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;f&#125; &#123;&#125;</annotation></semantics></math>-number decreases, the camera is able to gather light from a larger angle, giving wide-angle photography. As usual there is a trade-off. A greater <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>f</mi><mo stretchy="false">/</mo><mrow/><mo>#</mo></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;f&#125; slash &#123;#&#125; &#125; &#123;&#125;</annotation></semantics></math> means less light reaches the image plane. A setting of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>f</mi><mo stretchy="false">/</mo><mtext>16</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;f&#125; slash &#123;&quot;16&quot;&#125; &#125; &#123;&#125;</annotation></semantics></math> usually allows one to take pictures in bright sunlight as the aperture diameter is small. In optical fibers, light needs to be focused into the fiber. {'Figure_27_4_4 Figure 27.4.4} shows the angle used in calculating the  *NA size 12&#123; ital "NA"&#125; &#123;&#125;* of an optical fiber.
    
    
            
    
    Can the <math xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mstyle fontstyle="italic"><mrow><mtext>NA</mtext></mrow></mstyle></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;NA&quot;&#125; &#123;&#125;</annotation></semantics></math> be larger than 1.00? The answer is ‘yes’ if we use immersion lenses in which a medium such as oil, glycerine or water is placed between the objective and the microscope cover slip. This minimizes the mismatch in refractive indices as light rays go through different media, generally providing a greater light-gathering ability and an increase in resolution. {'Figure_27_4_5 Figure 27.4.5} shows light rays when using air and immersion lenses. 
    
    
            
    
    When using a microscope we do not see the entire extent of the sample. Depending on the eyepiece and objective lens we see a restricted region which we say is the field of view. The objective is then manipulated in two-dimensions above the sample to view other regions of the sample. Electronic scanning of either the objective or the sample is used in scanning microscopy. The image formed at each point during the scanning is combined using a computer to generate an image of a larger region of the sample at a selected magnification.
    
    When using a microscope, we rely on gathering light to form an image. Hence most specimens need to be illuminated, particularly at higher magnifications, when observing details that are so small that they reflect only small amounts of light. To make such objects easily visible, the intensity of light falling on them needs to be increased. Special illuminating systems called condensers are used for this purpose. The type of condenser that is suitable for an application depends on how the specimen is examined, whether by transmission, scattering or reflecting. See {'Figure_27_4_6 Figure 27.4.6} for an example of each. White light sources are common and lasers are often used. Laser light illumination tends to be quite intense and it is important to ensure that the light does not result in the degradation of the specimen. 
    
    
            
    
    We normally associate microscopes with visible light but x ray and electron microscopes provide greater resolution. The focusing and basic physics is the same as that just described, even though the lenses require different technology. The electron microscope requires vacuum chambers so that the electrons can proceed unheeded. Magnifications of 50 million times provide the ability to determine positions of individual atoms within materials. An electron microscope is shown in {'Figure_27_4_7 Figure 27.4.7}. We do not use our eyes to form images; rather images are recorded electronically and displayed on computers. In fact observing and saving images formed by optical microscopes on computers is now done routinely. Video recordings of what occurs in a microscope can be made for viewing by many people at later dates. Physics provides the science and tools needed to generate the sequence of time-lapse images of meiosis similar to the sequence sketched in {'Figure_27_4_8 Figure 27.4.8}.
    
    
            
    
    
            

  apply FullText

  ---
    26_4_0
    26_4_1

  / Microscopes - Full Text
  path FullText
    step
      --
        26_4_0
    step
      --
        26_4_1

    