
/ Energy and the Simple Harmonic Oscillator
story 16_5
  >
    To study the energy of a simple harmonic oscillator, we first consider all the forms of energy it can have We know from <link:> that the energy stored in the deformation of a simple harmonic oscillator is a form of potential energy given by:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow><msub>                  <mtext>PE</mtext>                                         <mtext>el</mtext></msub>                                      <mo stretchy="false">=</mo>                    <mfrac>                      <mn>1</mn>                      <mn>2</mn>                    </mfrac>                                   <mrow>                      <msup>                        <mi mathvariant="italic">kx</mi>                                                  <mrow>                            <mn>2</mn>                          </mrow>                                              </msup>                    </mrow>                </mrow>              </mrow>                        <mrow/><mo>.</mo>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;&quot;PE&quot; size 8&#123;&quot;el&quot;&#125;= &#123;  &#123;1&#125;  over  &#123;2&#125; &#125;  ital &quot;kx&quot; rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    Because a simple harmonic oscillator has no dissipative forces, the other important form of energy is kinetic energy <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>KE</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;KE&quot;&#125; &#123;&#125;</annotation></semantics></math>. Conservation of energy for these two forms is:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                      <mrow>                        <mtext>KE</mtext>                      </mrow>                    <mo stretchy="false">+</mo>                      <mrow>                        <msub>                          <mtext>PE</mtext>                                                      <mrow>                              <mtext>el</mtext>                                        </mrow>                                                  </msub>                      </mrow>                  </mrow>                  <mo stretchy="false">=</mo>                  <mtext>constant</mtext>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123; ital &quot;KE&quot;+ ital &quot;PE&quot; rSub &#123; size 8&#123;e1&#125; &#125; =&quot;constant&quot;&#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    or
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mfrac>                    <mn>1</mn>                    <mn>2</mn>                  </mfrac>                  <mrow>                                       <mrow>                        <msup>   <mstyle fontstyle="italic">                          <mtext>mv</mtext>                                     </mstyle>                            <mrow>                              <mn>2</mn>                            </mrow>                                                  </msup>                      </mrow>                             <mo stretchy="false">+</mo>                    <mfrac>                      <mn>1</mn>                      <mn>2</mn>                    </mfrac>                  </mrow>                  <mrow>                                  <mrow>                        <msup>        <mstyle fontstyle="italic">                          <mtext>kx</mtext>                                        </mstyle>                            <mrow>                              <mn>2</mn>                            </mrow>                                                  </msup>                      </mrow>                          <mo stretchy="false">=</mo>                    <mtext>constant.</mtext>                  </mrow>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123; &#123;  &#123;1&#125;  over  &#123;2&#125; &#125;  ital &quot;mv&quot; rSup &#123; size 8&#123;2&#125; &#125; + &#123;  &#123;1&#125;  over  &#123;2&#125; &#125;  ital &quot;kx&quot; rSup &#123; size 8&#123;2&#125; &#125; =&quot;constant&quot;&#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    This statement of conservation of energy is valid for  *all* simple harmonic oscillators, including ones where the gravitational force plays a role
    
    Namely, for a simple pendulum we replace the velocity with <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>v</mi><mo stretchy="false">=</mo><mi fontstyle="italic">Lω</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v=Lω&#125; &#123;&#125;</annotation></semantics></math>, the spring constant with <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>k</mi><mo stretchy="false">=</mo><mrow><mstyle fontstyle="italic"><mrow><mtext>mg</mtext></mrow></mstyle><mo stretchy="false">/</mo><mi>L</mi></mrow></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;k= ital &quot;mg&quot;/L&#125; &#123;&#125;</annotation></semantics></math>, and the displacement term with <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>x</mi><mo stretchy="false">=</mo><mi fontstyle="italic">Lθ</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;x=Lθ&#125; &#123;&#125;</annotation></semantics></math>. Thus
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mfrac>                    <mn>1</mn>                    <mn>2</mn>                  </mfrac>                             <mrow>                      <msup>         <mstyle fontstyle="italic">                        <mtext>mL</mtext>                               </mstyle>                          <mrow>                            <mn>2</mn>                          </mrow>                                              </msup>                    </mrow>                             <mrow>                    <msup>                      <mi>ω</mi>                                              <mrow>                          <mn>2</mn>                        </mrow>                                          </msup>                    <mo stretchy="false">+</mo>                    <mfrac>                      <mn>1</mn>                      <mn>2</mn>                    </mfrac>                  </mrow>                  <mstyle fontstyle="italic">                    <mrow>                      <mtext>mgL</mtext>                    </mrow>                  </mstyle>                  <mrow>                    <msup>                      <mi>θ</mi>                                              <mrow>                          <mn>2</mn>                        </mrow>                                          </msup>                    <mo stretchy="false">=</mo>                    <mtext>constant.</mtext>                  </mrow>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123; &#123;  &#123;1&#125;  over  &#123;2&#125; &#125;  ital &quot;mL&quot; rSup &#123; size 8&#123;2&#125; &#125; ω rSup &#123; size 8&#123;2&#125; &#125; + &#123;  &#123;1&#125;  over  &#123;2&#125; &#125;  ital &quot;mgL&quot;θ rSup &#123; size 8&#123;2&#125; &#125; =&quot;constant&quot;&#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    In the case of undamped simple harmonic motion, the energy oscillates back and forth between kinetic and potential, going completely from one to the other as the system oscillates. So for the simple example of an object on a frictionless surface attached to a spring, as shown again in {'Figure_17_5_1a Figure 17.5.1a}, the motion starts with all of the energy stored in the spring. As the object starts to move, the elastic potential energy is converted to kinetic energy, becoming entirely kinetic energy at the equilibrium position. It is then converted back into elastic potential energy by the spring, the velocity becomes zero when the kinetic energy is completely converted, and so on. This concept provides extra insight here and in later applications of simple harmonic motion, such as alternating current circuits.
    
    
            
    
    The conservation of energy principle can be used to derive an expression for velocity <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>v</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v&#125; &#123;&#125;</annotation></semantics></math>. If we start our simple harmonic motion with zero velocity and maximum displacement (<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>x</mi><mo stretchy="false">=</mo><mi>X</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;x=X&#125; &#123;&#125;</annotation></semantics></math>), then the total energy is 
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mfrac><mn>1</mn><mn>2</mn></mfrac><mrow><msup><mstyle fontstyle="italic"><mtext>kX</mtext></mstyle><mrow><mn>2</mn></mrow></msup></mrow></mrow></mrow><mrow/><mo>.</mo></mrow><annotation encoding="StarMath 5.0"> size 12&#123; &#123;  &#123;1&#125;  over  &#123;2&#125; &#125;  ital &quot;kX&quot; rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    This total energy is constant and is shifted back and forth between kinetic energy and potential energy, at most times being shared by each. The conservation of energy for this system in equation form is thus:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mfrac>                    <mn>1</mn>                    <mn>2</mn>                  </mfrac>                  <mrow>                                      <mrow>                        <msup>    <mstyle fontstyle="italic">                          <mtext>mv</mtext>                              </mstyle>                            <mrow>                              <mn>2</mn>                            </mrow>                                                  </msup>                      </mrow>                                    <mo stretchy="false">+</mo>                    <mfrac>                      <mn>1</mn>                      <mn>2</mn>                    </mfrac>                  </mrow>                  <mrow>                                         <mrow>                        <msup> <mstyle fontstyle="italic">                          <mtext>kx</mtext>                               </mstyle>                            <mrow>                              <mn>2</mn>                            </mrow>                                                  </msup>                      </mrow>                                   <mo stretchy="false">=</mo>                    <mfrac>                      <mn>1</mn>                      <mn>2</mn>                    </mfrac>                  </mrow>                                    <mrow>                      <msup>  <mstyle fontstyle="italic">                        <mtext>kX</mtext>                         </mstyle>                                   <mrow>                            <mn>2</mn>                          </mrow>                                              </msup>                    </mrow>                        </mrow>              </mrow>            <mo>.</mo>            <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123; &#123;  &#123;1&#125;  over  &#123;2&#125; &#125;  ital &quot;mv&quot; rSup &#123; size 8&#123;2&#125; &#125; + &#123;  &#123;1&#125;  over  &#123;2&#125; &#125;  ital &quot;kx&quot; rSup &#123; size 8&#123;2&#125; &#125; = &#123;  &#123;1&#125;  over  &#123;2&#125; &#125;  ital &quot;kX&quot; rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    Solving this equation for  *v size 12&#123;v&#125; &#123;&#125;* yields:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mi>v</mi>                  <mo stretchy="false">=</mo>                  <mrow>                    <mo stretchy="false">±</mo>                    <msqrt>                      <mrow>                        <mfrac>                          <mi>k</mi>                          <mi>m</mi>                        </mfrac>                        <mfenced close=")" open="(">                          <mrow>                            <msup>                              <mi>X</mi>                                                              <mrow>                                  <mn>2</mn>                                </mrow>                                                          </msup>                            <mo stretchy="false">−</mo>                            <msup>                              <mi>x</mi>                                                              <mrow>                                  <mn>2</mn>                                </mrow>                                                          </msup>                          </mrow>                        </mfenced>                      </mrow>                    </msqrt>                  </mrow>                </mrow>              </mrow>            <mo>.</mo>            <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;v= +-  sqrt &#123; &#123;  &#123;k&#125;  over  &#123;m&#125; &#125;  left (X rSup &#123; size 8&#123;2&#125; &#125;  - x rSup &#123; size 8&#123;2&#125; &#125;  right )&#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    Manipulating this expression algebraically gives:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <mi>v</mi>                    <mo stretchy="false">=</mo>                    <mrow>                      <mo stretchy="false">±</mo>                      <msqrt>                        <mfrac>                          <mi>k</mi>                          <mi>m</mi>                        </mfrac>                      </msqrt>                    </mrow>                  </mrow>                  <mi>X</mi>                  <msqrt>                    <mrow>                      <mn>1</mn>                      <mo stretchy="false">−</mo>                      <mfrac>                        <msup>                          <mi>x</mi>                                                      <mrow>                              <mn>2</mn>                            </mrow>                                                  </msup>                        <msup>                          <mi>X</mi>                                                      <mrow>                              <mn>2</mn>                            </mrow>                                                  </msup>                      </mfrac>                    </mrow>                  </msqrt>                </mrow>              </mrow>                        <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;v= +-  sqrt &#123; &#123;  &#123;k&#125;  over  &#123;m&#125; &#125; &#125; X sqrt &#123;1 -  &#123;  &#123;x rSup &#123; size 8&#123;2&#125; &#125; &#125;  over  &#123;X rSup &#123; size 8&#123;2&#125; &#125; &#125; &#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    and so
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <mi>v</mi>                    <mo stretchy="false">=</mo>                    <mrow>                      <mo stretchy="false">±</mo><msub>                      <mi>v</mi><mtext>max</mtext></msub>                    </mrow>                  </mrow>                                      <mrow>                      <mrow>                                                <msqrt>                          <mrow>                            <mn>1</mn>                            <mo stretchy="false">−</mo>                            <mfrac>                              <msup>                                <mi>x</mi>                                                                  <mrow>                                    <mn>2</mn>                                  </mrow>                                                              </msup>                              <msup>                                <mi>X</mi>                                                                  <mrow>                                    <mn>2</mn>                                  </mrow>                                                              </msup>                            </mfrac>                          </mrow>                        </msqrt>                      </mrow>                    </mrow>                                  </mrow>              </mrow>            <mo>,</mo>            <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;v= +- v size 8&#123;&quot;max&quot; sqrt &#123;1 -  &#123;  &#123;x rSup &#123; size 8&#123;2&#125; &#125; &#125;  over  &#123;X rSup &#123; size 8&#123;2&#125; &#125; &#125; &#125; &#125; &#125;&#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    where
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow><msub>                  <mi>v</mi><mtext>max</mtext></msub>                  <mrow>                                                                                 <mo stretchy="false">=</mo>                    <msqrt>                      <mfrac>                        <mi>k</mi>                        <mi>m</mi>                      </mfrac>                    </msqrt>                  </mrow>                  <mi>X</mi>                </mrow>              </mrow>            <mo>.</mo>                    <mrow/>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;v size 8&#123;&quot;max&quot;&#125;= sqrt &#123; &#123;  &#123;k&#125;  over  &#123;m&#125; &#125; &#125; X&#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    From this expression, we see that the velocity is a maximum (<math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>v</mi><mtext>max</mtext></msub></mrow><mrow/></mrow></semantics></math>) at <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>x</mi><mo stretchy="false">=</mo><mn>0</mn></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;x=0&#125; &#123;&#125;</annotation></semantics></math>, as stated earlier in <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>v</mi><mrow><mfenced close=")" open="("><mi>t</mi></mfenced><mo stretchy="false">=</mo><mrow><mo stretchy="false">−</mo></mrow></mrow><msub><mi>v</mi><mtext>max</mtext></msub><mspace width="0.25em"/><mtext>sin</mtext><mspace width="0.25em"/><mfrac><mrow><mn>2π</mn><mi>t</mi></mrow><mi>T</mi></mfrac></mrow></mrow><mrow/></mrow></semantics></math> *.* Notice that the maximum velocity depends on three factors. Maximum velocity is directly proportional to amplitude. As you might guess, the greater the maximum displacement the greater the maximum velocity. Maximum velocity is also greater for stiffer systems, because they exert greater force for the same displacement. This observation is seen in the expression for <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>v</mi><mrow><mtext>max</mtext></mrow></msub><mo>;</mo></mrow><mrow/></mrow></semantics></math> it is proportional to the square root of the force constant <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>k</mi></mrow><mrow/></mrow></semantics></math>. Finally, the maximum velocity is smaller for objects that have larger masses, because the maximum velocity is inversely proportional to the square root of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>m</mi></mrow><mrow/></mrow></semantics></math>. For a given force, objects that have large masses accelerate more slowly.
    
    A similar calculation for the simple pendulum produces a similar result, namely:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <msub>                      <mi>ω</mi>                                              <mrow>                          <mtext>max</mtext>                        </mrow>                                          </msub>                    <mo stretchy="false">=</mo>                    <msqrt>                      <mfrac>                        <mi>g</mi>                        <mi>L</mi>                      </mfrac>                    </msqrt>                  </mrow>                  <msub>                    <mi>θ</mi>                                          <mrow>                        <mtext>max</mtext>                      </mrow>                                      </msub>                </mrow>              </mrow>                        <mrow/><mo>.</mo>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;ω rSub &#123; size 8&#123;&quot;max&quot;&#125; &#125; = sqrt &#123; &#123;  &#123;g&#125;  over  &#123;L&#125; &#125; &#125; θ rSub &#123; size 8&#123;&quot;max&quot;&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     

  apply FullText

  ---
    16_5_0
    16_5_1

  / Energy and the Simple Harmonic Oscillator - Full Text
  path FullText
    step
      --
        16_5_0
    step
      --
        16_5_1

    