
/ Multiple Equilibria
story 15_3
  >
    There are times when one equilibrium reaction does not adequately describe the system being studied. Sometimes we have more than one type of equilibrium occurring at once (for example, an acid-base reaction and a precipitation reaction).
    
    The ocean is a unique example of a system with  **multiple equilibria**, or multiple states of solubility equilibria working simultaneously. Carbon dioxide in the air dissolves in sea water, forming carbonic acid (H<sub>2</sub>CO<sub>3</sub>). The carbonic acid then ionizes to form hydrogen ions and bicarbonate ions <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mo stretchy="false">(</mo><msub><mrow><mtext>HCO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">)</mo><mo>,</mo></mrow></math> which can further ionize into more hydrogen ions and carbonate ions <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mo stretchy="false">(</mo><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mtext>2−</mtext></msup><mo stretchy="false">)</mo><mo>:</mo></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>CO</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mo stretchy="false">⇌</mo><msub><mrow><mtext>CO</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>CO</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">⇌</mo><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo stretchy="false">⇌</mo><msup><mtext>H</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mrow><mtext>HCO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>HCO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo stretchy="false">⇌</mo><msup><mtext>H</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mrow><mtext>2−</mtext></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
    
    The excess H<sup>+</sup> ions make seawater more acidic. Increased ocean acidification can then have negative impacts on reef-building coral, as they cannot absorb the calcium carbonate they need to grow and maintain their skeletons ({'Figure_15_3_CoralReef Figure 15.3.CoralReef}). This in turn disrupts the local biosystem that depends upon the health of the reefs for its survival. If enough local reefs are similarly affected, the disruptions to sea life can be felt globally. The world’s oceans are presently in the midst of a period of intense acidification, believed to have begun in the mid-nineteenth century, and which is now accelerating at a rate faster than any change to oceanic pH in the last 20 million years.
    
    
            
    
    Slightly soluble solids derived from weak acids generally dissolve in strong acids, unless their solubility products are extremely small. For example, we can dissolve CuCO<sub>3</sub>, FeS, and Ca<sub>3</sub>(PO<sub>4</sub>)<sub>2</sub> in HCl because their basic anions react to form weak acids (H<sub>2</sub>CO<sub>3</sub>, H<sub>2</sub>S, and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">)</mo><mo>.</mo></mrow></math> The resulting decrease in the concentration of the anion results in a shift of the equilibrium concentrations to the right in accordance with Le Châtelier’s principle.
    
    Of particular relevance to us is the dissolution of hydroxylapatite, Ca<sub>5</sub>(PO<sub>4</sub>)<sub>3</sub>OH, in acid. Apatites are a class of calcium phosphate minerals ({'Figure_15_3_Apatite Figure 15.3.Apatite}); a biological form of hydroxylapatite is found as the principal mineral in the enamel of our teeth. A mixture of hydroxylapatite and water (or saliva) contains an equilibrium mixture of solid Ca<sub>5</sub>(PO<sub>4</sub>)<sub>3</sub>OH and dissolved Ca<sup>2+</sup>, <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mrow><mtext>3−</mtext></mrow></msup><mo>,</mo></mrow></math> and OH<sup>–</sup> ions:
    
    <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>Ca</mtext><mtext>5</mtext></msub><mo stretchy="false">(</mo><msub><mrow><mtext>P</mtext><msub><mrow><mtext>O</mtext></mrow><mn>4</mn></msub><mo stretchy="false">)</mo></mrow><mn>3</mn></msub><mtext>OH</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><mn>5</mn><msup><mrow><mtext>Ca</mtext></mrow><mrow><mtext>2+</mtext></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><mn>3</mn><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mrow><mtext>3−</mtext></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
    
    
            
    
    When exposed to acid, phosphate ions react with hydronium ions to form hydrogen phosphate ions and ultimately, phosphoric acid:
    
    <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mrow><mtext>3−</mtext></mrow></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mn>+</mn></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mrow><mtext>2−</mtext></mrow></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi fontstyle="italic">l</mi><mo stretchy="false">)</mo></mrow></math>
    
    <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mrow><mtext>2−</mtext></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mn>+</mn></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi fontstyle="italic">l</mi><mo stretchy="false">)</mo></mrow></math>
    
    <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mn>+</mn></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>3</mn></msub><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi fontstyle="italic">l</mi><mo stretchy="false">)</mo></mrow></math>
    
    Hydroxide ion reacts to form water:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mn>+</mn></msup><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><mn>2</mn><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext></mrow></math>
    
    These reactions decrease the phosphate and hydroxide ion concentrations, and additional hydroxylapatite dissolves in an acidic solution in accord with Le Châtelier’s principle. Our teeth develop cavities when acid waste produced by bacteria growing on them causes the hydroxylapatite of the enamel to dissolve. Fluoride toothpastes contain sodium fluoride, NaF, or stannous fluoride [more properly named tin(II) fluoride], SnF<sub>2</sub>. They function by replacing the OH<sup>–</sup> ion in hydroxylapatite with F<sup>–</sup> ion, producing fluorapatite, Ca<sub>5</sub>(PO<sub>4</sub>)<sub>3</sub>F:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>NaF</mtext><mo>+</mo><msub><mrow><mtext>Ca</mtext></mrow><mtext>5</mtext></msub><mo stretchy="false">(</mo><msub><mrow><mtext>P</mtext><msub><mrow><mtext>O</mtext></mrow><mn>4</mn></msub><mo stretchy="false">)</mo></mrow><mn>3</mn></msub><mtext>OH</mtext><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mrow><mtext>Ca</mtext></mrow><mtext>5</mtext></msub><mo stretchy="false">(</mo><msub><mrow><mtext>P</mtext><msub><mrow><mtext>O</mtext></mrow><mn>4</mn></msub><mo stretchy="false">)</mo></mrow><mn>3</mn></msub><mtext>F</mtext><mo>+</mo><msup><mrow><mtext>Na</mtext></mrow><mn>+</mn></msup><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup></mrow></math>
    
    The resulting Ca<sub>5</sub>(PO<sub>4</sub>)<sub>3</sub>F is slightly less soluble than Ca<sub>5</sub>(PO<sub>4</sub>)<sub>3</sub>OH, and F<sup>–</sup> is a weaker base than OH<sup>–</sup>. Both of these factors make the fluorapatite more resistant to attack by acids than hydroxylapatite. See the Chemistry in Everyday Life feature on the role of fluoride in preventing tooth decay for more information.
    
    When acid rain attacks limestone or marble, which are calcium carbonates, a reaction occurs that is similar to the acid attack on hydroxylapatite. The hydronium ion from the acid rain combines with the carbonate ion from calcium carbonates and forms the hydrogen carbonate ion, a weak acid:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mrow><mtext>2−</mtext></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mrow><mtext>HCO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo></mrow></math>
    
    Calcium hydrogen carbonate, Ca(HCO<sub>3</sub>)<sub>2</sub>, is soluble, so limestone and marble objects slowly dissolve in acid rain.
    
    If we add calcium carbonate to a concentrated acid, hydronium ion reacts with the carbonate ion according to the equation:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mn>2</mn><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mrow><mtext>2−</mtext></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><mn>2</mn><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo></mrow></math>
    
    (Acid rain is usually not sufficiently acidic to cause this reaction; however, laboratory acids are.) The solution may become saturated with the weak electrolyte carbonic acid, which is unstable, and carbon dioxide gas can be evolved:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mrow><mtext>CO</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo></mrow></math>
    
    These reactions decrease the carbonate ion concentration, and additional calcium carbonate dissolves. If enough acid is present, the concentration of carbonate ion is reduced to such a low level that the reaction quotient for the dissolution of calcium carbonate remains less than the solubility product of calcium carbonate, even after all of the calcium carbonate has dissolved.
    
    Therefore, precise calculations of the solubility of solids from the solubility product are limited to cases in which the only significant reaction occurring when the solid dissolves is the formation of its ions.

  apply FullText

  ---
    15_3_0
    15_3_1
    15_3_2

  path FullText
    step
      --
        15_3_0
    step
      --
        15_3_1
    step
      --
        15_3_2

    