
/ Coupled Equilibria
story 15_3
  >
    As discussed in preceding chapters on equilibrium,  *coupled equilibria* involve two or more separate chemical reactions that share one or more reactants or products. This section of this chapter will address solubility equilibria coupled with acid-base and complex-formation reactions.
    
    An environmentally relevant example illustrating the coupling of solubility and acid-base equilibria is the impact of ocean acidification on the health of the ocean’s coral reefs. These reefs are built upon skeletons of sparingly soluble calcium carbonate excreted by colonies of corals (small marine invertebrates). The relevant dissolution equilibrium is
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>CaCO</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msup><mrow><mtext>Ca</mtext></mrow><mrow><mn>2</mn><mo>+</mo></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo>+</mo><mspace width="0.2em"/><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mrow><mo>−</mo><mn>2</mn><mspace width="0.2em"/></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="5em"/><msub><mi>K</mi><mrow><mtext>sp</mtext></mrow></msub><mspace width="0.2em"/><mo>=</mo><mspace width="0.2em"/><mn>8.7</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mo>−</mo><mn>9</mn></mrow></msup></mrow></math>
    
    Rising concentrations of atmospheric carbon dioxide contribute to an increased acidity of ocean waters due to the dissolution, hydrolysis, and acid ionization of carbon dioxide:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>CO</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>g</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mtext>CO</mtext><mn>2</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>CO</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo>+</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtable><mtr><mtd columnalign="center"><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo> </mo><mspace width="0.2em"/><mo>+</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mrow><mtext>HCO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mrow><mo>−</mo></mrow></msup><mspace width="0.2em"/><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo>+</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mo>+</mo></msup><mspace width="0.2em"/><mrow><mo>(</mo><mrow><mi>a</mi><mi>q</mi></mrow><mo>)</mo></mrow><mo> </mo></mtd><mtd/><mtd columnalign="center"><msub><mi>K</mi><mrow><mtext>a</mtext><mn>1</mn></mrow></msub><mspace width="0.2em"/><mo>=</mo><mspace width="0.2em"/><mn>4.3</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mo>−</mo><mn>7</mn></mrow></msup></mtd></mtr></mtable></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtable><mtr><mtd columnalign="center"><msub><mrow><mtext>HCO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mrow><mo>−</mo></mrow></msup><mspace width="0.2em"/><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo>+</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mrow><mtext>CO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mrow><mn>2</mn><mo>−</mo><mspace width="0.2em"/></mrow></msup><mspace width="0.2em"/><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo>+</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mo>+</mo></msup><mspace width="0.2em"/><mrow><mo>(</mo><mrow><mi>a</mi><mi>q</mi></mrow><mo>)</mo></mrow></mtd><mtd/><mtd columnalign="center"><msub><mi>K</mi><mrow><mtext>a</mtext><mn>2</mn><mo> </mo></mrow></msub><mspace width="0.2em"/><mo>=</mo><mspace width="0.2em"/><mn>4.7</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mo>−</mo><mn>11</mn></mrow></msup></mtd></mtr></mtable></mrow></math>
    
    Inspection of these equilibria shows the carbonate ion is involved in the calcium carbonate dissolution and the acid hydrolysis of bicarbonate ion. Combining the dissolution equation with the reverse of the acid hydrolysis equation yields
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtable><mtr><mtd columnalign="center"><msub><mrow><mtext>CaCO</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo>+</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mo>+</mo></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msup><mrow><mtext>Ca</mtext></mrow><mrow><mn>2</mn><mo>+</mo></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo>+</mo><mspace width="0.2em"/><msub><mrow><mtext>HCO</mtext></mrow><mn>3</mn></msub><msup><mrow/><mrow><mo>−</mo></mrow></msup><mspace width="0.2em"/><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo>+</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mo> </mo></mtd><mtd/><mtd columnalign="center"><mi>K</mi><mspace width="0.2em"/><mo>=</mo><mspace width="0.2em"/><msub><mi>K</mi><mrow><mtext>sp</mtext></mrow></msub><mspace width="0.2em"/><mtext>/</mtext><mspace width="0.2em"/><msub><mi>K</mi><mrow><mtext>a</mtext><mn>2</mn></mrow></msub><mspace width="0.2em"/><mo>=</mo><mspace width="0.2em"/><mn>180</mn></mtd></mtr></mtable></mrow></math>
    
    The equilibrium constant for this net reaction is much greater than the  *Ksp* for calcium carbonate, indicating its solubility is markedly increased in acidic solutions. As rising carbon dioxide levels in the atmosphere increase the acidity of ocean waters, the calcium carbonate skeletons of coral reefs become more prone to dissolution and subsequently less healthy ({'Figure_15_3_CoralReef Figure 15.3.CoralReef}).
    
    
            
    
    The dramatic increase in solubility with increasing acidity described above for calcium carbonate is typical of salts containing basic anions (e.g., carbonate, fluoride, hydroxide, sulfide). Another familiar example is the formation of dental cavities in tooth enamel. The major mineral component of enamel is calcium hydroxyapatite ({'Figure_15_3_Apatite Figure 15.3.Apatite}), a sparingly soluble ionic compound whose dissolution equilibrium is
    
    <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>Ca</mtext><mtext>5</mtext></msub><mo stretchy="false">(</mo><msub><mrow><mtext>P</mtext><msub><mrow><mtext>O</mtext></mrow><mn>4</mn></msub><mo stretchy="false">)</mo></mrow><mn>3</mn></msub><mtext>OH</mtext><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><mn>5</mn><msup><mrow><mtext>Ca</mtext></mrow><mrow><mtext>2+</mtext></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><mn>3</mn><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mrow><mtext>3−</mtext></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
    
    
            
    
    This compound dissolved to yield two different basic ions: triprotic phosphate ions
    
    <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mrow><mtext>3−</mtext></mrow></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mn>+</mn></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mrow><mtext>2−</mtext></mrow></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi fontstyle="italic">l</mi><mo stretchy="false">)</mo></mrow></math>
    
    <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mrow><mtext>2−</mtext></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mn>+</mn></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi fontstyle="italic">l</mi><mo stretchy="false">)</mo></mrow></math>
    
    <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mn>2</mn></msub><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mn>+</mn></msup><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mn>3</mn></msub><msub><mrow><mtext>PO</mtext></mrow><mn>4</mn></msub><mo stretchy="false">(</mo><mi fontstyle="italic">aq</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi fontstyle="italic">l</mi><mo stretchy="false">)</mo></mrow></math>
    
    and monoprotic hydroxide ions:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mn>+</mn></msup><mspace width="0.2em"/><mo stretchy="false">⟶</mo><mspace width="0.2em"/><mn>2</mn><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext></mrow></math>
    
    Of the two basic productions, the hydroxide is, of course, by far the stronger base (it’s the strongest base that can exist in aqueous solution), and so it is the dominant factor providing the compound an acid-dependent solubility. Dental cavities form when the acid waste of bacteria growing on the surface of teeth hastens the dissolution of tooth enamel by reacting completely with the strong base hydroxide, shifting the hydroxyapatite solubility equilibrium to the right. Some toothpastes and mouth rinses contain added NaF or SnF<sub>2</sub> that make enamel more acid resistant by replacing the strong base hydroxide with the weak base fluoride:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>NaF</mtext><mo>+</mo><msub><mrow><mtext>Ca</mtext></mrow><mtext>5</mtext></msub><mo stretchy="false">(</mo><msub><mrow><mtext>P</mtext><msub><mrow><mtext>O</mtext></mrow><mn>4</mn></msub><mo stretchy="false">)</mo></mrow><mn>3</mn></msub><mtext>OH</mtext><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mrow><mtext>Ca</mtext></mrow><mtext>5</mtext></msub><mo stretchy="false">(</mo><msub><mrow><mtext>P</mtext><msub><mrow><mtext>O</mtext></mrow><mn>4</mn></msub><mo stretchy="false">)</mo></mrow><mn>3</mn></msub><mtext>F</mtext><mo>+</mo><msup><mrow><mtext>Na</mtext></mrow><mn>+</mn></msup><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup></mrow></math>
    
    The weak base fluoride ion reacts only partially with the bacterial acid waste, resulting in a less extensive shift in the solubility equilibrium and an increased resistance to acid dissolution. See the Chemistry in Everyday Life feature on the role of fluoride in preventing tooth decay for more information.
    
    The solubility of ionic compounds may also be increased when dissolution is coupled to the formation of a complex ion. For example, aluminum hydroxide dissolves in a solution of sodium hydroxide or another strong base because of the formation of the complex ion <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>Al</mtext><msub><mrow><mo stretchy="false">(</mo><mtext>OH</mtext><mo stretchy="false">)</mo></mrow><mn>4</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo>.</mo></mrow></math>
    
    
            
    
    The equations for the dissolution of aluminum hydroxide, the formation of the complex ion, and the combined (net) equation are shown below. As indicated by the relatively large value of K for the net reaction, coupling complex formation with dissolution drastically increases the solubility of Al(OH)<sub>3</sub>.
    
    <math xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtable><mtr><mtd columnalign="center"><mtext>Al</mtext><msub><mrow><mo stretchy="false">(</mo><mtext>OH</mtext><mo stretchy="false">)</mo></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msup><mrow><mtext>Al</mtext></mrow><mrow><mtext>3+</mtext></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><mn>3</mn><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mtd><mtd/><mtd columnalign="center"><msub><mi>K</mi><mrow><mtext>sp</mtext></mrow></msub><mo>=</mo><mn>2</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mo>−</mo><mn>32</mn></mrow></msup></mtd></mtr><mtr><mtd columnalign="center"><msup><mrow><mtext>Al</mtext></mrow><mrow><mtext>3+</mtext></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><mn>4</mn><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><mtext>Al</mtext><msub><mrow><mo stretchy="false">(</mo><mtext>OH</mtext><mo stretchy="false">)</mo></mrow><mn>4</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mtd><mtd/><mtd columnalign="center"><msub><mi>K</mi><mrow><mtext>f</mtext></mrow></msub><mo>=</mo><mn>1.1</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mn>33</mn></mrow></msup></mtd></mtr><mtr><mtd columnalign="center"><mtext>Net:</mtext><mspace width="0.2em"/><mtext>Al</mtext><msub><mrow><mo stretchy="false">(</mo><mtext>OH</mtext><mo stretchy="false">)</mo></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>s</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><mtext>Al</mtext><msub><mrow><mo stretchy="false">(</mo><mtext>OH</mtext><mo stretchy="false">)</mo></mrow><mn>4</mn></msub><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mtd><mtd/><mtd columnalign="center"><mi>K</mi><mo>=</mo><msub><mi>K</mi><mrow><mtext>sp</mtext></mrow></msub><mspace width="0.2em"/><msub><mi>K</mi><mtext>f</mtext></msub><mo>=</mo><mn>22</mn></mtd></mtr></mtable></mrow></math>

  apply FullText

  ---
    15_3_0
    15_3_1

  / Coupled Equilibria - Full Text
  path FullText
    step
      --
        15_3_0
    step
      --
        15_3_1

    