
/ Relative Strengths of Acids and Bases
story 14_3
  >
    We can rank the strengths of acids by the extent to which they ionize in aqueous solution. The reaction of an acid with water is given by the general expression:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>HA</mtext><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>A</mtext><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
    
    Water is the base that reacts with the acid HA, A<sup>−</sup> is the conjugate base of the acid HA, and the hydronium ion is the conjugate acid of water. A strong acid yields 100% (or very nearly so) of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mrow><mtext>+</mtext></mrow></msup></mrow></math> and A<sup>−</sup> when the acid ionizes in water; {'Figure_14_3_strong Figure 14.3.strong} lists several strong acids. A weak acid gives small amounts of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mrow><mtext>+</mtext></mrow></msup></mrow></math> and A<sup>−</sup>.
    
    
            
    
    The relative strengths of acids may be determined by measuring their equilibrium constants in aqueous solutions. In solutions of the same concentration, stronger acids ionize to a greater extent, and so yield higher concentrations of hydronium ions than do weaker acids. The equilibrium constant for an acid is called the  **acid-ionization constant, Ka**. For the reaction of an acid HA:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>HA</mtext><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>A</mtext><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>,</mo></mrow></math>
    
    we write the equation for the ionization constant as:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mi>K</mi><mtext>a</mtext></msub><mo>=</mo><mfrac><mrow><mo stretchy="false">[</mo><msub><mtext>H</mtext><mn>3</mn></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">]</mo><mo stretchy="false">[</mo><msup><mtext>A</mtext><mtext>−</mtext></msup><mo stretchy="false">]</mo></mrow><mrow><mtext>[HA]</mtext></mrow></mfrac></mrow></math>
    
    where the concentrations are those at equilibrium. Although water is a reactant in the reaction, it is the solvent as well, so we do not include [H<sub>2</sub>O] in the equation. The larger the  *K*<sub>a</sub> of an acid, the larger the concentration of <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mrow><mtext>+</mtext></mrow></msup></mrow></math> and A<sup>−</sup> relative to the concentration of the nonionized acid, HA. Thus a stronger acid has a larger ionization constant than does a weaker acid. The ionization constants increase as the strengths of the acids increase. (A table of ionization constants of weak acids appears in <link:>, with a partial listing in .)
    
    The following data on acid-ionization constants indicate the order of acid strength CH<sub>3</sub>CO<sub>2</sub>H < HNO<sub>2</sub> < <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>HSO</mtext></mrow><mn>4</mn></msub><mrow/><msup><mrow/><mtext>−</mtext></msup><mo>:</mo></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>CH</mtext></mrow><mn>3</mn></msub><mrow/><msub><mrow><mtext>CO</mtext></mrow><mn>2</mn></msub><mtext>H</mtext><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mrow><mtext>CH</mtext></mrow><mn>3</mn></msub><mrow/><msub><mrow><mtext>CO</mtext></mrow><mn>2</mn></msub><mrow/><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="5em"/><msub><mi>K</mi><mtext>a</mtext></msub><mo>=</mo><mn>1.8</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mn>−5</mn></mrow></msup></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>HNO</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mrow><mtext>NO</mtext></mrow><mn>2</mn></msub><mrow/><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="5em"/><msub><mi>K</mi><mtext>a</mtext></msub><mo>=</mo><mn>4.6</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mn>−4</mn></mrow></msup></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>HSO</mtext></mrow><mn>4</mn></msub><mrow/><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mrow><mtext>SO</mtext></mrow><mn>4</mn></msub><mrow/><msup><mrow/><mrow><mn>2−</mn></mrow></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="5em"/><msub><mi>K</mi><mtext>a</mtext></msub><mo>=</mo><mn>1.2</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mn>−2</mn></mrow></msup></mrow></math>
    
    Another measure of the strength of an acid is its percent ionization. The  **percent ionization** of a weak acid is the ratio of the concentration of the ionized acid to the initial acid concentration, times 100:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>% ionization</mtext><mo>=</mo><mspace width="0.2em"/><mfrac><mrow><msub><mrow><mo stretchy="false">[</mo><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">]</mo></mrow><mrow><mtext>eq</mtext></mrow></msub></mrow><mrow><msub><mrow><mo stretchy="false">[</mo><mtext>HA]</mtext></mrow><mn>0</mn></msub></mrow></mfrac><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><mn>100</mn></mrow></math>
    
    Because the ratio includes the initial concentration, the percent ionization for a solution of a given weak acid varies depending on the original concentration of the acid, and actually decreases with increasing acid concentration.
    
    We can rank the strengths of bases by their tendency to form hydroxide ions in aqueous solution. The reaction of a Brønsted-Lowry base with water is given by:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>B</mtext><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msup><mrow><mtext>HB</mtext></mrow><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
    
    Water is the acid that reacts with the base, HB<sup>+</sup> is the conjugate acid of the base B, and the hydroxide ion is the conjugate base of water. A strong base yields 100% (or very nearly so) of OH<sup>−</sup> and HB<sup>+</sup> when it reacts with water; {'Figure_14_3_strong Figure 14.3.strong} lists several strong bases. A weak base yields a small proportion of hydroxide ions. Soluble ionic hydroxides such as NaOH are considered strong bases because they dissociate completely when dissolved in water.
    
    As we did with acids, we can measure the relative strengths of bases by measuring their  **base-ionization constant (Kb)** in aqueous solutions. In solutions of the same concentration, stronger bases ionize to a greater extent, and so yield higher hydroxide ion concentrations than do weaker bases. A stronger base has a larger ionization constant than does a weaker base. For the reaction of a base, B:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>B</mtext><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msup><mrow><mtext>HB</mtext></mrow><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>,</mo></mrow></math>
    
    we write the equation for the ionization constant as:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mi>K</mi><mtext>b</mtext></msub><mo>=</mo><mspace width="0.2em"/><mfrac><mrow><mrow><mo stretchy="false">[</mo><mrow><msup><mrow><mtext>HB</mtext></mrow><mtext>+</mtext></msup></mrow><mo stretchy="false">]</mo></mrow><mrow><mo>[</mo><mrow><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup></mrow><mo>]</mo></mrow></mrow><mrow><mrow><mo>[</mo><mtext>B</mtext><mo>]</mo></mrow></mrow></mfrac></mrow></math>
    
    where the concentrations are those at equilibrium. Again, we do not include [H<sub>2</sub>O] in the equation because water is the solvent. The chemical reactions and ionization constants of the three bases shown are:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>NO</mtext></mrow><mn>2</mn></msub><mrow/><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mrow><mtext>HNO</mtext></mrow><mn>2</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="5em"/><msub><mi>K</mi><mtext>b</mtext></msub><mo>=</mo><mn>2.22</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mn>−11</mn></mrow></msup></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>CH</mtext></mrow><mn>3</mn></msub><mrow/><msub><mrow><mtext>CO</mtext></mrow><mn>2</mn></msub><mrow/><msup><mrow/><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mrow><mtext>CH</mtext></mrow><mn>3</mn></msub><mrow/><msub><mrow><mtext>CO</mtext></mrow><mn>2</mn></msub><mtext>H</mtext><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="5em"/><msub><mi>K</mi><mtext>b</mtext></msub><mo>=</mo><mn>5.6</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mn>−10</mn></mrow></msup></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>NH</mtext></mrow><mn>3</mn></msub><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mrow><mtext>NH</mtext></mrow><mn>4</mn></msub><mrow/><msup><mrow/><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="5em"/><msub><mi>K</mi><mtext>b</mtext></msub><mo>=</mo><mn>1.8</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mn>−5</mn></mrow></msup></mrow></math>
    
    A table of ionization constants of weak bases appears in <link:> (with a partial list in ). As with acids, percent ionization can be measured for basic solutions, but will vary depending on the base ionization constant and the initial concentration of the solution.
    
    Consider the ionization reactions for a conjugate acid-base pair, HA − A<sup>−</sup>:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mtext>HA</mtext><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mtext>A</mtext><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="5em"/><msub><mi>K</mi><mtext>a</mtext></msub><mo>=</mo><mspace width="0.2em"/><mfrac><mrow><mrow><mo stretchy="false">[</mo><mrow><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mrow><mtext>+</mtext></mrow></msup></mrow><mo stretchy="false">]</mo></mrow><mrow><mo>[</mo><mrow><msup><mtext>A</mtext><mtext>−</mtext></msup></mrow><mo>]</mo></mrow></mrow><mrow><mrow><mo>[</mo><mrow><mtext>HA</mtext></mrow><mo>]</mo></mrow></mrow></mfrac></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msup><mtext>A</mtext><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><mtext>HA</mtext><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mspace width="5em"/><msub><mi>K</mi><mtext>b</mtext></msub><mo>=</mo><mspace width="0.2em"/><mfrac><mrow><mrow><mo>[</mo><mrow><mtext>HA</mtext></mrow><mo>]</mo></mrow><mrow><mo>[</mo><mrow><mtext>OH</mtext></mrow><mo>]</mo></mrow></mrow><mrow><mrow><mo>[</mo><mrow><msup><mtext>A</mtext><mtext>−</mtext></msup></mrow><mo>]</mo></mrow></mrow></mfrac></mrow></math>
    
    Adding these two chemical equations yields the equation for the autoionization for water:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><menclose notation="horizontalstrike"><mrow><mtext>HA(</mtext><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></menclose><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mo>+</mo><menclose notation="horizontalstrike"><mrow><msup><mtext>A</mtext><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></menclose><mo>+</mo><msub><mtext>H</mtext><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><menclose notation="horizontalstrike"><mrow><msup><mtext>A</mtext><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></menclose><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><menclose notation="horizontalstrike"><mrow><mtext>HA(</mtext><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></menclose></mrow></math>
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mrow><mtext>2H</mtext></mrow><mn>2</mn></msub><mtext>O</mtext><mo stretchy="false">(</mo><mi>l</mi><mo stretchy="false">)</mo><mspace width="0.2em"/><mo stretchy="false">⇌</mo><mspace width="0.2em"/><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mtext>+</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo><mo>+</mo><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">(</mo><mi>a</mi><mi>q</mi><mo stretchy="false">)</mo></mrow></math>
    
    Because of the way mass-action expressions are defined, the  *K* expression for any chemical equation that is derived by adding together two or more other equations is equal to the mathematical product of the other equations’  *K* expressions. Multiplying the mass-action expressions together and canceling common terms, we see that:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mi>K</mi><mtext>a</mtext></msub><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msub><mi>K</mi><mtext>b</mtext></msub><mo>=</mo><mspace width="0.2em"/><mfrac><mrow><mo stretchy="false">[</mo><mrow><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mrow><mtext>+</mtext></mrow></msup></mrow><mo stretchy="false">]</mo><mo stretchy="false">[</mo><msup><mtext>A</mtext><mrow><mtext>−</mtext></mrow></msup><mo stretchy="false">]</mo></mrow><mrow><mtext>[HA]</mtext></mrow></mfrac><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><mfrac><mrow><mrow><mtext>[HA]</mtext></mrow><mrow><mo>[</mo><mrow><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup></mrow><mo>]</mo></mrow></mrow><mrow><mrow><mo>[</mo><mrow><msup><mtext>A</mtext><mtext>−</mtext></msup></mrow><mo>]</mo></mrow></mrow></mfrac><mspace width="0.2em"/><mo>=</mo><mrow><mo stretchy="false">[</mo><mrow><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mrow><mtext>+</mtext></mrow></msup></mrow><mo stretchy="false">]</mo></mrow><mrow><mo>[</mo><mrow><msup><mrow><mtext>OH</mtext></mrow><mtext>−</mtext></msup></mrow><mo>]</mo></mrow><mo>=</mo><msub><mi>K</mi><mtext>w</mtext></msub></mrow></math>
    
    For example, the acid ionization constant of acetic acid (CH<sub>3</sub>COOH) is 1.8 <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mo>×</mo></math> 10<sup>−5</sup>, and the base ionization constant of its conjugate base, acetate ion <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><mo stretchy="false">(</mo><msub><mrow><mtext>CH</mtext></mrow><mn>3</mn></msub><mrow/><msup><mrow><mtext>COO</mtext></mrow><mtext>−</mtext></msup><mo stretchy="false">)</mo><mo>,</mo></mrow></math> is 5.6 <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mo>×</mo></math> 10<sup>−10</sup>. The product of these two constants is indeed equal to  *K*<sub>w</sub>:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mi>K</mi><mtext>a</mtext></msub><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msub><mi>K</mi><mtext>b</mtext></msub><mo>=</mo><mrow><mo stretchy="false">(</mo><mrow><mn>1.8</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mn>−5</mn></mrow></msup></mrow><mo stretchy="false">)</mo></mrow><mspace width="0.4em"/><mo>×</mo><mspace width="0.2em"/><mrow><mo stretchy="false">(</mo><mrow><mn>5.6</mn><mspace width="0.4em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mn>−10</mn></mrow></msup></mrow><mo stretchy="false">)</mo></mrow><mo>=</mo><mn>1.0</mn><mspace width="0.2em"/><mo>×</mo><mspace width="0.2em"/><msup><mrow><mn>10</mn></mrow><mrow><mn>−14</mn></mrow></msup><mo>=</mo><msub><mi>K</mi><mtext>w</mtext></msub></mrow></math>
    
    The extent to which an acid, HA, donates protons to water molecules depends on the strength of the conjugate base, A<sup>−</sup>, of the acid. If A<sup>−</sup> is a strong base, any protons that are donated to water molecules are recaptured by A<sup>−</sup>. Thus there is relatively little A<sup>−</sup> and <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:bib="http://bibtexml.sf.net/" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><mrow><msub><mtext>H</mtext><mrow><mn>3</mn></mrow></msub><msup><mtext>O</mtext><mrow><mtext>+</mtext></mrow></msup></mrow></math> in solution, and the acid, HA, is weak. If A<sup>−</sup> is a weak base, water binds the protons more strongly, and the solution contains primarily A<sup>−</sup> and H<sub>3</sub>O<sup>+</sup>—the acid is strong. Strong acids form very weak conjugate bases, and weak acids form stronger conjugate bases ({'Figure_14_3_strengths Figure 14.3.strengths}).
    
    
            
    
    {'Figure_14_3_Corresp Figure 14.3.Corresp} lists a series of acids and bases in order of the decreasing strengths of the acids and the corresponding increasing strengths of the bases. The acid and base in a given row are conjugate to each other.
    
    
            
    
    The first six acids in {'Figure_14_3_Corresp Figure 14.3.Corresp} are the most common strong acids. These acids are completely dissociated in aqueous solution. The conjugate bases of these acids are weaker bases than water. When one of these acids dissolves in water, their protons are completely transferred to water, the stronger base.
    
    Those acids that lie between the hydronium ion and water in {'Figure_14_3_Corresp Figure 14.3.Corresp} form conjugate bases that can compete with water for possession of a proton. Both hydronium ions and nonionized acid molecules are present in equilibrium in a solution of one of these acids. Compounds that are weaker acids than water (those found below water in the column of acids) in {'Figure_14_3_Corresp Figure 14.3.Corresp} exhibit no observable acidic behavior when dissolved in water. Their conjugate bases are stronger than the hydroxide ion; if any conjugate base were formed, it would react with water to form the hydroxide ion.
    
    The extent to which a base forms hydroxide ion in aqueous solution depends on the strength of the base relative to that of the hydroxide ion, as shown in the last column in {'Figure_14_3_Corresp Figure 14.3.Corresp}. A strong base, such as one of those lying below hydroxide ion, accepts protons from water to yield 100% of the conjugate acid and hydroxide ion. Those bases lying between water and hydroxide ion accept protons from water, but a mixture of the hydroxide ion and the base results. Bases that are weaker than water (those that lie above water in the column of bases) show no observable basic behavior in aqueous solution.

  apply FullText

  ---
    14_3_0
    14_3_1
    14_3_2
    14_3_3
    14_3_4
    14_3_5

  path FullText
    step
      --
        14_3_0
    step
      --
        14_3_1
    step
      --
        14_3_2
    step
      --
        14_3_3
    step
      --
        14_3_4
    step
      --
        14_3_5

    