
/ Centripetal Force
story 6_3
  >
    Any force or combination of forces can cause a centripetal or radial acceleration. Just a few examples are the tension in the rope on a tether ball, the force of Earth’s gravity on the Moon, friction between roller skates and a rink floor, a banked roadway’s force on a car, and forces on the tube of a spinning centrifuge.
    
    Any net force causing uniform circular motion is called a  **centripetal force**. The direction of a centripetal force is toward the center of curvature, the same as the direction of centripetal acceleration. According to Newton’s second law of motion, net force is mass times acceleration: net <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mtext>F</mtext><mo stretchy="false">=</mo><mstyle fontstyle="italic"><mrow><mtext>ma</mtext></mrow></mstyle></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;F= ital &quot;ma&quot;&#125; &#123;&#125;</annotation></semantics></math>. For uniform circular motion, the acceleration is the centripetal acceleration— <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>a</mi><mo stretchy="false">=</mo><msub><mi>a</mi><mrow><mi>c</mi></mrow></msub></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a=a rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>. Thus, the magnitude of centripetal force <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mtext>F</mtext><mrow><mtext>c</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;F rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <msub>                    <mtext>F</mtext>                                          <mrow>                        <mtext>c</mtext>                      </mrow>                                      </msub>                  <mo stretchy="false">=</mo>                  <msub>                    <mrow><mi fontstyle="italic">m</mi>                    <mtext fontstyle="italic">a</mtext>                                            </mrow>                        <mtext>c</mtext>                                      </msub>                </mrow><mo>.</mo>              </mrow>                      </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;F rSub &#123; size 8&#123;c&#125; &#125; =ma rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    By using the expressions for centripetal acceleration <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>a</mi><mrow><mi>c</mi></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> from <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><msub><mi>a</mi><mrow><mi>c</mi></mrow></msub><mo stretchy="false">=</mo><mfrac><msup><mi>v</mi><mrow><mn>2</mn></mrow></msup><mi>r</mi></mfrac></mrow><mi>;</mi><mspace width="0.25em"/><mrow><msub><mi>a</mi><mrow><mi>c</mi></mrow></msub><mo stretchy="false">=</mo><msup><mi fontstyle="italic">rω</mi><mrow><mn>2</mn></mrow></msup></mrow></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a rSub &#123; size 8&#123;c&#125; &#125; = &#123;  &#123;v rSup &#123; size 8&#123;2&#125; &#125; &#125;  over  &#123;r&#125; &#125; ;``a rSub &#123; size 8&#123;c&#125; &#125; =rω rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>, we get two expressions for the centripetal force <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mtext>F</mtext><mrow><mtext>c</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;F rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> in terms of mass, velocity, angular velocity, and radius of curvature:
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                  <mrow>                    <msub>                      <mi>F</mi>                                              <mrow>                          <mi>c</mi>                        </mrow>                                          </msub>                    <mo stretchy="false">=</mo>                    <mi>m</mi>                  </mrow>                  <mfrac>                    <msup>                      <mi>v</mi>                                              <mrow>                          <mn>2</mn>                        </mrow>                                          </msup>                    <mi>r</mi>                  </mfrac>                  <mi>;</mi><mspace width="0.25em"/>                  <mrow>                    <msub>                      <mi>F</mi>                                              <mrow>                          <mi>c</mi>                        </mrow>                                          </msub>                    <mo stretchy="false">=</mo>                    <mstyle fontstyle="italic">                      <mrow>                        <mtext>mr</mtext>                      </mrow>                    </mstyle>                  </mrow>                  <msup>                    <mi>ω</mi>                                          <mrow>                        <mn>2</mn>                      </mrow>                                      </msup>                </mrow><mo>.</mo>              </mrow>          </mrow>          <annotation encoding="StarMath 5.0"> size 12&#123;F rSub &#123; size 8&#123;c&#125; &#125; =m &#123;  &#123;v rSup &#123; size 8&#123;2&#125; &#125; &#125;  over  &#123;r&#125; &#125; ;``F rSub &#123; size 8&#123;c&#125; &#125; = ital &quot;mr&quot;ω rSup &#123; size 8&#123;2&#125; &#125; &#125; &#123;&#125;</annotation>        </semantics>      </math>     
    
    You may use whichever expression for centripetal force is more convenient. Centripetal force <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi>F</mi><mrow><mtext>c</mtext></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;F rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is always perpendicular to the path and pointing to the center of curvature, because <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><msub><mi mathvariant="bold">a</mi><mrow><mi>c</mi></mrow></msub></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;a rSub &#123; size 8&#123;c&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math> is perpendicular to the velocity and pointing to the center of curvature.
    
    Note that if you solve the first expression for <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>r</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;r&#125; &#123;&#125;</annotation></semantics></math>, you get
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>r</mi><mo stretchy="false">=</mo><mfrac><mrow><msup><mrow><mi fontstyle="italic">mv</mi></mrow><mrow><mn>2</mn></mrow></msup></mrow><msub><mi>F</mi><mrow><mi>c</mi></mrow></msub></mfrac></mrow></mrow><mrow><mtext>.</mtext></mrow></mrow><annotation encoding="StarMath 5.0"> size 12&#123;r= &#123;  &#123; ital &quot;mv&quot; rSup &#123; size 8&#123;2&#125; &#125; &#125;  over  &#123;F rSub &#123; size 8&#123;c&#125; &#125; &#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    This implies that for a given mass and velocity, a large centripetal force causes a small radius of curvature—that is, a tight curve.
    
    
            
    
    
            
    
    Let us now consider  **banked curves**, where the slope of the road helps you negotiate the curve. See {'Figure_7_3_3a Figure 7.3.3a}. The greater the angle <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>θ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ&#125; &#123;&#125;</annotation></semantics></math>, the faster you can take the curve. Race tracks for bikes as well as cars, for example, often have steeply banked curves. In an “ideally banked curve,” the angle <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>θ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ&#125; &#123;&#125;</annotation></semantics></math> is such that you can negotiate the curve at a certain speed without the aid of friction between the tires and the road. We will derive an expression for <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>θ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ&#125; &#123;&#125;</annotation></semantics></math> for an ideally banked curve and consider an example related to it.
    
    For  **ideal banking**, the net external force equals the horizontal centripetal force in the absence of friction. The components of the normal force N in the horizontal and vertical directions must equal the centripetal force and the weight of the car, respectively. In cases in which forces are not parallel, it is most convenient to consider components along perpendicular axes—in this case, the vertical and horizontal directions.
    
    {'Figure_7_3_3a Figure 7.3.3a} shows a free body diagram for a car on a frictionless banked curve. If the angle <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>θ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ&#125; &#123;&#125;</annotation></semantics></math> is ideal for the speed and radius, then the net external force will equal the necessary centripetal force. The only two external forces acting on the car are its weight <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi mathvariant="bold">w</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;w&#125; &#123;&#125;</annotation></semantics></math> and the normal force of the road <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi mathvariant="bold">N</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;N&#125; &#123;&#125;</annotation></semantics></math>. (A frictionless surface can only exert a force perpendicular to the surface—that is, a normal force.) These two forces must add to give a net external force that is horizontal toward the center of curvature and has magnitude <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><msup><mtext>mv</mtext><mrow><mn>2</mn></mrow></msup><mtext>/r</mtext></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;&quot;mv&quot; rSup &#123; size 8&#123;2&#125; &#125; &quot;/r&quot;&#125; &#123;&#125;</annotation></semantics></math>. Because this is the crucial force and it is horizontal, we use a coordinate system with vertical and horizontal axes. Only the normal force has a horizontal component, and so this must equal the centripetal force—that is,
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>N</mi><mspace width="0.25em"/><mtext>sin</mtext><mspace width="0.25em"/><mrow><mi>θ</mi><mo stretchy="false">=</mo><mfrac><mrow><msup><mi fontstyle="italic">mv</mi><mrow><mn>2</mn></mrow></msup></mrow><mi>r</mi></mfrac></mrow></mrow></mrow><mrow/><mrow><mtext>.</mtext></mrow></mrow><annotation encoding="StarMath 5.0"> size 12&#123;N&quot;sin&quot;θ= &#123;  &#123; ital &quot;mv&quot; rSup &#123; size 8&#123;2&#125; &#125; &#125;  over  &#123;r&#125; &#125; &#125; &#123;&#125;</annotation></semantics></math>
    
    Because the car does not leave the surface of the road, the net vertical force must be zero, meaning that the vertical components of the two external forces must be equal in magnitude and opposite in direction. From the figure, we see that the vertical component of the normal force is <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>N</mi><mspace width="0.25em"/><mtext>cos</mtext><mspace width="0.25em"/><mi>θ</mi></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;N&quot;cos&quot;θ&#125; &#123;&#125;</annotation></semantics></math>, and the only other vertical force is the car’s weight. These must be equal in magnitude; thus,
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mi>N</mi><mspace width="0.25em"/><mtext>cos</mtext><mspace width="0.25em"/><mrow><mi>θ</mi><mo stretchy="false">=</mo><mstyle fontstyle="italic"><mrow><mtext>mg</mtext></mrow></mstyle></mrow></mrow></mrow><mrow/><mrow><mtext>.</mtext></mrow></mrow><annotation encoding="StarMath 5.0"> size 12&#123;N&quot;cos&quot;θ= ital &quot;mg&quot;&#125; &#123;&#125;</annotation></semantics></math>
    
    Now we can combine the last two equations to eliminate <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>N</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;N&#125; &#123;&#125;</annotation></semantics></math> and get an expression for <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>θ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ&#125; &#123;&#125;</annotation></semantics></math>, as desired. Solving the second equation for <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mi>N</mi><mo stretchy="false">=</mo><mrow><mstyle fontstyle="italic"><mrow><mtext>mg</mtext></mrow></mstyle><mo stretchy="false">/</mo><mo stretchy="false">(</mo></mrow></mrow><mtext>cos</mtext><mspace width="0.25em"/><mi>θ</mi><mo stretchy="false">)</mo></mrow></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;N= ital &quot;mg&quot;/ \( &quot;cos&quot;θ \) &#125; &#123;&#125;</annotation></semantics></math>, and substituting this into the first yields
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml">        <semantics>          <mrow>                          <mrow>                <mrow>                    <mstyle fontstyle="italic">                      <mrow>                        <mtext>mg</mtext>                      </mrow>                    </mstyle>                  </mrow>                  <mrow>                    <mfrac>                      <mrow>                        <mtext>sin</mtext><mspace width="0.25em"/>                        <mi>θ</mi>                      </mrow>                      <mrow>                        <mtext>cos</mtext><mspace width="0.25em"/>                        <mi>θ</mi>                      </mrow>                    </mfrac>                    <mo stretchy="false">=</mo>                    <mfrac>                        <mrow>                          <msup>                      <mstyle fontstyle="italic">                            <mtext>mv</mtext>                                                  </mstyle>                              <mrow>                                <mn>2</mn>                              </mrow>                                                      </msup>                        </mrow>                      <mi>r</mi>                    </mfrac>                  </mrow>                </mrow>              </mrow>        </semantics>      </math>     
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mtable columnalign="right"><mtr><mtd><mtext fontstyle="italic">mg</mtext><mspace width="0.25em"/><mtext>tan</mtext><mo stretchy="false">(</mo><mi>θ</mi><mo stretchy="false">)</mo></mtd><mtd><mo stretchy="false">=</mo></mtd><mtd><mfrac><mrow><msup><mi fontstyle="italic">mv</mi><mn>2</mn></msup></mrow><mi>r</mi></mfrac></mtd></mtr><mtr><mtd><mtext>tan</mtext><mspace width="0.25em"/><mi>θ</mi></mtd><mtd><mo stretchy="false">=</mo></mtd><mtd><mfrac><msup><mi>v</mi><mrow><mn>2</mn></mrow></msup><mstyle fontstyle="italic"><mrow><mtext>rg.</mtext></mrow></mstyle></mfrac></mtd></mtr></mtable></mrow></mrow></semantics></math>
    
    Taking the inverse tangent gives
    
    <math xmlns:q="http://cnx.rice.edu/qml/1.0" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mrow><mrow><mi>θ</mi><mo stretchy="false">=</mo><msup><mtext>tan</mtext><mrow><mrow><mo stretchy="false">−</mo><mn>1</mn></mrow></mrow></msup></mrow><mfenced close=")" open="("><mfrac><msup><mi>v</mi><mrow><mn>2</mn></mrow></msup><mstyle fontstyle="italic"><mrow><mtext>rg</mtext></mrow></mstyle></mfrac></mfenced></mrow></mrow><mrow/><mrow><mspace width="0.25em"/><mtext> (ideally banked curve, no friction).</mtext></mrow></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ=&quot;tan&quot; rSup &#123; size 8&#123; - 1&#125; &#125;  left ( &#123;  &#123;v rSup &#123; size 8&#123;2&#125; &#125; &#125;  over  &#123; ital &quot;rg&quot;&#125; &#125;  right )&#125; &#123;&#125;</annotation></semantics></math>
    
    This expression can be understood by considering how <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>θ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ&#125; &#123;&#125;</annotation></semantics></math> depends on <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>v</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v&#125; &#123;&#125;</annotation></semantics></math> and <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>r</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;r&#125; &#123;&#125;</annotation></semantics></math>. A large <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>θ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ&#125; &#123;&#125;</annotation></semantics></math> will be obtained for a large <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>v</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;v&#125; &#123;&#125;</annotation></semantics></math> and a small <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>r</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;r&#125; &#123;&#125;</annotation></semantics></math>. That is, roads must be steeply banked for high speeds and sharp curves. Friction helps, because it allows you to take the curve at greater or lower speed than if the curve is frictionless. Note that <math xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:md="http://cnx.rice.edu/mdml" xmlns="http://cnx.rice.edu/cnxml"><semantics><mrow><mrow><mi>θ</mi></mrow><mrow/></mrow><annotation encoding="StarMath 5.0"> size 12&#123;θ&#125; &#123;&#125;</annotation></semantics></math> does not depend on the mass of the vehicle.
    
    
            

  apply FullText

  ---
    6_3_0
    6_3_1
    6_3_3

  path FullText
    step
      --
        6_3_0
    step
      --
        6_3_1
    step
      --
        6_3_3

    